# enrich_F.py — Fahrzeug-Enrichment Block F (54 Fahrzeuge, 2007–2012)
# Format: DATA[Name] = {gewicht, drehmoment, cw, kofferraum, laenge, tank, akku,
#   reichweite_km, verbrauch_l, verbrauch_kwh, antrieb, karosserie, antriebsart,
#   motorbauart, zylinder, turbo, getriebe, sitze, neupreis_eur, baujahr_ende,
#   nordschleife, konzern}

DATA = {
    "Opel Corsa OPC (Deutschland, 2007)": {
        "gewicht": 1175, "drehmoment": 230, "cw": 0.33, "kofferraum": 285,
        "laenge": 3999, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.4, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 4, "neupreis_eur": 21990,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "VW",
    },
    "Smart Fortwo Brabus (Deutschland, 2007)": {
        "gewicht": 760, "drehmoment": 150, "cw": 0.37, "kofferraum": 220,
        "laenge": 2695, "tank": 33, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.8, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 3, "turbo": True,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 15990,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Alfa Romeo 8C Competizione (Italien, 2007)": {
        "gewicht": 1585, "drehmoment": 470, "cw": 0.30, "kofferraum": 175,
        "laenge": 4380, "tank": 80, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.5, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Coupé", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 143000,
        "baujahr_ende": 2010, "nordschleife": 0, "konzern": "Stellantis",
    },
    "VW Passat B6 R36 (Deutschland, 2007)": {
        "gewicht": 1695, "drehmoment": 350, "cw": 0.30, "kofferraum": 565,
        "laenge": 4765, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.3, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 6, "turbo": False,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 42500,
        "baujahr_ende": 2010, "nordschleife": 0, "konzern": "VW",
    },
    "Mercedes-Benz C 180 W204 (Deutschland, 2007)": {
        "gewicht": 1455, "drehmoment": 230, "cw": 0.29, "kofferraum": 475,
        "laenge": 4581, "tank": 66, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.7, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 31500,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Audi A4 B8 (Deutschland, 2007)": {
        "gewicht": 1480, "drehmoment": 250, "cw": 0.29, "kofferraum": 480,
        "laenge": 4703, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.0, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 31900,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "VW",
    },
    "Peugeot 207 GTI (Frankreich, 2007)": {
        "gewicht": 1217, "drehmoment": 240, "cw": 0.33, "kofferraum": 270,
        "laenge": 4030, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.1, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 21900,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "Stellantis",
    },
    "Fiat Grande Punto Abarth (Italien, 2007)": {
        "gewicht": 1230, "drehmoment": 250, "cw": 0.33, "kofferraum": 275,
        "laenge": 4030, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.3, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 20500,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "Stellantis",
    },
    "Think City (Norwegen, 2008, EV)": {
        "gewicht": 1045, "drehmoment": 165, "cw": 0.36, "kofferraum": 220,
        "laenge": 3130, "tank": 0, "akku": 28.0, "reichweite_km": 160,
        "verbrauch_l": 0.0, "verbrauch_kwh": 18.0,
        "antrieb": "Heck", "karosserie": "Hatchback", "antriebsart": "EV",
        "motorbauart": "E-Motor", "zylinder": 0, "turbo": False,
        "getriebe": "E-Getriebe", "sitze": 2, "neupreis_eur": 29900,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "unabhängig",
    },
    "BMW M3 E92 (Deutschland, 2008)": {
        "gewicht": 1655, "drehmoment": 400, "cw": 0.30, "kofferraum": 440,
        "laenge": 4615, "tank": 63, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.0, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Coupé", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Handschalter", "sitze": 4, "neupreis_eur": 66000,
        "baujahr_ende": 2013, "nordschleife": 478, "konzern": "BMW",
    },
    "VW Golf 6 (Deutschland, 2008)": {
        "gewicht": 1246, "drehmoment": 175, "cw": 0.31, "kofferraum": 350,
        "laenge": 4199, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.7, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": False,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 17950,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "VW",
    },
    "Opel Insignia A (Deutschland, 2008)": {
        "gewicht": 1620, "drehmoment": 280, "cw": 0.29, "kofferraum": 500,
        "laenge": 4830, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.6, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 24900,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "Renault Megane III (Frankreich, 2008)": {
        "gewicht": 1285, "drehmoment": 190, "cw": 0.31, "kofferraum": 363,
        "laenge": 4300, "tank": 60, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.3, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 17400,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "Renault-Nissan",
    },
    "Buddy Electric (Norwegen, 2008)": {
        "gewicht": 640, "drehmoment": 115, "cw": 0.38, "kofferraum": 130,
        "laenge": 2660, "tank": 0, "akku": 12.0, "reichweite_km": 80,
        "verbrauch_l": 0.0, "verbrauch_kwh": 15.0,
        "antrieb": "Heck", "karosserie": "Hatchback", "antriebsart": "EV",
        "motorbauart": "E-Motor", "zylinder": 0, "turbo": False,
        "getriebe": "E-Getriebe", "sitze": 2, "neupreis_eur": 19900,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "unabhängig",
    },
    "Audi TTS 8J (Deutschland, 2008)": {
        "gewicht": 1395, "drehmoment": 350, "cw": 0.30, "kofferraum": 290,
        "laenge": 4178, "tank": 60, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.5, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Coupé", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 4, "neupreis_eur": 42900,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "VW",
    },
    "Ford Fiesta Mk7 (Deutschland, 2008)": {
        "gewicht": 1070, "drehmoment": 145, "cw": 0.33, "kofferraum": 295,
        "laenge": 3950, "tank": 42, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.2, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": False,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 12550,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "Ford",
    },
    "Golf 6 GTI (VW, Deutschland, 2009)": {
        "gewicht": 1358, "drehmoment": 280, "cw": 0.31, "kofferraum": 350,
        "laenge": 4199, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.0, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 26900,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "VW",
    },
    "Audi R8 V10 (Deutschland, 2009)": {
        "gewicht": 1620, "drehmoment": 530, "cw": 0.30, "kofferraum": 100,
        "laenge": 4431, "tank": 90, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 14.9, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Sportwagen", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 10, "turbo": False,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 140700,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "VW",
    },
    "Ferrari 458 Italia (Italien, 2009)": {
        "gewicht": 1380, "drehmoment": 540, "cw": 0.30, "kofferraum": 230,
        "laenge": 4527, "tank": 86, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.7, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Sportwagen", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 197000,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "unabhängig",
    },
    "Mercedes-Benz E 63 AMG T-Modell (Deutschland, 2009)": {
        "gewicht": 1945, "drehmoment": 630, "cw": 0.29, "kofferraum": 695,
        "laenge": 4899, "tank": 80, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.4, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Kombi", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 97750,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "Mercedes",
    },
    "VW Polo 5 (Deutschland, 2009)": {
        "gewicht": 1080, "drehmoment": 160, "cw": 0.32, "kofferraum": 280,
        "laenge": 3970, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.8, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": False,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 12225,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "Opel Astra J (Deutschland, 2009)": {
        "gewicht": 1300, "drehmoment": 200, "cw": 0.29, "kofferraum": 370,
        "laenge": 4419, "tank": 56, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.9, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 18450,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "VW",
    },
    "Opel Insignia A OPC (Deutschland, 2009)": {
        "gewicht": 1849, "drehmoment": 400, "cw": 0.29, "kofferraum": 500,
        "laenge": 4830, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.5, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 6, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 43900,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "Mercedes-Benz E 200 W212 (Deutschland, 2009)": {
        "gewicht": 1595, "drehmoment": 310, "cw": 0.27, "kofferraum": 540,
        "laenge": 4868, "tank": 66, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.1, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 41500,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Mercedes-Benz SLS AMG (Deutschland, 2010)": {
        "gewicht": 1620, "drehmoment": 650, "cw": 0.32, "kofferraum": 176,
        "laenge": 4638, "tank": 85, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.2, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Sportwagen", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 177310,
        "baujahr_ende": 2014, "nordschleife": 458, "konzern": "Mercedes",
    },
    "VW Polo 5 GTI (Deutschland, 2010)": {
        "gewicht": 1230, "drehmoment": 250, "cw": 0.32, "kofferraum": 280,
        "laenge": 3970, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.6, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 21500,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "VW Passat B7 (Deutschland, 2010)": {
        "gewicht": 1488, "drehmoment": 200, "cw": 0.29, "kofferraum": 565,
        "laenge": 4765, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.2, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 25825,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "VW",
    },
    "BMW 520i F10 (Deutschland, 2010)": {
        "gewicht": 1595, "drehmoment": 270, "cw": 0.25, "kofferraum": 520,
        "laenge": 4899, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.9, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 39500,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "BMW",
    },
    "Audi A8 3.0 TFSI D4 (Deutschland, 2010)": {
        "gewicht": 1945, "drehmoment": 440, "cw": 0.26, "kofferraum": 510,
        "laenge": 5137, "tank": 90, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 10.8, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 6, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 80200,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "Lamborghini Aventador LP700-4 (Italien, 2011)": {
        "gewicht": 1575, "drehmoment": 690, "cw": 0.33, "kofferraum": 150,
        "laenge": 4780, "tank": 90, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 17.2, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Sportwagen", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 12, "turbo": False,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 319765,
        "baujahr_ende": 2022, "nordschleife": 0, "konzern": "VW",
    },
    "Citroën DS3 Racing (Frankreich, 2011)": {
        "gewicht": 1170, "drehmoment": 275, "cw": 0.33, "kofferraum": 285,
        "laenge": 3948, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.8, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 4, "neupreis_eur": 26900,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "Stellantis",
    },
    "Pagani Huayra (Italien, 2011)": {
        "gewicht": 1350, "drehmoment": 1100, "cw": 0.37, "kofferraum": 60,
        "laenge": 4605, "tank": 90, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 19.6, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Sportwagen", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 12, "turbo": True,
        "getriebe": "Automatik", "sitze": 2, "neupreis_eur": 1150000,
        "baujahr_ende": 2018, "nordschleife": 0, "konzern": "unabhängig",
    },
    "VW Passat B7 V6 (Deutschland, 2011)": {
        "gewicht": 1715, "drehmoment": 350, "cw": 0.29, "kofferraum": 565,
        "laenge": 4765, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.3, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 6, "turbo": False,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 44800,
        "baujahr_ende": 2014, "nordschleife": 0, "konzern": "VW",
    },
    "BMW M5 F10 (Deutschland, 2011)": {
        "gewicht": 1870, "drehmoment": 680, "cw": 0.29, "kofferraum": 520,
        "laenge": 4907, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 12.5, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 99800,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "BMW",
    },
    "Audi RS3 8P (Deutschland, 2011)": {
        "gewicht": 1505, "drehmoment": 450, "cw": 0.33, "kofferraum": 290,
        "laenge": 4286, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 10.3, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 5, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 48900,
        "baujahr_ende": 2012, "nordschleife": 0, "konzern": "VW",
    },
    "BMW 116i F20 (Deutschland, 2011)": {
        "gewicht": 1305, "drehmoment": 200, "cw": 0.30, "kofferraum": 360,
        "laenge": 4324, "tank": 52, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.5, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 22550,
        "baujahr_ende": 2019, "nordschleife": 0, "konzern": "BMW",
    },
    "Ford Focus Mk3 (Deutschland, 2011)": {
        "gewicht": 1295, "drehmoment": 200, "cw": 0.30, "kofferraum": 316,
        "laenge": 4358, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.8, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 18400,
        "baujahr_ende": 2018, "nordschleife": 0, "konzern": "Ford",
    },
    "KTM X-Bow R (Österreich, 2012)": {
        "gewicht": 790, "drehmoment": 360, "cw": 0.49, "kofferraum": 0,
        "laenge": 3738, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.9, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Roadster", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 2, "neupreis_eur": 58900,
        "baujahr_ende": 0, "nordschleife": 487, "konzern": "unabhängig",
    },
    "Mercedes-Benz G 63 AMG (Deutschland, 2012)": {
        "gewicht": 2620, "drehmoment": 760, "cw": 0.55, "kofferraum": 667,
        "laenge": 4660, "tank": 96, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 16.9, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "SUV", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 159226,
        "baujahr_ende": 0, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Mercedes-Benz B 250 Sport (Deutschland, 2012)": {
        "gewicht": 1555, "drehmoment": 350, "cw": 0.26, "kofferraum": 486,
        "laenge": 4359, "tank": 60, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.0, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Van", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 31940,
        "baujahr_ende": 2018, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Mercedes-Benz CLS 63 AMG (Deutschland, 2012)": {
        "gewicht": 1915, "drehmoment": 800, "cw": 0.29, "kofferraum": 520,
        "laenge": 4996, "tank": 80, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 12.5, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Coupé", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": True,
        "getriebe": "Automatik", "sitze": 4, "neupreis_eur": 120070,
        "baujahr_ende": 2018, "nordschleife": 0, "konzern": "Mercedes",
    },
    "VW Golf 7 (Deutschland, 2012)": {
        "gewicht": 1205, "drehmoment": 200, "cw": 0.27, "kofferraum": 380,
        "laenge": 4255, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.7, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 18975,
        "baujahr_ende": 2020, "nordschleife": 0, "konzern": "VW",
    },
    "Opel Astra J OPC (Deutschland, 2012)": {
        "gewicht": 1435, "drehmoment": 400, "cw": 0.29, "kofferraum": 370,
        "laenge": 4419, "tank": 56, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.9, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 32990,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "VW",
    },
    "BMW 316i F30 (Deutschland, 2012)": {
        "gewicht": 1455, "drehmoment": 200, "cw": 0.26, "kofferraum": 480,
        "laenge": 4624, "tank": 60, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.4, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 28450,
        "baujahr_ende": 2019, "nordschleife": 0, "konzern": "BMW",
    },
    "Audi A3 8V (Deutschland, 2012)": {
        "gewicht": 1230, "drehmoment": 200, "cw": 0.29, "kofferraum": 365,
        "laenge": 4313, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.0, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 21400,
        "baujahr_ende": 2020, "nordschleife": 0, "konzern": "VW",
    },
    "Audi RS4 B8 (Deutschland, 2012)": {
        "gewicht": 1825, "drehmoment": 430, "cw": 0.32, "kofferraum": 490,
        "laenge": 4723, "tank": 70, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.5, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Kombi", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": False,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 72600,
        "baujahr_ende": 2015, "nordschleife": 0, "konzern": "VW",
    },
    "Peugeot 208 (Frankreich, 2012)": {
        "gewicht": 1035, "drehmoment": 150, "cw": 0.29, "kofferraum": 285,
        "laenge": 3963, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.7, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 3, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 13200,
        "baujahr_ende": 2019, "nordschleife": 0, "konzern": "Stellantis",
    },
    "Renault Clio IV (Frankreich, 2012)": {
        "gewicht": 1084, "drehmoment": 166, "cw": 0.30, "kofferraum": 300,
        "laenge": 4062, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.9, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 13990,
        "baujahr_ende": 2019, "nordschleife": 0, "konzern": "Renault-Nissan",
    },
    "Puli X3 (Ungarn, 2012)": {
        "gewicht": 850, "drehmoment": 160, "cw": 0.36, "kofferraum": 100,
        "laenge": 3200, "tank": 0, "akku": 18.0, "reichweite_km": 120,
        "verbrauch_l": 0.0, "verbrauch_kwh": 15.0,
        "antrieb": "Heck", "karosserie": "Roadster", "antriebsart": "EV",
        "motorbauart": "E-Motor", "zylinder": 0, "turbo": False,
        "getriebe": "E-Getriebe", "sitze": 2, "neupreis_eur": 0,
        "baujahr_ende": 0, "nordschleife": 0, "konzern": "unabhängig",
    },
    "BMW M135i F20 (Deutschland, 2012)": {
        "gewicht": 1450, "drehmoment": 450, "cw": 0.30, "kofferraum": 360,
        "laenge": 4324, "tank": 52, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.6, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 6, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 37600,
        "baujahr_ende": 2019, "nordschleife": 0, "konzern": "BMW",
    },
    "Mercedes-Benz A 160 W176 (Deutschland, 2012)": {
        "gewicht": 1385, "drehmoment": 200, "cw": 0.26, "kofferraum": 341,
        "laenge": 4292, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.5, "verbrauch_kwh": 0.0,
        "antrieb": "Front", "karosserie": "Hatchback", "antriebsart": "Benzin",
        "motorbauart": "Reihe", "zylinder": 4, "turbo": True,
        "getriebe": "Handschalter", "sitze": 5, "neupreis_eur": 23418,
        "baujahr_ende": 2018, "nordschleife": 0, "konzern": "Mercedes",
    },
    "Audi S8 D4 (Deutschland, 2012)": {
        "gewicht": 2050, "drehmoment": 650, "cw": 0.26, "kofferraum": 510,
        "laenge": 5137, "tank": 90, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.1, "verbrauch_kwh": 0.0,
        "antrieb": "Allrad", "karosserie": "Limousine", "antriebsart": "Benzin",
        "motorbauart": "V", "zylinder": 8, "turbo": True,
        "getriebe": "Automatik", "sitze": 5, "neupreis_eur": 104000,
        "baujahr_ende": 2017, "nordschleife": 0, "konzern": "VW",
    },
    "Porsche Boxster 981 (Deutschland, 2012)": {
        "gewicht": 1320, "drehmoment": 265, "cw": 0.31, "kofferraum": 280,
        "laenge": 4374, "tank": 64, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.1, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Cabrio", "antriebsart": "Benzin",
        "motorbauart": "Boxer", "zylinder": 6, "turbo": False,
        "getriebe": "Handschalter", "sitze": 2, "neupreis_eur": 49168,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "VW",
    },
    "Porsche Boxster S 981 (Deutschland, 2012)": {
        "gewicht": 1350, "drehmoment": 360, "cw": 0.31, "kofferraum": 280,
        "laenge": 4374, "tank": 64, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.3, "verbrauch_kwh": 0.0,
        "antrieb": "Heck", "karosserie": "Cabrio", "antriebsart": "Benzin",
        "motorbauart": "Boxer", "zylinder": 6, "turbo": False,
        "getriebe": "Handschalter", "sitze": 2, "neupreis_eur": 59168,
        "baujahr_ende": 2016, "nordschleife": 0, "konzern": "VW",
    },
}
