DATA = {
    "Kia Stinger GT (Südkorea, 2017)": {
        "gewicht": 1820, "drehmoment": 510, "cw": 0.30, "kofferraum": 406,
        "laenge": 4830, "tank": 60, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 10.5, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 49990, "baujahr_ende": 2023, "nordschleife": 0,
        "konzern": "Hyundai-Kia",
    },
    "Alpine A110 (Frankreich, 2017)": {
        "gewicht": 1103, "drehmoment": 320, "cw": 0.32, "kofferraum": 100,
        "laenge": 4178, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.8, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Sportwagen", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 58500, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Renault-Nissan",
    },
    "Honda Civic Type R FK8 (Japan, 2017)": {
        "gewicht": 1380, "drehmoment": 400, "cw": 0.33, "kofferraum": 420,
        "laenge": 4557, "tank": 46, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.9, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 36950, "baujahr_ende": 2022, "nordschleife": 473,
        "konzern": "Honda",
    },
    "McLaren 720S (UK, 2017)": {
        "gewicht": 1283, "drehmoment": 770, "cw": 0.32, "kofferraum": 150,
        "laenge": 4543, "tank": 72, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 12.8, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Sportwagen", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 242000, "baujahr_ende": 2021, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Suzuki Swift Sport (Japan, 2017)": {
        "gewicht": 970, "drehmoment": 230, "cw": 0.33, "kofferraum": 265,
        "laenge": 3890, "tank": 37, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.7, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Handschalter", "sitze": 4,
        "neupreis_eur": 20490, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Mercedes-Benz GLC 63 S AMG (Deutschland, 2017)": {
        "gewicht": 2010, "drehmoment": 700, "cw": 0.34, "kofferraum": 550,
        "laenge": 4656, "tank": 80, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.8, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 92000, "baujahr_ende": 2022, "nordschleife": 0,
        "konzern": "Mercedes",
    },
    "VW Polo 6 (Deutschland, 2017)": {
        "gewicht": 1090, "drehmoment": 175, "cw": 0.32, "kofferraum": 351,
        "laenge": 4053, "tank": 40, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.5, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 3, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 15990, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Opel Astra K GSi (Deutschland, 2017)": {
        "gewicht": 1445, "drehmoment": 280, "cw": 0.30, "kofferraum": 370,
        "laenge": 4370, "tank": 52, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.2, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 29900, "baujahr_ende": 2021, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "Opel Insignia B (Deutschland, 2017)": {
        "gewicht": 1530, "drehmoment": 300, "cw": 0.26, "kofferraum": 490,
        "laenge": 4899, "tank": 62, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.5, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 28990, "baujahr_ende": 2022, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "BMW 520i G30 (Deutschland, 2017)": {
        "gewicht": 1595, "drehmoment": 300, "cw": 0.22, "kofferraum": 530,
        "laenge": 4936, "tank": 68, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.2, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 43900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "Mercedes-Benz E 63 S AMG W213 (Deutschland, 2017)": {
        "gewicht": 1970, "drehmoment": 900, "cw": 0.28, "kofferraum": 540,
        "laenge": 4923, "tank": 80, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.3, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 107000, "baujahr_ende": 2023, "nordschleife": 0,
        "konzern": "Mercedes",
    },
    "Audi RS4 B9 (Deutschland, 2017)": {
        "gewicht": 1735, "drehmoment": 600, "cw": 0.35, "kofferraum": 505,
        "laenge": 4783, "tank": 73, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.9, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Kombi", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 79900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Porsche Cayenne V6 9YA (Deutschland, 2017)": {
        "gewicht": 1985, "drehmoment": 450, "cw": 0.36, "kofferraum": 770,
        "laenge": 4918, "tank": 75, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.6, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 72800, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Zenvo TSR-S (Dänemark, 2018)": {
        "gewicht": 1458, "drehmoment": 1100, "cw": 0.28, "kofferraum": 0,
        "laenge": 4390, "tank": 100, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 23.0, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Sportwagen", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 1700000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Rimac C_Two (Kroatien, 2018)": {
        "gewicht": 1950, "drehmoment": 2360, "cw": 0.28, "kofferraum": 100,
        "laenge": 4680, "tank": 0, "akku": 120.0, "reichweite_km": 550,
        "verbrauch_l": 0.0, "verbrauch_kwh": 21.8, "antrieb": "Allrad",
        "karosserie": "Sportwagen", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 2,
        "neupreis_eur": 2000000, "baujahr_ende": 2021, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "McLaren Senna (UK, 2018)": {
        "gewicht": 1198, "drehmoment": 800, "cw": 0.28, "kofferraum": 0,
        "laenge": 4745, "tank": 72, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 14.0, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Sportwagen", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 1000000, "baujahr_ende": 2019, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "VW Polo 6 GTI (Deutschland, 2018)": {
        "gewicht": 1262, "drehmoment": 320, "cw": 0.32, "kofferraum": 351,
        "laenge": 4053, "tank": 40, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.0, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 24975, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Opel Insignia B GSi (Deutschland, 2018)": {
        "gewicht": 1695, "drehmoment": 400, "cw": 0.26, "kofferraum": 490,
        "laenge": 4899, "tank": 62, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.5, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 43500, "baujahr_ende": 2022, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "BMW 318i G20 (Deutschland, 2018)": {
        "gewicht": 1460, "drehmoment": 250, "cw": 0.23, "kofferraum": 480,
        "laenge": 4709, "tank": 59, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.5, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 33950, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "BMW M5 F90 (Deutschland, 2018)": {
        "gewicht": 1855, "drehmoment": 750, "cw": 0.30, "kofferraum": 530,
        "laenge": 4963, "tank": 68, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.0, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 117000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "Audi RS6 C8 Avant (Deutschland, 2019)": {
        "gewicht": 2075, "drehmoment": 800, "cw": 0.30, "kofferraum": 565,
        "laenge": 5050, "tank": 73, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 11.5, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Kombi", "antriebsart": "MHEV", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 118000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Renault Mégane RS Trophy-R (Frankreich, 2019)": {
        "gewicht": 1306, "drehmoment": 400, "cw": 0.33, "kofferraum": 341,
        "laenge": 4359, "tank": 47, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.4, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 4,
        "neupreis_eur": 54000, "baujahr_ende": 2020, "nordschleife": 465,
        "konzern": "Renault-Nissan",
    },
    "VW Golf 8 (Deutschland, 2019)": {
        "gewicht": 1270, "drehmoment": 200, "cw": 0.28, "kofferraum": 381,
        "laenge": 4284, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.8, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 24990, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "VW Passat B8 2.0 TSI (Deutschland, 2019)": {
        "gewicht": 1455, "drehmoment": 350, "cw": 0.27, "kofferraum": 586,
        "laenge": 4767, "tank": 66, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.4, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 34490, "baujahr_ende": 2023, "nordschleife": 0,
        "konzern": "VW",
    },
    "Opel Corsa F (Deutschland, 2019)": {
        "gewicht": 1095, "drehmoment": 205, "cw": 0.31, "kofferraum": 309,
        "laenge": 4060, "tank": 44, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.8, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 3, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 16590, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "Renault Clio V (Frankreich, 2019)": {
        "gewicht": 1155, "drehmoment": 160, "cw": 0.29, "kofferraum": 391,
        "laenge": 4050, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.7, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 16490, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Renault-Nissan",
    },
    "BMW 116i F40 (Deutschland, 2019)": {
        "gewicht": 1310, "drehmoment": 170, "cw": 0.33, "kofferraum": 380,
        "laenge": 4319, "tank": 40, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.9, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 3, "turbo": True, "getriebe": "Handschalter", "sitze": 5,
        "neupreis_eur": 26250, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "BMW M135i xDrive F40 (Deutschland, 2019)": {
        "gewicht": 1560, "drehmoment": 450, "cw": 0.33, "kofferraum": 380,
        "laenge": 4319, "tank": 40, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.1, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 46300, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "Porsche Cayenne Turbo S E-Hybrid 9YA (Deutschland, 2019)": {
        "gewicht": 2715, "drehmoment": 900, "cw": 0.36, "kofferraum": 770,
        "laenge": 4918, "tank": 75, "akku": 14.1, "reichweite_km": 44,
        "verbrauch_l": 3.4, "verbrauch_kwh": 20.8, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "PHEV", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 177137, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Toyota GR Yaris (Japan, 2020)": {
        "gewicht": 1280, "drehmoment": 370, "cw": 0.33, "kofferraum": 174,
        "laenge": 3995, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.2, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 3, "turbo": True, "getriebe": "Handschalter", "sitze": 4,
        "neupreis_eur": 33250, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Toyota",
    },
    "Ford Mustang Shelby GT500 (USA, 2020)": {
        "gewicht": 1866, "drehmoment": 847, "cw": 0.35, "kofferraum": 0,
        "laenge": 4789, "tank": 61, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 16.5, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Coupé", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 4,
        "neupreis_eur": 80000, "baujahr_ende": 2023, "nordschleife": 0,
        "konzern": "Ford",
    },
    "Mercedes-AMG GT Black Series (Deutschland, 2020)": {
        "gewicht": 1625, "drehmoment": 800, "cw": 0.30, "kofferraum": 226,
        "laenge": 4550, "tank": 76, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 13.8, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Sportwagen", "antriebsart": "Benzin", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 335000, "baujahr_ende": 2023, "nordschleife": 415,
        "konzern": "Mercedes",
    },
    "Mercedes-Benz GLS 63 AMG (Deutschland, 2020)": {
        "gewicht": 2600, "drehmoment": 900, "cw": 0.35, "kofferraum": 680,
        "laenge": 5207, "tank": 105, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 14.0, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "MHEV", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 7,
        "neupreis_eur": 175000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Mercedes",
    },
    "Opel Corsa-e (Deutschland, 2020)": {
        "gewicht": 1530, "drehmoment": 260, "cw": 0.31, "kofferraum": 267,
        "laenge": 4060, "tank": 0, "akku": 50.0, "reichweite_km": 337,
        "verbrauch_l": 0.0, "verbrauch_kwh": 14.9, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 5,
        "neupreis_eur": 29900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "Audi A3 8Y (Deutschland, 2020)": {
        "gewicht": 1295, "drehmoment": 200, "cw": 0.27, "kofferraum": 380,
        "laenge": 4343, "tank": 40, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 5.9, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 29900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Renault Clio V RS Line (Frankreich, 2020)": {
        "gewicht": 1205, "drehmoment": 205, "cw": 0.29, "kofferraum": 391,
        "laenge": 4050, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.0, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 22990, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Renault-Nissan",
    },
    "Škoda Octavia IV (Tschechien, 2020)": {
        "gewicht": 1355, "drehmoment": 250, "cw": 0.24, "kofferraum": 600,
        "laenge": 4689, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.3, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 23590, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Škoda Octavia IV RS (Tschechien, 2020)": {
        "gewicht": 1480, "drehmoment": 370, "cw": 0.24, "kofferraum": 600,
        "laenge": 4689, "tank": 50, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 7.8, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 38690, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Mercedes-Benz S 500 W223 (Deutschland, 2020)": {
        "gewicht": 2185, "drehmoment": 700, "cw": 0.22, "kofferraum": 510,
        "laenge": 5179, "tank": 76, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.3, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Limousine", "antriebsart": "MHEV", "motorbauart": "V",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 109127, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Mercedes",
    },
    "Cupra Formentor VZ5 (Spanien, 2021)": {
        "gewicht": 1686, "drehmoment": 480, "cw": 0.33, "kofferraum": 420,
        "laenge": 4449, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.4, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 5, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 59900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Rimac Nevera (Kroatien, 2021)": {
        "gewicht": 2150, "drehmoment": 2360, "cw": 0.28, "kofferraum": 100,
        "laenge": 4680, "tank": 0, "akku": 120.0, "reichweite_km": 550,
        "verbrauch_l": 0.0, "verbrauch_kwh": 21.8, "antrieb": "Allrad",
        "karosserie": "Sportwagen", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 2,
        "neupreis_eur": 2000000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Tesla Model S Plaid (USA, 2021)": {
        "gewicht": 2162, "drehmoment": 1420, "cw": 0.208, "kofferraum": 793,
        "laenge": 4970, "tank": 0, "akku": 100.0, "reichweite_km": 600,
        "verbrauch_l": 0.0, "verbrauch_kwh": 17.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 5,
        "neupreis_eur": 135000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Golf 8 GTI Clubsport (VW, Deutschland, 2021)": {
        "gewicht": 1450, "drehmoment": 400, "cw": 0.28, "kofferraum": 381,
        "laenge": 4284, "tank": 45, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 8.2, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 43090, "baujahr_ende": 0, "nordschleife": 476,
        "konzern": "VW",
    },
    "Audi e-tron GT (Deutschland, 2021)": {
        "gewicht": 2340, "drehmoment": 630, "cw": 0.24, "kofferraum": 405,
        "laenge": 4989, "tank": 0, "akku": 93.4, "reichweite_km": 488,
        "verbrauch_l": 0.0, "verbrauch_kwh": 19.6, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 4,
        "neupreis_eur": 99800, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "BMW M4 Competition (Deutschland, 2021)": {
        "gewicht": 1725, "drehmoment": 650, "cw": 0.30, "kofferraum": 440,
        "laenge": 4794, "tank": 59, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 10.4, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Coupé", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 4,
        "neupreis_eur": 85900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "Cupra Born (Spanien, 2021)": {
        "gewicht": 1779, "drehmoment": 310, "cw": 0.28, "kofferraum": 385,
        "laenge": 4322, "tank": 0, "akku": 77.0, "reichweite_km": 540,
        "verbrauch_l": 0.0, "verbrauch_kwh": 15.8, "antrieb": "Heck",
        "karosserie": "Hatchback", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 5,
        "neupreis_eur": 37990, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Opel Astra L (Deutschland, 2021)": {
        "gewicht": 1370, "drehmoment": 230, "cw": 0.28, "kofferraum": 422,
        "laenge": 4374, "tank": 41, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 6.2, "verbrauch_kwh": 0.0, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 3, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 24890, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Stellantis",
    },
    "BMW M3 G80 (Deutschland, 2021)": {
        "gewicht": 1730, "drehmoment": 650, "cw": 0.30, "kofferraum": 480,
        "laenge": 4794, "tank": 59, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 10.4, "verbrauch_kwh": 0.0, "antrieb": "Heck",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 82900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "BMW",
    },
    "Audi RS3 8Y (Deutschland, 2021)": {
        "gewicht": 1570, "drehmoment": 500, "cw": 0.33, "kofferraum": 325,
        "laenge": 4507, "tank": 55, "akku": 0.0, "reichweite_km": 0,
        "verbrauch_l": 9.5, "verbrauch_kwh": 0.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "Benzin", "motorbauart": "Reihe",
        "zylinder": 5, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 56900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "VW",
    },
    "Mercedes-Benz S 63 AMG W223 (Deutschland, 2021)": {
        "gewicht": 2640, "drehmoment": 900, "cw": 0.22, "kofferraum": 510,
        "laenge": 5179, "tank": 76, "akku": 13.5, "reichweite_km": 33,
        "verbrauch_l": 3.0, "verbrauch_kwh": 18.0, "antrieb": "Allrad",
        "karosserie": "Limousine", "antriebsart": "PHEV", "motorbauart": "V",
        "zylinder": 8, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 219009, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Mercedes",
    },
    "Togg T10X (Türkei, 2023)": {
        "gewicht": 2100, "drehmoment": 530, "cw": 0.30, "kofferraum": 498,
        "laenge": 4559, "tank": 0, "akku": 88.5, "reichweite_km": 523,
        "verbrauch_l": 0.0, "verbrauch_kwh": 17.5, "antrieb": "Heck",
        "karosserie": "SUV", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 5,
        "neupreis_eur": 40000, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "unabhängig",
    },
    "Mercedes-AMG ONE (Deutschland, 2023)": {
        "gewicht": 1773, "drehmoment": 1000, "cw": 0.28, "kofferraum": 0,
        "laenge": 4732, "tank": 64, "akku": 6.7, "reichweite_km": 18,
        "verbrauch_l": 8.0, "verbrauch_kwh": 12.0, "antrieb": "Allrad",
        "karosserie": "Sportwagen", "antriebsart": "PHEV", "motorbauart": "V",
        "zylinder": 6, "turbo": True, "getriebe": "Automatik", "sitze": 2,
        "neupreis_eur": 2750000, "baujahr_ende": 2023, "nordschleife": 415,
        "konzern": "Mercedes",
    },
    "Hyundai Ioniq 5 N (Südkorea, 2023)": {
        "gewicht": 2235, "drehmoment": 740, "cw": 0.29, "kofferraum": 527,
        "laenge": 4635, "tank": 0, "akku": 84.0, "reichweite_km": 448,
        "verbrauch_l": 0.0, "verbrauch_kwh": 18.8, "antrieb": "Allrad",
        "karosserie": "SUV", "antriebsart": "EV", "motorbauart": "E-Motor",
        "zylinder": 0, "turbo": False, "getriebe": "E-Getriebe", "sitze": 5,
        "neupreis_eur": 69900, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Hyundai-Kia",
    },
    "Opel Astra L GSe (Deutschland, 2023)": {
        "gewicht": 1640, "drehmoment": 360, "cw": 0.28, "kofferraum": 352,
        "laenge": 4374, "tank": 41, "akku": 12.4, "reichweite_km": 62,
        "verbrauch_l": 1.4, "verbrauch_kwh": 14.5, "antrieb": "Front",
        "karosserie": "Hatchback", "antriebsart": "PHEV", "motorbauart": "Reihe",
        "zylinder": 4, "turbo": True, "getriebe": "Automatik", "sitze": 5,
        "neupreis_eur": 44700, "baujahr_ende": 0, "nordschleife": 0,
        "konzern": "Stellantis",
    },
}
