# -*- coding: utf-8 -*-
# C:\Users\Andre\Desktop\Cowork\Geoquest\patches\games_batch3.py
# Batch 3: Indie-Klassiker & moderne Meisterwerke (Phase 405)
# 20 Spiele — Kategorien: "Indie" (neue Kategorie) und "Klassiker"

DATA = {
    "Stardew Valley": {
        "release": 2016, "kategorie": "Indie",
        "publisher": "ConcernedApe", "publisher_land": "Vereinigte Staaten",
        "developer": "ConcernedApe", "dev_land": "Vereinigte Staaten",
        "dev_city": "Seattle", "dev_lat": 47.6062, "dev_lng": -122.3321,
        "genre": "Rollenspiel", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 20.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.074, "peak_year": 2016, "metacritic": 89,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 47.6062, "publisher_lng": -122.3321
    },
    "Hollow Knight": {
        "release": 2017, "kategorie": "Indie",
        "publisher": "Team Cherry", "publisher_land": "Australien",
        "developer": "Team Cherry", "dev_land": "Australien",
        "dev_city": "Adelaide", "dev_lat": -34.9285, "dev_lng": 138.6007,
        "genre": "Action-Adventure", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 3.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.014, "peak_year": 2017, "metacritic": 87,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": -34.9285, "publisher_lng": 138.6007
    },
    "Celeste": {
        "release": 2018, "kategorie": "Indie",
        "publisher": "Matt Makes Games", "publisher_land": "Kanada",
        "developer": "Matt Makes Games", "dev_land": "Kanada",
        "dev_city": "Victoria", "dev_lat": 48.4284, "dev_lng": -123.3656,
        "genre": "Jump 'n' Run", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 1.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.008, "peak_year": 2018, "metacritic": 94,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 48.4284, "publisher_lng": -123.3656
    },
    "Terraria": {
        "release": 2011, "kategorie": "Indie",
        "publisher": "Re-Logic", "publisher_land": "Vereinigte Staaten",
        "developer": "Re-Logic", "dev_land": "Vereinigte Staaten",
        "dev_city": "Indianapolis", "dev_lat": 39.7684, "dev_lng": -86.1581,
        "genre": "Action-Adventure", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 44.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.49, "peak_year": 2020, "metacritic": 83,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 39.7684, "publisher_lng": -86.1581
    },
    "Undertale": {
        "release": 2015, "kategorie": "Indie",
        "publisher": "Toby Fox", "publisher_land": "Vereinigte Staaten",
        "developer": "Toby Fox", "dev_land": "Vereinigte Staaten",
        "dev_city": "Boston", "dev_lat": 42.3601, "dev_lng": -71.0589,
        "genre": "Rollenspiel", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 3.5, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.023, "peak_year": 2015, "metacritic": 92,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 1,
        "publisher_lat": 42.3601, "publisher_lng": -71.0589
    },
    "Hades": {
        "release": 2020, "kategorie": "Indie",
        "publisher": "Supergiant Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Supergiant Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "San Francisco", "dev_lat": 37.7749, "dev_lng": -122.4194,
        "genre": "Action-Adventure", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 3.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.049, "peak_year": 2020, "metacritic": 93,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 1,
        "publisher_lat": 37.7749, "publisher_lng": -122.4194
    },
    "Among Trees": {
        "release": 2021, "kategorie": "Indie",
        "publisher": "FJRD Interactive", "publisher_land": "Frankreich",
        "developer": "FJRD Interactive", "dev_land": "Frankreich",
        "dev_city": "Paris", "dev_lat": 48.8566, "dev_lng": 2.3522,
        "genre": "Sandbox", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 0.3, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "peak_year": 2021, "metacritic": None,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 48.8566, "publisher_lng": 2.3522
    },
    "Cuphead": {
        "release": 2017, "kategorie": "Indie",
        "publisher": "Studio MDHR", "publisher_land": "Kanada",
        "developer": "Studio MDHR", "dev_land": "Kanada",
        "dev_city": "Regina", "dev_lat": 50.4452, "dev_lng": -104.6189,
        "genre": "Action-Adventure", "usk": 0, "pegi": 7,
        "f2p": False, "vk_mio": 6.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.035, "peak_year": 2017, "metacritic": 88,
        "plattform": "Multiplattform", "vorbild_land": "Vereinigte Staaten",
        "adaption": "Serie", "esports": False, "sequel_count": 1,
        "publisher_lat": 50.4452, "publisher_lng": -104.6189
    },
    "Disco Elysium": {
        "release": 2019, "kategorie": "Indie",
        "publisher": "ZA/UM", "publisher_land": "Vereinigtes Königreich",
        "developer": "ZA/UM", "dev_land": "Estland",
        "dev_city": "Tallinn", "dev_lat": 59.4370, "dev_lng": 24.7536,
        "genre": "Rollenspiel", "usk": 16, "pegi": 18,
        "f2p": False, "vk_mio": 1.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.013, "peak_year": 2019, "metacritic": 97,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 51.5074, "publisher_lng": -0.1278
    },
    "Factorio": {
        "release": 2020, "kategorie": "Indie",
        "publisher": "Wube Software", "publisher_land": "Tschechien",
        "developer": "Wube Software", "dev_land": "Tschechien",
        "dev_city": "Prag", "dev_lat": 50.0755, "dev_lng": 14.4378,
        "genre": "Strategie", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 3.5, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.071, "peak_year": 2020, "metacritic": 90,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 50.0755, "publisher_lng": 14.4378
    },
    "Portal 2": {
        "release": 2011, "kategorie": "Klassiker",
        "publisher": "Valve", "publisher_land": "Vereinigte Staaten",
        "developer": "Valve", "dev_land": "Vereinigte Staaten",
        "dev_city": "Kirkland", "dev_lat": 47.6769, "dev_lng": -122.2060,
        "genre": "Puzzle", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 4.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.064, "peak_year": 2011, "metacritic": 95,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 47.6769, "publisher_lng": -122.2060
    },
    "Red Dead Redemption 2": {
        "release": 2018, "kategorie": "Klassiker",
        "publisher": "Rockstar Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Rockstar Studios", "dev_land": "Vereinigte Staaten",
        "dev_city": "New York", "dev_lat": 40.7128, "dev_lng": -74.0060,
        "genre": "Action-Adventure", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 61.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.089, "peak_year": 2018, "metacritic": 97,
        "plattform": "Multiplattform", "vorbild_land": "Vereinigte Staaten",
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 40.7128, "publisher_lng": -74.0060
    },
    "Dark Souls": {
        "release": 2011, "kategorie": "Klassiker",
        "publisher": "Bandai Namco", "publisher_land": "Japan",
        "developer": "FromSoftware", "dev_land": "Japan",
        "dev_city": "Tokyo", "dev_lat": 35.6895, "dev_lng": 139.6917,
        "genre": "Rollenspiel", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.022, "peak_year": 2012, "metacritic": 89,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 2,
        "publisher_lat": 35.6895, "publisher_lng": 139.6917
    },
    "Cyberpunk 2077": {
        "release": 2020, "kategorie": "Klassiker",
        "publisher": "CD Projekt", "publisher_land": "Polen",
        "developer": "CD Projekt Red", "dev_land": "Polen",
        "dev_city": "Warschau", "dev_lat": 52.2297, "dev_lng": 21.0122,
        "genre": "Rollenspiel", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 25.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 1.054, "peak_year": 2023, "metacritic": 86,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Serie", "esports": False, "sequel_count": 0,
        "publisher_lat": 52.2297, "publisher_lng": 21.0122
    },
    "Elden Ring": {
        "release": 2022, "kategorie": "Klassiker",
        "publisher": "Bandai Namco", "publisher_land": "Japan",
        "developer": "FromSoftware", "dev_land": "Japan",
        "dev_city": "Tokyo", "dev_lat": 35.6895, "dev_lng": 139.6917,
        "genre": "Rollenspiel", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 25.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.952, "peak_year": 2022, "metacritic": 96,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 35.6895, "publisher_lng": 139.6917
    },
    "Baldur's Gate 3": {
        "release": 2023, "kategorie": "Klassiker",
        "publisher": "Larian Studios", "publisher_land": "Belgien",
        "developer": "Larian Studios", "dev_land": "Belgien",
        "dev_city": "Gent", "dev_lat": 51.0543, "dev_lng": 3.7174,
        "genre": "Rollenspiel", "usk": 16, "pegi": 18,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.875, "peak_year": 2023, "metacritic": 96,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 51.0543, "publisher_lng": 3.7174
    },
    "God of War (2018)": {
        "release": 2018, "kategorie": "Klassiker",
        "publisher": "Sony Interactive Entertainment", "publisher_land": "Japan",
        "developer": "Santa Monica Studio", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0195, "dev_lng": -118.4912,
        "genre": "Action-Adventure", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 23.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "peak_year": 2018, "metacritic": 94,
        "plattform": "Konsole", "vorbild_land": "Griechenland",
        "adaption": None, "esports": False, "sequel_count": 1,
        "publisher_lat": 35.5652, "publisher_lng": 139.7182
    },
    "Ori and the Blind Forest": {
        "release": 2015, "kategorie": "Indie",
        "publisher": "Microsoft", "publisher_land": "Vereinigte Staaten",
        "developer": "Moon Studios", "dev_land": "Österreich",
        "dev_city": "Wien", "dev_lat": 48.2082, "dev_lng": 16.3738,
        "genre": "Jump 'n' Run", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 4.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.025, "peak_year": 2015, "metacritic": 88,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 1,
        "publisher_lat": 47.6062, "publisher_lng": -122.3321
    },
    "Minecraft Dungeons": {
        "release": 2020, "kategorie": "Modern Youth",
        "publisher": "Mojang Studios", "publisher_land": "Schweden",
        "developer": "Mojang Studios", "dev_land": "Schweden",
        "dev_city": "Stockholm", "dev_lat": 59.3293, "dev_lng": 18.0686,
        "genre": "Action-Adventure", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 15.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "peak_year": 2020, "metacritic": 71,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0,
        "publisher_lat": 47.6062, "publisher_lng": -122.3321
    },
    "Dota 2": {
        "release": 2013, "kategorie": "Klassiker",
        "publisher": "Valve", "publisher_land": "Vereinigte Staaten",
        "developer": "Valve", "dev_land": "Vereinigte Staaten",
        "dev_city": "Kirkland", "dev_lat": 47.6769, "dev_lng": -122.2060,
        "genre": "MOBA", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 180.0,
        "peak_concurrent_mio": 1.3, "peak_year": 2016, "metacritic": 90,
        "plattform": "PC", "vorbild_land": None,
        "adaption": "Serie", "esports": True, "sequel_count": 0,
        "publisher_lat": 47.6769, "publisher_lng": -122.2060
    },
}
