DATA = {
    "GTA V": {
        "release": 2013, "kategorie": "Klassiker",
        "publisher": "Rockstar Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Rockstar North", "dev_land": "Vereinigtes Königreich",
        "dev_city": "Edinburgh", "dev_lat": 55.9533, "dev_lng": -3.1883,
        "genre": "Action-Adventure", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 200.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 1.5, "metacritic": 97,
        "plattform": "Multiplattform", "vorbild_land": "Vereinigte Staaten",
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "The Witcher 3: Wild Hunt": {
        "release": 2015, "kategorie": "Klassiker",
        "publisher": "CD Projekt", "publisher_land": "Polen",
        "developer": "CD Projekt Red", "dev_land": "Polen",
        "dev_city": "Warschau", "dev_lat": 52.2297, "dev_lng": 21.0122,
        "genre": "Rollenspiel", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 50.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.1, "metacritic": 92,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Serie", "esports": False, "sequel_count": 0
    },
    "Pokémon Rot/Blau": {
        "release": 1996, "kategorie": "Klassiker",
        "publisher": "Nintendo", "publisher_land": "Japan",
        "developer": "Game Freak", "dev_land": "Japan",
        "dev_city": "Tokyo", "dev_lat": 35.6895, "dev_lng": 139.6917,
        "genre": "Rollenspiel", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 31.4, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Konsole", "vorbild_land": None,
        "adaption": "Anime", "esports": False, "sequel_count": 8
    },
    "Super Mario 64": {
        "release": 1996, "kategorie": "Klassiker",
        "publisher": "Nintendo", "publisher_land": "Japan",
        "developer": "Nintendo", "dev_land": "Japan",
        "dev_city": "Kyoto", "dev_lat": 35.0116, "dev_lng": 135.7681,
        "genre": "Jump 'n' Run", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 11.9, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Konsole", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 3
    },
    "Tetris": {
        "release": 1984, "kategorie": "Klassiker",
        "publisher": "Spectrum HoloByte", "publisher_land": "Vereinigte Staaten",
        "developer": "Alexey Pajitnov", "dev_land": "Russland",
        "dev_city": "Moskau", "dev_lat": 55.7558, "dev_lng": 37.6173,
        "genre": "Puzzle", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 520.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 2
    },
    "Pac-Man": {
        "release": 1980, "kategorie": "Klassiker",
        "publisher": "Namco", "publisher_land": "Japan",
        "developer": "Namco", "dev_land": "Japan",
        "dev_city": "Tokyo", "dev_lat": 35.6895, "dev_lng": 139.6917,
        "genre": "Action-Adventure", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 7.7, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 4
    },
    "The Last of Us": {
        "release": 2013, "kategorie": "Klassiker",
        "publisher": "Sony Computer Entertainment", "publisher_land": "Japan",
        "developer": "Naughty Dog", "dev_land": "Vereinigte Staaten",
        "dev_city": "Santa Monica", "dev_lat": 34.0195, "dev_lng": -118.4912,
        "genre": "Action-Adventure", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 37.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 95,
        "plattform": "Konsole", "vorbild_land": "Vereinigte Staaten",
        "adaption": "Serie", "esports": False, "sequel_count": 1
    },
    "Tomb Raider": {
        "release": 1996, "kategorie": "Klassiker",
        "publisher": "Eidos Interactive", "publisher_land": "Vereinigtes Königreich",
        "developer": "Core Design", "dev_land": "Vereinigtes Königreich",
        "dev_city": "Derby", "dev_lat": 52.9225, "dev_lng": -1.4746,
        "genre": "Action-Adventure", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 7.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 6
    },
    "World of Warcraft": {
        "release": 2004, "kategorie": "Klassiker",
        "publisher": "Blizzard Entertainment", "publisher_land": "Vereinigte Staaten",
        "developer": "Blizzard Entertainment", "dev_land": "Vereinigte Staaten",
        "dev_city": "Irvine", "dev_lat": 33.6846, "dev_lng": -117.8265,
        "genre": "MMO", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 0.0, "downloads_mio": 15.0,
        "peak_concurrent_mio": 0.8, "metacritic": 93,
        "plattform": "PC", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 9
    },
    "Sonic the Hedgehog": {
        "release": 1991, "kategorie": "Klassiker",
        "publisher": "Sega", "publisher_land": "Japan",
        "developer": "Sonic Team", "dev_land": "Japan",
        "dev_city": "Tokyo", "dev_lat": 35.6895, "dev_lng": 139.6917,
        "genre": "Jump 'n' Run", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 15.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Konsole", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 5
    },
    "Half-Life": {
        "release": 1998, "kategorie": "Klassiker",
        "publisher": "Sierra Studios", "publisher_land": "Vereinigte Staaten",
        "developer": "Valve", "dev_land": "Vereinigte Staaten",
        "dev_city": "Kirkland", "dev_lat": 47.6769, "dev_lng": -122.2060,
        "genre": "Ego-Shooter", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 12.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 96,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 2
    },
    "Counter-Strike": {
        "release": 2000, "kategorie": "Klassiker",
        "publisher": "Sierra Studios", "publisher_land": "Vereinigte Staaten",
        "developer": "Valve", "dev_land": "Vereinigte Staaten",
        "dev_city": "Kirkland", "dev_lat": 47.6769, "dev_lng": -122.2060,
        "genre": "Ego-Shooter", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 0.0, "downloads_mio": 25.0,
        "peak_concurrent_mio": 1.3, "metacritic": 88,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 2
    },
    "Doom": {
        "release": 1993, "kategorie": "Klassiker",
        "publisher": "id Software", "publisher_land": "Vereinigte Staaten",
        "developer": "id Software", "dev_land": "Vereinigte Staaten",
        "dev_city": "Mesquite", "dev_lat": 32.7668, "dev_lng": -96.5992,
        "genre": "Ego-Shooter", "usk": 18, "pegi": 18,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 4
    },
    "The Legend of Zelda: Ocarina of Time": {
        "release": 1998, "kategorie": "Klassiker",
        "publisher": "Nintendo", "publisher_land": "Japan",
        "developer": "Nintendo", "dev_land": "Japan",
        "dev_city": "Kyoto", "dev_lat": 35.0116, "dev_lng": 135.7681,
        "genre": "Action-Adventure", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 7.6, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 99,
        "plattform": "Konsole", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 5
    },
    "Grand Theft Auto": {
        "release": 1997, "kategorie": "Klassiker",
        "publisher": "BMG Interactive", "publisher_land": "Vereinigtes Königreich",
        "developer": "DMA Design", "dev_land": "Vereinigtes Königreich",
        "dev_city": "Dundee", "dev_lat": 56.4620, "dev_lng": -2.9707,
        "genre": "Action-Adventure", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 1.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": "Vereinigte Staaten",
        "adaption": None, "esports": False, "sequel_count": 5
    },
    "Diablo II": {
        "release": 2000, "kategorie": "Klassiker",
        "publisher": "Blizzard Entertainment", "publisher_land": "Vereinigte Staaten",
        "developer": "Blizzard North", "dev_land": "Vereinigte Staaten",
        "dev_city": "San Mateo", "dev_lat": 37.5630, "dev_lng": -122.3255,
        "genre": "Rollenspiel", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 4.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 88,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 2
    },
    "StarCraft": {
        "release": 1998, "kategorie": "Klassiker",
        "publisher": "Blizzard Entertainment", "publisher_land": "Vereinigte Staaten",
        "developer": "Blizzard Entertainment", "dev_land": "Vereinigte Staaten",
        "dev_city": "Irvine", "dev_lat": 33.6846, "dev_lng": -117.8265,
        "genre": "Strategie", "usk": 12, "pegi": 12,
        "f2p": False, "vk_mio": 11.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 88,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 1
    },
    "Assassin's Creed": {
        "release": 2007, "kategorie": "Klassiker",
        "publisher": "Ubisoft", "publisher_land": "Frankreich",
        "developer": "Ubisoft Montreal", "dev_land": "Kanada",
        "dev_city": "Montreal", "dev_lat": 45.5017, "dev_lng": -73.5673,
        "genre": "Action-Adventure", "usk": 16, "pegi": 16,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 81,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 11
    },
    "The Elder Scrolls V: Skyrim": {
        "release": 2011, "kategorie": "Klassiker",
        "publisher": "Bethesda Softworks", "publisher_land": "Vereinigte Staaten",
        "developer": "Bethesda Game Studios", "dev_land": "Vereinigte Staaten",
        "dev_city": "Rockville", "dev_lat": 39.0840, "dev_lng": -77.1528,
        "genre": "Rollenspiel", "usk": 16, "pegi": 18,
        "f2p": False, "vk_mio": 60.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 0.28, "metacritic": 96,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Ghost of Tsushima": {
        "release": 2020, "kategorie": "Klassiker",
        "publisher": "Sony Interactive Entertainment", "publisher_land": "Japan",
        "developer": "Sucker Punch Productions", "dev_land": "Vereinigte Staaten",
        "dev_city": "Bellevue", "dev_lat": 47.6101, "dev_lng": -122.2015,
        "genre": "Action-Adventure", "usk": 16, "pegi": 18,
        "f2p": False, "vk_mio": 13.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 83,
        "plattform": "Konsole", "vorbild_land": "Japan",
        "adaption": "Film", "esports": False, "sequel_count": 0
    },
}
