DATA = {
    "Roblox": {
        "release": 2006, "kategorie": "Modern Youth",
        "publisher": "Roblox Corporation", "publisher_land": "Vereinigte Staaten",
        "developer": "Roblox Corporation", "dev_land": "Vereinigte Staaten",
        "dev_city": "San Mateo", "dev_lat": 37.5630, "dev_lng": -122.3255,
        "genre": "Sandbox", "usk": 6, "pegi": 7,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 600.0,
        "peak_concurrent_mio": 5.6, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Fortnite": {
        "release": 2017, "kategorie": "Modern Youth",
        "publisher": "Epic Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Epic Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "Cary", "dev_lat": 35.7915, "dev_lng": -78.7811,
        "genre": "Battle Royale", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 500.0,
        "peak_concurrent_mio": 11.6, "metacritic": 81,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Among Us": {
        "release": 2018, "kategorie": "Modern Youth",
        "publisher": "Innersloth", "publisher_land": "Vereinigte Staaten",
        "developer": "Innersloth", "dev_land": "Vereinigte Staaten",
        "dev_city": "Redmond", "dev_lat": 47.6740, "dev_lng": -122.1215,
        "genre": "Social Deduction", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 15.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": 3.9, "metacritic": 85,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Fall Guys": {
        "release": 2020, "kategorie": "Modern Youth",
        "publisher": "Mediatonic", "publisher_land": "Vereinigte Staaten",
        "developer": "Mediatonic", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0522, "dev_lng": -118.2437,
        "genre": "Party-Spiel", "usk": 6, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 50.0,
        "peak_concurrent_mio": 1.5, "metacritic": 80,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Brawl Stars": {
        "release": 2018, "kategorie": "Global Mobile",
        "publisher": "Supercell", "publisher_land": "Finnland",
        "developer": "Supercell", "dev_land": "Finnland",
        "dev_city": "Helsinki", "dev_lat": 60.1699, "dev_lng": 24.9384,
        "genre": "Action-Adventure", "usk": 12, "pegi": 7,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 500.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Clash of Clans": {
        "release": 2012, "kategorie": "Global Mobile",
        "publisher": "Supercell", "publisher_land": "Finnland",
        "developer": "Supercell", "dev_land": "Finnland",
        "dev_city": "Helsinki", "dev_lat": 60.1699, "dev_lng": 24.9384,
        "genre": "Strategie", "usk": 6, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 600.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Clash Royale": {
        "release": 2016, "kategorie": "Global Mobile",
        "publisher": "Supercell", "publisher_land": "Finnland",
        "developer": "Supercell", "dev_land": "Finnland",
        "dev_city": "Helsinki", "dev_lat": 60.1699, "dev_lng": 24.9384,
        "genre": "Strategie", "usk": 6, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 500.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "PUBG Mobile": {
        "release": 2018, "kategorie": "Global Mobile",
        "publisher": "Krafton", "publisher_land": "Südkorea",
        "developer": "Tencent Games", "dev_land": "China",
        "dev_city": "Shenzhen", "dev_lat": 22.5431, "dev_lng": 114.0579,
        "genre": "Battle Royale", "usk": 16, "pegi": 16,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 1000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Garena Free Fire": {
        "release": 2017, "kategorie": "Global Mobile",
        "publisher": "Garena", "publisher_land": "Singapur",
        "developer": "111dots Studio", "dev_land": "Singapur",
        "dev_city": "Singapur", "dev_lat": 1.3521, "dev_lng": 103.8198,
        "genre": "Battle Royale", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 1000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Genshin Impact": {
        "release": 2020, "kategorie": "Global Mobile",
        "publisher": "miHoYo", "publisher_land": "China",
        "developer": "miHoYo", "dev_land": "China",
        "dev_city": "Shanghai", "dev_lat": 31.2304, "dev_lng": 121.4737,
        "genre": "Rollenspiel", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 100.0,
        "peak_concurrent_mio": None, "metacritic": 84,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Anime", "esports": False, "sequel_count": 0
    },
    "Honkai: Star Rail": {
        "release": 2023, "kategorie": "Global Mobile",
        "publisher": "HoYoverse", "publisher_land": "China",
        "developer": "HoYoverse", "dev_land": "China",
        "dev_city": "Shanghai", "dev_lat": 31.2304, "dev_lng": 121.4737,
        "genre": "Rollenspiel", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 100.0,
        "peak_concurrent_mio": None, "metacritic": 87,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Mobile Legends: Bang Bang": {
        "release": 2016, "kategorie": "Global Mobile",
        "publisher": "Moonton", "publisher_land": "China",
        "developer": "Moonton", "dev_land": "China",
        "dev_city": "Shanghai", "dev_lat": 31.2304, "dev_lng": 121.4737,
        "genre": "MOBA", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 1000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Honor of Kings": {
        "release": 2015, "kategorie": "Global Mobile",
        "publisher": "TiMi Studio Group", "publisher_land": "China",
        "developer": "TiMi Studio Group", "dev_land": "China",
        "dev_city": "Shenzhen", "dev_lat": 22.5431, "dev_lng": 114.0579,
        "genre": "MOBA", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 200.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Subway Surfers": {
        "release": 2012, "kategorie": "Global Mobile",
        "publisher": "Kiloo", "publisher_land": "Finnland",
        "developer": "Sybo Games", "dev_land": "Finnland",
        "dev_city": "Kopenhagen", "dev_lat": 55.6761, "dev_lng": 12.5683,
        "genre": "Endless Runner", "usk": 6, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 3000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Stumble Guys": {
        "release": 2021, "kategorie": "Global Mobile",
        "publisher": "Scopely", "publisher_land": "Vereinigte Staaten",
        "developer": "Kitka Games", "dev_land": "Finnland",
        "dev_city": "Helsinki", "dev_lat": 60.1699, "dev_lng": 24.9384,
        "genre": "Party-Spiel", "usk": 6, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 300.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Valorant": {
        "release": 2020, "kategorie": "Modern Youth",
        "publisher": "Riot Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Riot Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0195, "dev_lng": -118.4912,
        "genre": "Ego-Shooter", "usk": 16, "pegi": 16,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 14.0,
        "peak_concurrent_mio": 1.0, "metacritic": 80,
        "plattform": "PC", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Apex Legends": {
        "release": 2019, "kategorie": "Modern Youth",
        "publisher": "Electronic Arts", "publisher_land": "Vereinigte Staaten",
        "developer": "Respawn Entertainment", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0522, "dev_lng": -118.2437,
        "genre": "Battle Royale", "usk": 16, "pegi": 16,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 100.0,
        "peak_concurrent_mio": 0.6, "metacritic": 89,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Rocket League": {
        "release": 2015, "kategorie": "Modern Youth",
        "publisher": "Psyonix", "publisher_land": "Vereinigte Staaten",
        "developer": "Psyonix", "dev_land": "Vereinigte Staaten",
        "dev_city": "San Diego", "dev_lat": 32.7157, "dev_lng": -117.1611,
        "genre": "Sportsimulation", "usk": 0, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 75.0,
        "peak_concurrent_mio": 0.15, "metacritic": 86,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "EA FC 24": {
        "release": 2023, "kategorie": "Modern Youth",
        "publisher": "Electronic Arts", "publisher_land": "Vereinigte Staaten",
        "developer": "EA Vancouver", "dev_land": "Kanada",
        "dev_city": "Burnaby", "dev_lat": 49.2488, "dev_lng": -122.9805,
        "genre": "Sportsimulation", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 75,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Pokémon GO": {
        "release": 2016, "kategorie": "Global Mobile",
        "publisher": "Niantic", "publisher_land": "Vereinigte Staaten",
        "developer": "Niantic", "dev_land": "Vereinigte Staaten",
        "dev_city": "San Francisco", "dev_lat": 37.7749, "dev_lng": -122.4194,
        "genre": "Rollenspiel", "usk": 0, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 1000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": "Anime", "esports": False, "sequel_count": 0
    },
    "League of Legends": {
        "release": 2009, "kategorie": "Modern Youth",
        "publisher": "Riot Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Riot Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0195, "dev_lng": -118.4912,
        "genre": "MOBA", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 180.0,
        "peak_concurrent_mio": 8.0, "metacritic": 91,
        "plattform": "PC", "vorbild_land": None,
        "adaption": "Serie", "esports": True, "sequel_count": 0
    },
    "Overwatch 2": {
        "release": 2022, "kategorie": "Modern Youth",
        "publisher": "Blizzard Entertainment", "publisher_land": "Vereinigte Staaten",
        "developer": "Blizzard Entertainment", "dev_land": "Vereinigte Staaten",
        "dev_city": "Irvine", "dev_lat": 33.6846, "dev_lng": -117.8265,
        "genre": "Ego-Shooter", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 35.0,
        "peak_concurrent_mio": 0.5, "metacritic": 72,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Candy Crush Saga": {
        "release": 2012, "kategorie": "Global Mobile",
        "publisher": "King", "publisher_land": "Schweden",
        "developer": "King", "dev_land": "Schweden",
        "dev_city": "Stockholm", "dev_lat": 59.3293, "dev_lng": 18.0686,
        "genre": "Puzzle", "usk": 0, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 3000.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": False, "sequel_count": 0
    },
    "Angry Birds 2": {
        "release": 2015, "kategorie": "Global Mobile",
        "publisher": "Rovio Entertainment", "publisher_land": "Finnland",
        "developer": "Rovio Entertainment", "dev_land": "Finnland",
        "dev_city": "Espoo", "dev_lat": 60.2052, "dev_lng": 24.6522,
        "genre": "Puzzle", "usk": 0, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 300.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 0
    },
    "Call of Duty: Mobile": {
        "release": 2019, "kategorie": "Global Mobile",
        "publisher": "Activision", "publisher_land": "Vereinigte Staaten",
        "developer": "TiMi Studio Group", "dev_land": "China",
        "dev_city": "Shenzhen", "dev_lat": 22.5431, "dev_lng": 114.0579,
        "genre": "Ego-Shooter", "usk": 16, "pegi": 16,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 650.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Mario Kart Tour": {
        "release": 2019, "kategorie": "Global Mobile",
        "publisher": "Nintendo", "publisher_land": "Japan",
        "developer": "Nintendo", "dev_land": "Japan",
        "dev_city": "Kyoto", "dev_lat": 35.0116, "dev_lng": 135.7681,
        "genre": "Rennspiel", "usk": 0, "pegi": 3,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 200.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Mobil", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 0
    },
    "Teamfight Tactics": {
        "release": 2019, "kategorie": "Modern Youth",
        "publisher": "Riot Games", "publisher_land": "Vereinigte Staaten",
        "developer": "Riot Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "Los Angeles", "dev_lat": 34.0195, "dev_lng": -118.4912,
        "genre": "Strategie", "usk": 12, "pegi": 12,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 35.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "Brawlhalla": {
        "release": 2017, "kategorie": "Modern Youth",
        "publisher": "Ubisoft", "publisher_land": "Frankreich",
        "developer": "Blue Mammoth Games", "dev_land": "Vereinigte Staaten",
        "dev_city": "Atlanta", "dev_lat": 33.7490, "dev_lng": -84.3880,
        "genre": "Kampfspiel", "usk": 6, "pegi": 7,
        "f2p": True, "vk_mio": 0.0, "downloads_mio": 80.0,
        "peak_concurrent_mio": None, "metacritic": None,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 0
    },
    "FIFA 23": {
        "release": 2022, "kategorie": "Modern Youth",
        "publisher": "Electronic Arts", "publisher_land": "Vereinigte Staaten",
        "developer": "EA Vancouver", "dev_land": "Kanada",
        "dev_city": "Burnaby", "dev_lat": 49.2488, "dev_lng": -122.9805,
        "genre": "Sportsimulation", "usk": 0, "pegi": 3,
        "f2p": False, "vk_mio": 10.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 79,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": None, "esports": True, "sequel_count": 1
    },
    "Minecraft": {
        "release": 2009, "kategorie": "Modern Youth",
        "publisher": "Mojang Studios", "publisher_land": "Schweden",
        "developer": "Mojang Studios", "dev_land": "Schweden",
        "dev_city": "Stockholm", "dev_lat": 59.3293, "dev_lng": 18.0686,
        "genre": "Sandbox", "usk": 6, "pegi": 7,
        "f2p": False, "vk_mio": 238.0, "downloads_mio": 0.0,
        "peak_concurrent_mio": None, "metacritic": 93,
        "plattform": "Multiplattform", "vorbild_land": None,
        "adaption": "Film", "esports": False, "sequel_count": 0
    },
}
