SRC = "/sessions/trusting-upbeat-lovelace/mnt/Desktop/Cowork/Geoquest/gen.py"
with open(SRC, "r", encoding="utf-8") as f:
    c = f.read()
print("Initial size:", len(c))

old="airports:'airports flughaefen',neighbors:'nachbarlaender',map_mode:'weltkarte map'};"
new="airports:'airports flughaefen',neighbors:'nachbarlaender',map_mode:'weltkarte map',tiere:'tiere natur animals nature tierwelt'};"
assert c.count(old)==1,f"catLabels:{c.count(old)}"; c=c.replace(old,new,1); print("1 catLabels OK")

old='    {n:"Przewalski-Pferd (Mongolei)",lat:47.0,lng:102.0}\n  ],\n\n  /* 2. Big Five Nationalparks */\n  tiere_bigfive:['
new='    {n:"Przewalski-Pferd (Mongolei)",lat:47.0,lng:102.0},\n    {n:"Aye-Aye (Madagaskar)",lat:-18.7,lng:46.9},\n    {n:"Indri (Madagaskar)",lat:-18.9,lng:48.4},\n    {n:"Quokka (Westaustralien)",lat:-31.9,lng:115.9},\n    {n:"Numbat (Westaustralien)",lat:-32.4,lng:118.5},\n    {n:"Bilby (Zentralaustralien)",lat:-25.0,lng:128.0},\n    {n:"Schnabeltier (Queensland)",lat:-27.0,lng:153.0},\n    {n:"Kurzschnabeligel (Australien)",lat:-28.0,lng:134.0},\n    {n:"Kea (Neuseeland)",lat:-43.5,lng:172.0},\n    {n:"Tuatara (Neuseeland)",lat:-41.3,lng:174.8},\n    {n:"Takahe (Fiordland NZ)",lat:-45.5,lng:167.7},\n    {n:"Okapi (Kongo-Regenwald)",lat:1.0,lng:29.0},\n    {n:"Drill (Kamerun)",lat:5.0,lng:9.5},\n    {n:"Mandrill (Gabun)",lat:-0.4,lng:11.6},\n    {n:"Baumk\\u00e4nguru (Neuguinea)",lat:-6.0,lng:147.0},\n    {n:"Kasuar (Neuguinea)",lat:-4.0,lng:136.0},\n    {n:"Philippinenadler (Mindanao)",lat:8.0,lng:126.0},\n    {n:"Tarsier (Sulawesi)",lat:-1.0,lng:122.0},\n    {n:"Babirusa (Sulawesi)",lat:0.5,lng:121.0},\n    {n:"Anoa (Sulawesi)",lat:-2.0,lng:121.5},\n    {n:"Malaiischer Tapir (Sumatra)",lat:3.6,lng:102.0},\n    {n:"Riesenpanda (Sichuan)",lat:30.5,lng:104.0},\n    {n:"Roter Panda (Himalaya-Yunnan)",lat:27.0,lng:88.5},\n    {n:"Saiga-Antilope (Kasachstan)",lat:50.0,lng:62.0},\n    {n:"Vikuja (Peru-Anden)",lat:-14.0,lng:-75.0},\n    {n:"Darwin-Fuchs (Chile)",lat:-38.0,lng:-73.0},\n    {n:"Galapagos-Pinguin (Isabela)",lat:-0.6,lng:-91.3},\n    {n:"Galapagos-Meeresleguan (Santa Cruz)",lat:-0.7,lng:-91.0},\n    {n:"Irawaddy-Delfin (Mekong)",lat:13.0,lng:105.0},\n    {n:"Florida-Panther (Everglades)",lat:26.0,lng:-81.0},\n    {n:"Puerto-Rico-Amazone (El Yunque)",lat:18.3,lng:-66.6},\n    {n:"Zwergelefant (Borneo)",lat:5.0,lng:118.0},\n    {n:"Nilgiri-Tahr (S\\u00fcdindien)",lat:10.1,lng:77.1},\n    {n:"Andentapir (Kolumbien)",lat:1.0,lng:-77.0},\n    {n:"Gerenuk (Kenia-Savanne)",lat:1.0,lng:40.5},\n    {n:"Gelada-Pavian (\\u00c4thiopien)",lat:12.0,lng:39.5},\n    {n:"\\u00c4thiopischer Wolf (Bale Mountains)",lat:6.9,lng:39.9},\n    {n:"Walia-Steinbock (Simien)",lat:13.2,lng:38.1},\n    {n:"Rodrigues-Flughund (Mauritius)",lat:-19.7,lng:63.4},\n    {n:"Nene (Hawaii-Inseln)",lat:20.0,lng:-155.0},\n    {n:"Iberischer Luchs (Andalusien)",lat:38.0,lng:-6.5},\n    {n:"Schneeaffe (Japan-Alpen)",lat:36.7,lng:138.0},\n    {n:"Guanako (Patagonien)",lat:-50.0,lng:-72.0},\n    {n:"Pangolin (Mittelafrika-Kongo)",lat:5.0,lng:18.0},\n    {n:"Sri-Lanka-Elefant (Minneriya)",lat:7.9,lng:80.7},\n    {n:"Wisent (Bia\\u0142owie\\u017ca Polen)",lat:52.7,lng:23.8},\n    {n:"Markhor (Hindukusch-Pakistan)",lat:36.0,lng:71.5},\n    {n:"Vaquita (Golf von Kalifornien)",lat:31.0,lng:-114.7},\n    {n:"Hainan-Gibbon (China)",lat:19.0,lng:109.0}\n  ],\n\n  /* 2. Big Five Nationalparks */\n  tiere_bigfive:['
assert c.count(old)==1,f"endemisch:{c.count(old)}"; c=c.replace(old,new,1); print("2 endemisch OK (+48)")

old='    {n:"Mikumi NP (Tansania)",lat:-7.4,lng:37.1}\n  ],\n\n  /* 3. Großkatzen-Habitate */\n  tiere_grosskatzen:['
new='    {n:"Mikumi NP (Tansania)",lat:-7.4,lng:37.1},\n    {n:"Bwindi Impenetrable NP (Uganda)",lat:-1.0,lng:29.6},\n    {n:"Queen Elizabeth NP (Uganda)",lat:-0.2,lng:30.0},\n    {n:"Murchison Falls NP (Uganda)",lat:2.2,lng:31.7},\n    {n:"Mana Pools NP (Simbabwe)",lat:-15.8,lng:29.4},\n    {n:"Zakouma NP (Tschad)",lat:10.8,lng:19.8},\n    {n:"Pendjari NP (Benin)",lat:11.3,lng:1.8},\n    {n:"Lewa Conservancy (Kenia)",lat:0.2,lng:37.5},\n    {n:"Samburu NP (Kenia)",lat:0.6,lng:37.5},\n    {n:"Tarangire NP (Tansania)",lat:-4.0,lng:36.0},\n    {n:"Lake Manyara NP (Tansania)",lat:-3.5,lng:35.8},\n    {n:"Marakele NP (S\\u00fcdafrika)",lat:-24.3,lng:27.7},\n    {n:"Pilanesberg NP (S\\u00fcdafrika)",lat:-25.2,lng:27.0},\n    {n:"Nyika NP (Malawi)",lat:-11.0,lng:33.9},\n    {n:"Lower Zambezi NP (Sambia)",lat:-15.5,lng:29.5},\n    {n:"Liuwa Plain NP (Sambia)",lat:-14.5,lng:22.6},\n    {n:"Waterberg Plateau NP (Namibia)",lat:-20.4,lng:17.2},\n    {n:"Bwabwata NP (Namibia)",lat:-18.2,lng:21.8},\n    {n:"Ongava GR (Namibia)",lat:-19.1,lng:15.8}\n  ],\n\n  /* 3. Großkatzen-Habitate */\n  tiere_grosskatzen:['
assert c.count(old)==1,f"bigfive:{c.count(old)}"; c=c.replace(old,new,1); print("3 bigfive OK (+18)")

old='    {n:"Afrikanischer Leopard (Kongo)",lat:-1.0,lng:24.0}\n  ],\n\n  /* 4. Invasive Arten — Ursprungsland */\n  tiere_invasiv:['
new='    {n:"Afrikanischer Leopard (Kongo)",lat:-1.0,lng:24.0},\n    {n:"Bengalischer Tiger (Ranthambore)",lat:26.0,lng:76.5},\n    {n:"Indochinesischer Tiger (Myanmar)",lat:21.0,lng:96.5},\n    {n:"Malaiischer Tiger (Taman Negara)",lat:4.5,lng:102.3},\n    {n:"Jaguar (Corcovado, Costa Rica)",lat:8.5,lng:-83.6},\n    {n:"Jaguar (Belize-Regenwald)",lat:17.0,lng:-88.5},\n    {n:"Schneeleopard (Altai-Gebirge)",lat:49.5,lng:87.5},\n    {n:"Schneeleopard (Pamir)",lat:38.5,lng:73.0},\n    {n:"Afrikanischer L\\u00f6we (Etosha)",lat:-18.9,lng:16.3},\n    {n:"Afrikanischer L\\u00f6we (Kruger NP)",lat:-24.0,lng:31.5},\n    {n:"Gepard (Serengeti-Ebene)",lat:-2.5,lng:35.0},\n    {n:"Gepard (Kalahari)",lat:-25.0,lng:21.0},\n    {n:"Puma (Rocky Mountains)",lat:40.0,lng:-105.5},\n    {n:"Nebelparder (Sumatra)",lat:2.0,lng:99.5},\n    {n:"Persischer Leopard (Iran)",lat:32.0,lng:53.0},\n    {n:"Asiatischer Gepard (Iran-Plateau)",lat:35.0,lng:55.0},\n    {n:"Serval (Ostafrika-Savanne)",lat:-3.0,lng:36.0},\n    {n:"Karakal (Nordindien)",lat:27.0,lng:76.0},\n    {n:"Puma (Andes, Peru)",lat:-10.0,lng:-75.5},\n    {n:"Jaguar (Gran Chaco, Paraguay)",lat:-22.0,lng:-60.0},\n    {n:"Schneeleopard (Tian Shan)",lat:42.0,lng:80.0}\n  ],\n\n  /* 4. Invasive Arten — Ursprungsland */\n  tiere_invasiv:['
assert c.count(old)==1,f"grosskatzen:{c.count(old)}"; c=c.replace(old,new,1); print("4 grosskatzen OK (+20)")

old='    {n:"Hausratte (Weltweit) → Südasien",lat:25.0,lng:78.0}\n  ],\n\n  /* 5. Vogelzug-Knotenpunkte */\n  tiere_vogelzug:['
new='    {n:"Hausratte (Weltweit) → Südasien",lat:25.0,lng:78.0},\n    {n:"Wasserhyazinthe (Weltweit) \\u2192 Brasilien",lat:-15.0,lng:-47.0},\n    {n:"Niltilapia (Ostafrika) \\u2192 Nilbecken",lat:15.0,lng:32.0},\n    {n:"Burmesische Python (Everglades) \\u2192 S\\u00fcdostasien",lat:10.0,lng:100.0},\n    {n:"Braune Baumschlange (Guam) \\u2192 Australien",lat:-25.0,lng:133.0},\n    {n:"Indischer Mungo (Karibik) \\u2192 S\\u00fcdasien",lat:20.0,lng:80.0},\n    {n:"Rote Feuerameise (USA/Weltweit) \\u2192 S\\u00fcdamerika",lat:-15.0,lng:-55.0},\n    {n:"Japanischer Staudenknoterich (Europa) \\u2192 Ostasien",lat:35.0,lng:139.0},\n    {n:"Signal-Krebs (Europa) \\u2192 Nordamerika",lat:45.0,lng:-90.0},\n    {n:"Zebramuschel (USA) \\u2192 Schwarzmeer-Region",lat:46.0,lng:31.0},\n    {n:"Quagga-Muschel (Schweiz) \\u2192 Ponto-Kaspis",lat:47.0,lng:40.0},\n    {n:"Mink (Argentinien) \\u2192 Nordamerika",lat:50.0,lng:-95.0},\n    {n:"Amerikanischer Waschb\\u00e4r (Europa) \\u2192 Nordamerika",lat:40.0,lng:-80.0},\n    {n:"Kudzu (USA) \\u2192 Ostasien",lat:30.0,lng:115.0},\n    {n:"Nilbarsch (Uganda-Victoriasee) \\u2192 Nilbecken",lat:5.0,lng:32.0},\n    {n:"Asiatischer Feuerfisch (Karibik) \\u2192 Indopazifik",lat:5.0,lng:120.0},\n    {n:"Europ\\u00e4isches Kaninchen (Australien) \\u2192 Iberische Halbinsel",lat:40.0,lng:-4.0},\n    {n:"Rotfuchs (Australien) \\u2192 Europa",lat:50.0,lng:10.0},\n    {n:"Coqui-Frosch (Hawaii) \\u2192 Puerto Rico",lat:18.3,lng:-66.6},\n    {n:"Asiatischer Karpfen (USA-Mississippi) \\u2192 Ostasien",lat:32.0,lng:113.0},\n    {n:"Nilgans (Europa) \\u2192 Nil-Afrika",lat:10.0,lng:32.0},\n    {n:"Riesenbärenklau (Europa) \\u2192 Kaukasus",lat:42.0,lng:44.0},\n    {n:"Chinesische Wollhandkrabbe (UK) \\u2192 China",lat:32.0,lng:121.0},\n    {n:"Amerikanische Blaukrabbe (Europa) \\u2192 Nordamerika",lat:37.0,lng:-76.0}\n  ],\n\n  /* 5. Vogelzug-Knotenpunkte */\n  tiere_vogelzug:['
assert c.count(old)==1,f"invasiv:{c.count(old)}"; c=c.replace(old,new,1); print("5 invasiv OK (+23)")

old='    {n:"Bretagne (Frankreich, Seevögel)",lat:48.5,lng:-4.0}\n  ],\n\n  /* 6. Ursprung der Haustiere */\n  tiere_haustiere:['
new='    {n:"Bretagne (Frankreich, Seevögel)",lat:48.5,lng:-4.0},\n    {n:"Strait of Messina (Italien)",lat:38.2,lng:15.6},\n    {n:"Sahara-Querung (Tunesien)",lat:33.5,lng:9.0},\n    {n:"Sahel-Zone (Niger)",lat:14.0,lng:9.0},\n    {n:"Red Sea-K\\u00fcste (Sudan)",lat:21.0,lng:37.0},\n    {n:"Rift Valley (\\u00c4thiopien)",lat:8.5,lng:38.5},\n    {n:"Lake Victoria (Tansania/Kenia)",lat:-1.0,lng:32.9},\n    {n:"Djoudj NP (Senegal)",lat:16.5,lng:-16.2},\n    {n:"Banc d\'Arguin (Mauretanien)",lat:20.4,lng:-16.5},\n    {n:"Bhutan-Himalaya-Pass (Bhutan)",lat:27.5,lng:91.0},\n    {n:"Miyako-Inseln (Japan, Fr\\u00fchlingsszug)",lat:24.8,lng:125.3},\n    {n:"Hokkaido (Japan, Kraniche)",lat:43.5,lng:144.0},\n    {n:"Poyang-See (China, Zugv\\u00f6gel)",lat:29.0,lng:116.2},\n    {n:"Bohai Bay (China, Limikolen)",lat:38.5,lng:121.0},\n    {n:"Incheon Tidal Flats (S\\u00fcdkorea)",lat:37.5,lng:126.4},\n    {n:"Copper River Delta (Alaska)",lat:60.5,lng:-145.0},\n    {n:"Delaware Bay (USA, Limikolen)",lat:39.2,lng:-75.3},\n    {n:"Cape May (New Jersey)",lat:38.9,lng:-74.9},\n    {n:"Gulf Coast (Texas)",lat:27.0,lng:-97.0},\n    {n:"Yucatan (Mexiko, Herbst-Korridor)",lat:19.5,lng:-89.5},\n    {n:"Mar Chiquita (Argentinien)",lat:-30.7,lng:-62.6},\n    {n:"Tierra del Fuego (Zugziel, Chile)",lat:-53.5,lng:-70.0},\n    {n:"Fair Isle (Schottland)",lat:59.5,lng:-1.6},\n    {n:"Helgoland (Nordsee)",lat:54.2,lng:7.9},\n    {n:"Courland Spit (Ostsee)",lat:55.3,lng:21.1}\n  ],\n\n  /* 6. Ursprung der Haustiere */\n  tiere_haustiere:['
assert c.count(old)==1,f"vogelzug:{c.count(old)}"; c=c.replace(old,new,1); print("6 vogelzug OK (+24)")

old='    {n:"Seidenraupe (Gelbes-Fluss-Tal, China)",lat:34.0,lng:109.0}\n  ],\n\n  /* 7. Nationaltiere Pin */\n  tiere_nationaltier_pin'
new='    {n:"Seidenraupe (Gelbes-Fluss-Tal, China)",lat:34.0,lng:109.0},\n    {n:"Wasserbüffel (Indus-Tal, Pakistan)",lat:26.0,lng:72.0},\n    {n:"Kaninchen (Mittelmeerraum, Iberien)",lat:37.0,lng:-4.0},\n    {n:"Frettchen (Westeuropa)",lat:48.0,lng:2.0},\n    {n:"Taube (Naher Osten)",lat:32.0,lng:35.5},\n    {n:"Seidenhuhn (China, Jiangnan)",lat:30.0,lng:115.0},\n    {n:"Koi-Karpfen (Japan, Niigata)",lat:37.4,lng:139.0},\n    {n:"Alpaka (Anden, Peru)",lat:-13.5,lng:-75.0},\n    {n:"Trampeltier (Zentralasien)",lat:42.0,lng:64.0},\n    {n:"Yak (Tibetisches Hochland)",lat:30.0,lng:90.0}\n  ],\n\n  /* 7. Nationaltiere Pin */\n  tiere_nationaltier_pin'
assert c.count(old)==1,f"haustiere:{c.count(old)}"; c=c.replace(old,new,1); print("7 haustiere OK (+9)")

old='{n:"Madagaskar-Regenwald",lat:-18.91,lng:47.54}\n  ]},\n  tiere_zoos:{prompt:"Wo liegt'
new='{n:"Madagaskar-Regenwald",lat:-18.91,lng:47.54},\n    {n:"Bwindi Impenetrable NP",lat:-1.0,lng:29.6},\n    {n:"Kaziranga NP",lat:26.6,lng:93.2},\n    {n:"Ranthambore NP",lat:26.0,lng:76.5},\n    {n:"Jim Corbett NP",lat:29.5,lng:79.0},\n    {n:"Chitwan NP",lat:27.5,lng:84.4},\n    {n:"Khao Yai NP",lat:14.4,lng:101.4},\n    {n:"Taman Negara",lat:4.0,lng:102.0},\n    {n:"Gunung Leuser NP",lat:3.9,lng:97.5},\n    {n:"Ujung Kulon NP",lat:-6.8,lng:105.4},\n    {n:"Komodo NP",lat:-8.5,lng:119.5},\n    {n:"Great Smoky Mountains NP",lat:35.7,lng:-83.5},\n    {n:"Everglades NP",lat:25.4,lng:-80.9},\n    {n:"Torres del Paine NP",lat:-51.0,lng:-73.0},\n    {n:"Corcovado NP",lat:8.5,lng:-83.6},\n    {n:"Manu NP",lat:-11.9,lng:-71.4},\n    {n:"Kilimanjaro NP",lat:-3.1,lng:37.4},\n    {n:"Mount Kenya NP",lat:-0.1,lng:37.3},\n    {n:"Masoala NP",lat:-15.5,lng:50.5},\n    {n:"Tsingy de Bemaraha",lat:-19.0,lng:44.8},\n    {n:"Białowieża NP (Belarus)",lat:52.8,lng:23.9},\n    {n:"Sarek NP",lat:67.3,lng:17.7},\n    {n:"Svalbard NP",lat:79.0,lng:17.0},\n    {n:"Plitvicer Seen NP",lat:44.9,lng:15.6},\n    {n:"Sierra Nevada NP (Spanien)",lat:37.1,lng:-3.4},\n    {n:"Kakadu NP",lat:-13.0,lng:132.5},\n    {n:"Fiordland NP",lat:-45.4,lng:167.7},\n    {n:"Lorentz NP",lat:-4.8,lng:137.5},\n    {n:"Wrangel Island Reserve",lat:71.0,lng:-179.5},\n    {n:"Wood Buffalo NP",lat:59.0,lng:-112.0},\n    {n:"Great Bear Rainforest",lat:52.0,lng:-127.0}\n  ]},\n  tiere_zoos:{prompt:"Wo liegt'
assert c.count(old)==1,f"schutzgebiete:{c.count(old)}"; c=c.replace(old,new,1); print("8 schutzgebiete OK (+30)")

old='{n:"Budapest Zoo",lat:47.51,lng:19.08}\n  ]},\n  tiere_nutztier_rassen:{prompt:"Wo wur'
new='{n:"Budapest Zoo",lat:47.51,lng:19.08},\n    {n:"Zoo Leipzig",lat:51.34,lng:12.38},\n    {n:"Kölner Zoo",lat:50.97,lng:6.97},\n    {n:"Tierpark Berlin",lat:52.5,lng:13.52},\n    {n:"Wilhelma Stuttgart",lat:48.8,lng:9.21},\n    {n:"Zoo Frankfurt",lat:50.12,lng:8.72},\n    {n:"Zoo Antwerpen",lat:51.22,lng:4.42},\n    {n:"Zoo Kopenhagen",lat:55.67,lng:12.52},\n    {n:"Kolmårdens Djurpark (Schweden)",lat:58.68,lng:16.37},\n    {n:"Zoo Helsinki",lat:60.1,lng:25.08},\n    {n:"Moscow Zoo",lat:55.76,lng:37.57},\n    {n:"Shanghai Zoo",lat:31.19,lng:121.41},\n    {n:"Chengdu Giant Panda Research Base",lat:30.73,lng:104.14},\n    {n:"Taipei Zoo",lat:24.99,lng:121.58},\n    {n:"Seoul Grand Park Zoo",lat:37.43,lng:127.01},\n    {n:"Asahiyama Zoo (Japan)",lat:43.77,lng:142.37},\n    {n:"Johannesburg Zoo",lat:-26.17,lng:28.05},\n    {n:"Adelaide Zoo",lat:-34.92,lng:138.6},\n    {n:"Perth Zoo",lat:-31.98,lng:115.85},\n    {n:"Wellington Zoo",lat:-41.31,lng:174.77},\n    {n:"Los Angeles Zoo",lat:34.15,lng:-118.3},\n    {n:"Bronx Zoo",lat:40.85,lng:-73.88},\n    {n:"National Zoo Washington",lat:38.93,lng:-77.05},\n    {n:"Chicago Lincoln Park Zoo",lat:41.92,lng:-87.64},\n    {n:"Cincinnati Zoo",lat:39.14,lng:-84.51},\n    {n:"Denver Zoo",lat:39.75,lng:-104.95},\n    {n:"San Francisco Zoo",lat:37.73,lng:-122.5},\n    {n:"Seattle Woodland Park Zoo",lat:47.67,lng:-122.35},\n    {n:"Vancouver Aquarium",lat:49.3,lng:-123.13},\n    {n:"Bioparc Lyon",lat:45.77,lng:4.82},\n    {n:"Pairi Daiza (Belgien)",lat:50.55,lng:3.88},\n    {n:"Rotterdam Diergaarde Blijdorp",lat:51.93,lng:4.43},\n    {n:"Burgers\' Zoo (Arnhem)",lat:51.98,lng:5.89},\n    {n:"Zoo Prag",lat:50.12,lng:14.41},\n    {n:"Zoo Warschau",lat:52.25,lng:21.02},\n    {n:"Zoo Lissabon",lat:38.74,lng:-9.17},\n    {n:"Zoo Madrid",lat:40.41,lng:-3.74},\n    {n:"Hellabrunn Zoo München",lat:48.1,lng:11.55},\n    {n:"Zoo Hannover",lat:52.37,lng:9.74},\n    {n:"Zoo Rostock",lat:54.09,lng:12.11},\n    {n:"Zoo Karlsruhe",lat:49.0,lng:8.39}\n  ]},\n  tiere_nutztier_rassen:{prompt:"Wo wur'
assert c.count(old)==1,f"zoos:{c.count(old)}"; c=c.replace(old,new,1); print("9 zoos OK (+40)")

old='{n:"Zebu-Rind",lat:11.00,lng:78.00}\n  ]},\n  tiere_fossilien:{prompt:"Wo liegt diese '
new='{n:"Zebu-Rind",lat:11.00,lng:78.00},\n    {n:"Charolais-Rind",lat:46.8,lng:4.3},\n    {n:"Limousin-Rind",lat:45.83,lng:1.26},\n    {n:"Galloway-Rind",lat:55.0,lng:-4.0},\n    {n:"Texel-Schaf",lat:53.03,lng:4.8},\n    {n:"Corriedale-Schaf",lat:-44.0,lng:170.0},\n    {n:"Boer-Ziege",lat:-33.0,lng:26.0},\n    {n:"Toggenburger Ziege",lat:47.35,lng:9.38},\n    {n:"Landrace-Schwein",lat:56.0,lng:10.0},\n    {n:"Pietrain-Schwein",lat:50.62,lng:4.53},\n    {n:"Noriker-Pferd",lat:47.8,lng:13.5},\n    {n:"Orpington-Huhn",lat:51.4,lng:0.1},\n    {n:"Marans-Huhn",lat:45.83,lng:-0.97},\n    {n:"Toulouse-Gans",lat:43.6,lng:1.44},\n    {n:"Emden-Gans",lat:53.37,lng:7.21},\n    {n:"Anatolisches Schaf (Kivircik)",lat:40.0,lng:29.0},\n    {n:"Katahdin-Schaf",lat:45.2,lng:-68.8},\n    {n:"Manx Loaghtan (Isle of Man)",lat:54.2,lng:-4.5},\n    {n:"Dexter-Rind",lat:53.5,lng:-8.0},\n    {n:"Muscovy-Ente",lat:-5.0,lng:-55.0},\n    {n:"Schwarzwälder Kaltblut",lat:47.9,lng:8.1}\n  ]},\n  tiere_fossilien:{prompt:"Wo liegt diese '
assert c.count(old)==1,f"nutztier:{c.count(old)}"; c=c.replace(old,new,1); print("10 nutztier OK (+20)")

old='{n:"Patagonien-Dino-Canyon",lat:-41.87,lng:-66.70}\n  ]},\n\n  /* === Pferde-DLC: Pin-Daten (1 Modus) === */\n  pferde_rassen:{p'
new='{n:"Patagonien-Dino-Canyon",lat:-41.87,lng:-66.70},\n    {n:"La Brea Tar Pits (Los Angeles)",lat:34.06,lng:-118.36},\n    {n:"Joggins Fossil Cliffs (Kanada)",lat:45.7,lng:-64.44},\n    {n:"Riversleigh (Australien)",lat:-19.07,lng:138.7},\n    {n:"Naracoorte Caves (Australien)",lat:-37.01,lng:140.78},\n    {n:"Sterkfontein (Südafrika)",lat:-26.02,lng:27.73},\n    {n:"Chengjiang Formation (Yunnan)",lat:24.5,lng:103.0},\n    {n:"Florissant Fossil Beds (Colorado)",lat:38.91,lng:-105.28},\n    {n:"John Day Fossil Beds (Oregon)",lat:44.55,lng:-119.64},\n    {n:"Liaoning Jiufotang Formation",lat:41.3,lng:121.0},\n    {n:"Las Hoyas (Spanien)",lat:40.24,lng:-2.55},\n    {n:"Fayum Depression (Ägypten)",lat:29.3,lng:30.55},\n    {n:"Rusinga Island (Kenia)",lat:-0.37,lng:34.15},\n    {n:"Nemegt Formation (Mongolei)",lat:43.0,lng:100.0},\n    {n:"Kem Kem (Marokko, Spinosaurus)",lat:31.0,lng:-4.5},\n    {n:"Mazon Creek (Illinois, Karbon)",lat:41.4,lng:-88.4},\n    {n:"Hukawng Valley (Myanmar, Bernstein)",lat:26.5,lng:96.6},\n    {n:"Cradle of Humankind (Südafrika)",lat:-26.02,lng:27.75},\n    {n:"El Breal de Orocual (Venezuela)",lat:9.6,lng:-62.8},\n    {n:"Walvis Bay (Namibia, Kreide)",lat:-22.96,lng:14.51},\n    {n:"Mahenge (Tansania, Eozän)",lat:-8.7,lng:36.7}\n  ]},\n\n  /* === Pferde-DLC: Pin-Daten (1 Modus) === */\n  pferde_rassen:{p'
assert c.count(old)==1,f"fossilien:{c.count(old)}"; c=c.replace(old,new,1); print("11 fossilien OK (+20)")

old='{n:"Paint Horse",lat:35.50,lng:-97.50}\n  ]},\n\n  /* === Phase 216: Match-Kategorien (Schritt 3) === */\n  insel_match:[{n:"Gal'
new='{n:"Paint Horse",lat:35.50,lng:-97.50},\n    {n:"Lusitano",lat:38.7,lng:-9.2},\n    {n:"Knabstrupper (Dänemark)",lat:55.5,lng:11.8},\n    {n:"Noriker",lat:47.8,lng:13.5},\n    {n:"Akhal-Teke (Turkmenistan)",lat:38.0,lng:58.5},\n    {n:"Marwari (Rajasthan)",lat:27.02,lng:74.22},\n    {n:"Kathiawari (Gujarat)",lat:22.3,lng:70.0},\n    {n:"Morgan Horse (Vermont)",lat:44.0,lng:-72.5},\n    {n:"Tennessee Walking Horse",lat:35.7,lng:-86.5},\n    {n:"Standardbred (Pennsylvania)",lat:40.1,lng:-76.0},\n    {n:"Paso Fino (Puerto Rico/Kolumbien)",lat:18.2,lng:-66.5},\n    {n:"Peruanischer Paso",lat:-12.0,lng:-77.0},\n    {n:"Criollo (Argentinien)",lat:-34.0,lng:-64.0},\n    {n:"Barb (Nordafrika)",lat:34.0,lng:3.0},\n    {n:"Boerperd (Südafrika)",lat:-30.0,lng:25.0},\n    {n:"Basuto-Pony (Lesotho)",lat:-29.5,lng:28.5},\n    {n:"Franches-Montagnes (Schweiz)",lat:47.3,lng:7.2},\n    {n:"Schwarzwälder Fuchs",lat:47.9,lng:8.1},\n    {n:"Rocky Mountain Horse",lat:37.5,lng:-83.5},\n    {n:"Mangalarga Marchador (Brasilien)",lat:-19.9,lng:-43.9},\n    {n:"Noric-Kaltblut (Österreich)",lat:47.5,lng:14.0}\n  ]},\n\n  /* === Phase 216: Match-Kategorien (Schritt 3) === */\n  insel_match:[{n:"Gal'
assert c.count(old)==1,f"pferde_rassen:{c.count(old)}"; c=c.replace(old,new,1); print("12 pferde_rassen OK (+20)")

old='{n:"Lemminge",c:"Arktis (Nordpol)"}\n  ]},\n  forscher_eponyme:'
new='{n:"Lemminge",c:"Arktis (Nordpol)"},\n    {n:"Königspinguin",c:"Antarktis (Südpol)"},\n    {n:"Eisfisch (Channichthyidae)",c:"Antarktis (Südpol)"},\n    {n:"Antarktischer Krill",c:"Antarktis (Südpol)"},\n    {n:"Skua (Antarktische)",c:"Antarktis (Südpol)"},\n    {n:"Zwergwal (Südpolarmeer)",c:"Antarktis (Südpol)"},\n    {n:"Grönlandwal",c:"Arktis (Nordpol)"},\n    {n:"Makaroni-Pinguin",c:"Antarktis (Südpol)"},\n    {n:"Arktischer Charr",c:"Arktis (Nordpol)"},\n    {n:"Arktischer Polardorsch",c:"Arktis (Nordpol)"},\n    {n:"Antarktischer Albatros",c:"Antarktis (Südpol)"},\n    {n:"Spitzbergen-Rentier",c:"Arktis (Nordpol)"},\n    {n:"Gentoo-Pinguin",c:"Antarktis (Südpol)"},\n    {n:"Chinstrap-Pinguin",c:"Antarktis (Südpol)"},\n    {n:"Elfenbeinmöwe",c:"Arktis (Nordpol)"},\n    {n:"Sibirischer Lemming (Tundra)",c:"Arktis (Nordpol)"},\n    {n:"Schneeeule (Wanderzug)",c:"Arktis (Nordpol)"},\n    {n:"Moschusochse (Grönland)",c:"Arktis (Nordpol)"},\n    {n:"Weddell-Seehund",c:"Antarktis (Südpol)"},\n    {n:"Sattelrobbe",c:"Arktis (Nordpol)"},\n    {n:"Antarktische Meeresechse",c:"Antarktis (Südpol)"}\n  ]},\n  forscher_eponyme:'
assert c.count(old)==1,f"arktis:{c.count(old)}"; c=c.replace(old,new,1); print("13 arktis OK (+20)")

old='{n:"Gray-Breitnassenb\\u00e4r",c:"John E. Gray"}\n  ]},\n  pelagial:'
new='{n:"Gray-Breitnassenb\\u00e4r",c:"John E. Gray"},\n    {n:"Blyth-Hornvogel",c:"Edward Blyth"},\n    {n:"Sclater-Brüllaffe",c:"Philip Sclater"},\n    {n:"Müller-Gibbon",c:"Salomon Müller"},\n    {n:"Jerdon-Buschlerche",c:"Thomas C. Jerdon"},\n    {n:"Hodgson-Schilfhühnchen",c:"Brian Houghton Hodgson"},\n    {n:"Ridgway-Sturmvogel",c:"Robert Ridgway"},\n    {n:"Bewick-Schwan",c:"Thomas Bewick"},\n    {n:"Leach-Sturmschwalbe",c:"William Elford Leach"},\n    {n:"Audubon-Bussard",c:"John James Audubon"},\n    {n:"Temminck-Tragopan",c:"Coenraad Temminck"},\n    {n:"Blanford-Uhu",c:"William T. Blanford"},\n    {n:"Swinhoe-Fasan",c:"Robert Swinhoe"},\n    {n:"Peters-Zwergfledermaus",c:"Wilhelm Peters"},\n    {n:"Schlegel-Rennechse",c:"Hermann Schlegel"},\n    {n:"Gould-Sittich",c:"John Gould"},\n    {n:"Layard-Schlangenhalsvogel",c:"Edgar Leopold Layard"},\n    {n:"Sharpe-Schnäpper",c:"Richard Bowdler Sharpe"},\n    {n:"Tristram-Steinschmätzer",c:"Henry Baker Tristram"},\n    {n:"Peters-Warzenschwein",c:"Wilhelm Peters"},\n    {n:"Vigors-Sonnenvogel",c:"Nicholas Aylward Vigors"}\n  ]},\n  pelagial:'
assert c.count(old)==1,f"forscher:{c.count(old)}"; c=c.replace(old,new,1); print("14 forscher OK (+20)")

old='{n:"Schwarzer Schlund-Aal",c:"Bathypelagial (1000-4000m)"}\n  ]},\n  wuesten_spezialisten:'
new='{n:"Schwarzer Schlund-Aal",c:"Bathypelagial (1000-4000m)"},\n    {n:"Sattelrobbe (Jagdtiefe)",c:"Epipelagial (0-200m)"},\n    {n:"Portugiesische Galeere",c:"Epipelagial (0-200m)"},\n    {n:"Tiefsee-Skorpionsfisch",c:"Bathypelagial (1000-4000m)"},\n    {n:"Hatchetfish (Beilbauchfisch)",c:"Mesopelagial (200-1000m)"},\n    {n:"Barreleye-Fisch (Opisthoproctus)",c:"Mesopelagial (200-1000m)"},\n    {n:"Abyssale Seegurke",c:"Abyssopelagial (4000-6000m)"},\n    {n:"Riesenassel (Bathynomus)",c:"Bathypelagial (1000-4000m)"},\n    {n:"Tiefsee-Garnele (Acanthephyra)",c:"Mesopelagial (200-1000m)"},\n    {n:"Weißer Hai (Jagdtiefe)",c:"Epipelagial (0-200m)"},\n    {n:"Manta-Rochen",c:"Epipelagial (0-200m)"},\n    {n:"Tiefsee-Anglerfisch (Melanocetus)",c:"Bathypelagial (1000-4000m)"},\n    {n:"Riesentintenfisch (Architeuthis)",c:"Bathypelagial (1000-4000m)"},\n    {n:"Colossal Squid",c:"Bathypelagial (1000-4000m)"},\n    {n:"Grönlandhai",c:"Bathypelagial (1000-4000m)"},\n    {n:"Tiefsee-Oktopus (Grimpoteuthis)",c:"Abyssopelagial (4000-6000m)"},\n    {n:"Lanzettfisch (Alepisaurus)",c:"Mesopelagial (200-1000m)"},\n    {n:"Koboldhai (Mitsukurina)",c:"Bathypelagial (1000-4000m)"},\n    {n:"Flötenaal (Anguilliformes)",c:"Mesopelagial (200-1000m)"},\n    {n:"Tiefseequalle (Deepstaria)",c:"Bathypelagial (1000-4000m)"},\n    {n:"Polychaet-Wurm (Tiefsee)",c:"Abyssopelagial (4000-6000m)"}\n  ]},\n  wuesten_spezialisten:'
assert c.count(old)==1,f"pelagial:{c.count(old)}"; c=c.replace(old,new,1); print("15 pelagial OK (+20)")

old='{n:"R\\u00fcsselpfeifen-Echse",c:"Namib"}\n  ]},\n  gift_hotspots:'
new='{n:"R\\u00fcsselpfeifen-Echse",c:"Namib"},\n    {n:"Addax-Antilope",c:"Sahara"},\n    {n:"Sahara-Silberfuchs",c:"Sahara"},\n    {n:"W\\u00fcstenigel",c:"Arabische W\\u00fcste"},\n    {n:"R\\u00fcstenspringmaus (Sahara)",c:"Sahara"},\n    {n:"Riesenhornechse",c:"Sonora-W\\u00fcste"},\n    {n:"Klapperschlange (Diamantback)",c:"Sonora-W\\u00fcste"},\n    {n:"W\\u00fcustenrennmaus (Mongolei)",c:"Gobi"},\n    {n:"Takhi (Przewalski-Pferd)",c:"Gobi"},\n    {n:"Namibtaube",c:"Namib"},\n    {n:"Nebeltrinker-K\\u00e4fer",c:"Namib"},\n    {n:"Bilby (W\\u00fcustenart)",c:"Australische W\\u00fcste"},\n    {n:"Mulgara",c:"Australische W\\u00fcste"},\n    {n:"Atacama-Laufechse",c:"Atacama"},\n    {n:"Sinai-Steinbock",c:"Arabische W\\u00fcste"},\n    {n:"Arabischer Wolf",c:"Arabische W\\u00fcste"},\n    {n:"Gobi-B\\u00e4r (Mazaalai)",c:"Gobi"},\n    {n:"Sahara-Gepard (Nordafrika)",c:"Sahara"},\n    {n:"Lama (W\\u00fcustengrenze)",c:"Atacama"},\n    {n:"Nabataean Ibex",c:"Negev-W\\u00fcste"},\n    {n:"Kalahari-L\\u00f6we",c:"Kalahari"}\n  ]},\n  gift_hotspots:'
assert c.count(old)==1,f"wuesten:{c.count(old)}"; c=c.replace(old,new,1); print("16 wuesten OK (+20)")

old='{n:"Mamba (Schwarze)",c:"Subsahara-Afrika"}\n  ]},\n  migranten:'
new='{n:"Mamba (Schwarze)",c:"Subsahara-Afrika"},\n    {n:"Taipan (Küsten-Taipan)",c:"Australien"},\n    {n:"Todesnatter (Death Adder)",c:"Australien"},\n    {n:"Tigerotter",c:"Australien"},\n    {n:"Ägyptische Kobra",c:"Nordafrika"},\n    {n:"Puffotter",c:"Subsahara-Afrika"},\n    {n:"Grüne Mamba",c:"Subsahara-Afrika"},\n    {n:"Monokel-Kobra",c:"Südostasien"},\n    {n:"Kreuzotter (Europa)",c:"Europa"},\n    {n:"Hornviper",c:"Naher Osten/Nordafrika"},\n    {n:"Lanzenviper (Bothrops)",c:"Brasilien"},\n    {n:"Buschmeister-Viper",c:"Brasilien"},\n    {n:"Gabun-Riesenviper",c:"Subsahara-Afrika"},\n    {n:"Gila-Krustenechse (Gift)",c:"USA/Mexiko"},\n    {n:"Kegelschnecke (Conus geographus)",c:"Indopazifik"},\n    {n:"Blauring-Oktopus (Hapalochlaena)",c:"Australien/Pazifik"},\n    {n:"Steinfisch (Synanceia)",c:"Indopazifik"},\n    {n:"Pazifische Peitschennatter",c:"Ozeanien"},\n    {n:"Schlingnatter (Europa)",c:"Europa"},\n    {n:"Kashmiri-Felsviper",c:"Himalaya/Südasien"},\n    {n:"Korallenschlange (Ostamerika)",c:"USA/Mexiko"}\n  ]},\n  migranten:'
assert c.count(old)==1,f"gift:{c.count(old)}"; c=c.replace(old,new,1); print("17 gift OK (+20)")

old='{n:"Gnu (Botswana)",c:"Okavango-Linyanti-Zyklus"}\n  ]},\n  pferde_fachbegriffe:'
new='{n:"Gnu (Botswana)",c:"Okavango-Linyanti-Zyklus"},\n    {n:"Polarfuchs (Arktis)",c:"Arktis \\u2192 Subarktische Taiga"},\n    {n:"Grauer Storch",c:"Europa \\u2192 Ostafrika"},\n    {n:"Wachtel",c:"Europa \\u2192 Subsahara-Afrika"},\n    {n:"Kuckuck",c:"Europa \\u2192 Kongobecken"},\n    {n:"Wiedehopf",c:"Europa/Asien \\u2192 Tropenafrika"},\n    {n:"Humpback-Wal (Atlantik)",c:"Antarktis \\u2192 Karibik"},\n    {n:"Lederschildkr\\u00f6te",c:"Karibik \\u2192 Nordatlantik"},\n    {n:"Silberlachs",c:"Nordpazifik \\u2192 Oregon-Fl\\u00fcsse"},\n    {n:"Atlantischer Thunfisch",c:"Mittelmeer \\u2192 Nordatlantik"},\n    {n:"Distelfalter",c:"Afrika \\u2192 Nordeuropa"},\n    {n:"Riesenseeadler",c:"Sibirien \\u2192 Japan-K\\u00fcste"},\n    {n:"Sandregenpfeifer",c:"Arktis \\u2192 Neuseeland"},\n    {n:"Wei\\u00dfwangengans",c:"Gr\\u00f6nland \\u2192 Nordsee"},\n    {n:"Gro\\u00dfer Brachvogel",c:"Eurasien \\u2192 Westafrika"},\n    {n:"Wei\\u00dfstorch (Ostroute)",c:"Europa \\u2192 S\\u00fcdafrika (via Bosporus)"},\n    {n:"Kranich (Eurasien)",c:"Sibirien \\u2192 Indien/Spanien"},\n    {n:"Stelzenl\\u00e4ufer",c:"Europa \\u2192 Tropenafrika"},\n    {n:"Dreizehenmöwe",c:"Nordatlantik \\u2192 Tropenatlantik"},\n    {n:"Elch (Skandinavien)",c:"Norwegen \\u2192 Schweden (saisonal)"},\n    {n:"Karibu (Kanada)",c:"Borealer Wald \\u2192 Arktische Tundra"}\n  ]},\n  pferde_fachbegriffe:'
assert c.count(old)==1,f"migranten:{c.count(old)}"; c=c.replace(old,new,1); print("18 migranten OK (+20)")

old='{n:"Halfter",c:"Kopfzeug ohne Geb\\u00dft"}\n  ]},\n};'
new='{n:"Halfter",c:"Kopfzeug ohne Geb\\u00dft"},\n    {n:"Schritt",c:"Viersprung-Grundgang des Pferdes"},\n    {n:"Trab",c:"Zweitakt-Diagonalgang"},\n    {n:"Galopp",c:"Dreitakt-Sprunggang"},\n    {n:"R\\u00fccken",c:"Obere Verbindung zwischen Widerrist und Kruppe"},\n    {n:"Kruppe",c:"Hinterhand des Pferdes \\u00fcber dem Schweif"},\n    {n:"Fessel",c:"Gelenk zwischen R\\u00f6hrbein und Huf"},\n    {n:"Strahl",c:"V-f\\u00f6rmige Hornstruktur an der Hufsohle"},\n    {n:"Schopf",c:"M\\u00e4hnenansatz zwischen den Ohren"},\n    {n:"Ganaschen",c:"Kieferwinkel-Bereich am Pferdekopf"},\n    {n:"Vorhand",c:"Vorderteil: Kopf, Hals, Schulter, Vorderbeine"},\n    {n:"Hinterhand",c:"Kruppe, Oberschenkel, Unterschenkel, Hinterfu\\u00df"},\n    {n:"Longe",c:"Leine zum Zirkelreiten ohne Reiter"},\n    {n:"Volte",c:"Kreisbahn von 6 Metern Durchmesser"},\n    {n:"Traversale",c:"Seitw\\u00e4rtsgang mit Biegung in Bewegungsrichtung"},\n    {n:"Schultereinhalt",c:"\\u00dcbung: Vorhand auf innerer Spur"},\n    {n:"Piaffee",c:"Trabartiger Bewegung auf der Stelle"},\n    {n:"Passage",c:"Sehr getragener, federnder Trab"},\n    {n:"Trense",c:"Leichtes Geb\\u00dft am Pferd"},\n    {n:"Kandare",c:"Strenges Geb\\u00dft mit zwei Geb\\u00dftst\\u00e4ngen"},\n    {n:"Gurt",c:"Riemen zum Befestigen des Sattels"}\n  ]},\n};'
assert c.count(old)==1,f"pfachbeg:{c.count(old)}"; c=c.replace(old,new,1); print("19 pfachbeg OK (+20)")

old='{name:"S\\u00fcdkorea",val:2}\n  ]},\n  pferde_stockmass:'
new='{name:"S\\u00fcdkorea",val:2},\n    {name:"Bolivien",val:28},\n    {name:"Ecuador",val:19},\n    {name:"Kolumbien",val:14},\n    {name:"Venezuela",val:18},\n    {name:"Sambia",val:17},\n    {name:"Uganda",val:20},\n    {name:"Tansania",val:23},\n    {name:"Simbabwe",val:30},\n    {name:"Neuseeland (Südinsel)",val:156},\n    {name:"Island",val:64}\n  ]},\n  pferde_stockmass:'
assert c.count(old)==1,f"haustier_dichte:{c.count(old)}"; c=c.replace(old,new,1); print("20 haustier_dichte OK (+10)")

with open(SRC, "w", encoding="utf-8") as f:
    f.write(c)
print("Done, size:", len(c))
