"""patch_278b — Tiere Pin (restliche Keys) + Tiere Match auf ≥80."""
import json, os
BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, 'data')
_t = 0

def _m(fname, key, new_items, target=80):
    global _t
    fp = os.path.join(DATA, fname)
    with open(fp,'r',encoding='utf-8') as f: d=json.load(f)
    entry=d[key]; items=entry['items'] if isinstance(entry,dict) and 'items' in entry else entry
    is_pin='lat' in items[0]
    if is_pin:
        seen=set((round(i['lat'],1),round(i['lng'],1)) for i in items); add=0
        for it in new_items:
            if len(items)>=target: break
            k2=(round(it['lat'],1),round(it['lng'],1))
            if k2 not in seen: items.append(it);seen.add(k2);add+=1
    else:
        nf='name' if 'name' in items[0] else 'n'
        seen=set(i.get(nf,'') for i in items); add=0
        for it in new_items:
            if len(items)>=target: break
            nm=it.get(nf,'')
            if nm and nm not in seen: items.append(it);seen.add(nm);add+=1
    with open(fp,'w',encoding='utf-8') as f: json.dump(d,f,ensure_ascii=False,indent=2)
    _t += add
    print(f'  {"✅" if len(items)>=target else "⚠️ "+str(len(items))}  {fname}::{key}: +{add} → {len(items)}')

# ── tiere_pin: remaining keys ────────────────────────────────────────────────

_m('tiere_pin.json','tiere_invasiv',[
    {"n":"Nilnilbarsch (Nile Perch) Lake Victoria (Kenia/Uganda)","lat":-0.6,"lng":33.0},
    {"n":"Asiatische Hornisse Vespa velutina (Frankreich — invasiv)","lat":44.8,"lng":-0.6},
    {"n":"Braune Baumschlange (Boiga irregularis, Guam, USA)","lat":13.5,"lng":144.8},
    {"n":"Kaspisches Wasser-Hyazinthe-Gebiet (Iran — Eichhornia)","lat":37.3,"lng":49.6},
    {"n":"Florida Everglades (USA — Tigerpython invasiv)","lat":25.4,"lng":-80.6},
    {"n":"Wakame Alge Undaria (Tasmanien — Einschleppung)","lat":-43.0,"lng":147.3},
    {"n":"Hauskatze Felis catus (Australien — Schutzgebiet Threat)","lat":-23.0,"lng":133.0},
    {"n":"Karpfen (Cyprinus carpio) Murray-Darling Basin (Australien)","lat":-35.0,"lng":143.5},
    {"n":"Staudensauerampfer Fallopia japonica (England — Küste)","lat":51.5,"lng":-3.2},
    {"n":"Amerikanischer Nerz (Neovison vison, Schottland — Farmen)","lat":57.5,"lng":-4.0},
    {"n":"Grauhörnchen (Sciurus carolinensis, England — native Eichhörnchen verdrängt)","lat":51.7,"lng":-1.2},
    {"n":"Amerikanischer Mink (Neuseeland — Vogelnist)","lat":-36.0,"lng":174.5},
    {"n":"Roter Feuerfisch (Pterois volitans, Karibikmeer — invasiv)","lat":19.0,"lng":-71.5},
    {"n":"Asiatischer Seidenschwanz (Kenia — 1998 Einschleppung)","lat":-1.3,"lng":36.8},
    {"n":"Kudzu Pueraria montana (Georgia, USA — invasiv)","lat":33.7,"lng":-84.4},
    {"n":"Zebra-Muschel Dreissena polymorpha (Großer See Erie)","lat":42.2,"lng":-81.2},
    {"n":"Berberaffe Macaca sylvanus (Gibraltar — eingebürg.)","lat":36.14,"lng":-5.35},
    {"n":"Marderhund Nyctereutes procyonoides (Mitteleuropa — Finnland)","lat":60.5,"lng":25.0},
    {"n":"Amerikanischer Biber (Castor canadensis, Feuerland, Argentinien)","lat":-54.4,"lng":-67.0},
    {"n":"Grüne Boa (Boa constrictor, Florida Keys — invasiv)","lat":24.8,"lng":-80.8},
    {"n":"Nilgans Alopochen aegyptiaca (Deutschland — Rhein)","lat":50.9,"lng":6.9},
    {"n":"Wollhandkrabbe Eriocheir sinensis (Elbe, Deutschland)","lat":53.5,"lng":9.9},
    {"n":"Amerikanischer Ochsenfrosch Lithobates catesbeianus (Frankreich)","lat":44.3,"lng":0.0},
    {"n":"Flusskrebse Orconectes limosus (Rhein-Einzugsgebiet)","lat":48.5,"lng":7.7},
    {"n":"Iberischer Mink (Neovison macrodon, Portugal — eingeführt)","lat":41.5,"lng":-8.4},
    {"n":"Östlicher Graukopf-Papagei (Ecuador — invasiv)","lat":-0.2,"lng":-78.5},
    {"n":"Mungo Herpestes javanicus (Hawaii — Invasionsstelle)","lat":20.1,"lng":-155.8},
    {"n":"Coqui-Frosch Eleutherodactylus coqui (Hawaii)","lat":19.9,"lng":-155.1},
    {"n":"Kaninchen (Oryctolagus cuniculus, Australien — Myxomatose-Bekämpfung)","lat":-32.0,"lng":148.0},
    {"n":"Asiatische Tigermücke Aedes albopictus (Südeuropa — Nordvordringen)","lat":43.3,"lng":5.4},
])

_m('tiere_pin.json','tiere_vogelzug',[
    {"n":"Weißstorch-Rastplatz Oued Massa (Marokko)","lat":30.1,"lng":-9.65},
    {"n":"Kranich-Rastplatz Hortobágy (Ungarn)","lat":47.6,"lng":21.1},
    {"n":"Vogelzug Bosporus (Istanbul, Türkei — Engpass)","lat":41.05,"lng":29.0},
    {"n":"Zugvogel-Zählpunkt Gibraltar (UK)","lat":36.14,"lng":-5.35},
    {"n":"Kranich-Rastplatz Lac du Der (Frankreich)","lat":48.57,"lng":4.72},
    {"n":"Arktische Seeschwalbe-Route Wattenmeer (Deutschland)","lat":54.8,"lng":8.3},
    {"n":"Sandregenpfeifer-Wattenmeer (Niederlande)","lat":53.0,"lng":5.2},
    {"n":"Limosine-Zugstrecke Camargu (Frankreich)","lat":43.4,"lng":4.6},
    {"n":"Flamingo-Brutkolonie Camargue (Frankreich)","lat":43.52,"lng":4.65},
    {"n":"Weißpelikan-Route Doñana NP (Spanien)","lat":36.97,"lng":-6.43},
    {"n":"Halbinsel Lissabon-Zugpunkt (Portugal)","lat":38.76,"lng":-9.13},
    {"n":"Zugpunkt Falsterbo (Schweden — Greifvögel)","lat":55.39,"lng":12.84},
    {"n":"Hawk Watch Point Veracruz (Mexiko — Rekord 6 Mio. Greifvögel/Jahr)","lat":19.2,"lng":-96.1},
    {"n":"Point Pelee (Kanada — Singvogel-Frühjahrsrast)","lat":41.9,"lng":-82.5},
    {"n":"Cape May (New Jersey, USA — Zugpunkt Atlantik)","lat":38.93,"lng":-74.92},
    {"n":"Hawk Mountain Sanctuary (Pennsylvania, USA)","lat":40.64,"lng":-75.99},
    {"n":"Derby Hill (New York, USA — Greifvogel-Zugpunkt)","lat":43.55,"lng":-76.3},
    {"n":"Rio Grande Valley (Texas, USA — Zugvogel-Korridor)","lat":26.4,"lng":-98.1},
    {"n":"Padre Island (Texas, USA — Küstenzug)","lat":27.4,"lng":-97.4},
    {"n":"Izmir Kuş Gölü (Türkei — Zugvogel-Reservoir)","lat":38.65,"lng":26.92},
    {"n":"Al Asfar Lake (Saudi-Arabien — Zugvogel-Stopp)","lat":25.4,"lng":49.5},
    {"n":"Banc d'Arguin (Mauretanien — Wattvogel-Weltrekord)","lat":20.5,"lng":-16.6},
    {"n":"Bijagos Inseln (Guinea-Bissau — Zugvogel-Überwinterung)","lat":11.25,"lng":-16.1},
    {"n":"Dzanga-Sangha (Zentralafrika — Waldvögel-Überwinterung)","lat":3.0,"lng":16.3},
    {"n":"Okavango-Delta Zugvogel (Botswana)","lat":-18.8,"lng":22.4},
    {"n":"Lake Natron (Tansania — Flamingo-Brutgebiet)","lat":-2.4,"lng":36.1},
    {"n":"Baringo-See (Kenia — 470 Vogelarten)","lat":0.7,"lng":36.1},
    {"n":"Chilika Lake (Indien — Zugvögel aus Sibirien)","lat":19.7,"lng":85.3},
    {"n":"Point Calimere (Tamil Nadu — Flamingo-Zug)","lat":10.3,"lng":79.85},
    {"n":"Sundarbans Bird Corridor (Bangladesh)","lat":22.0,"lng":89.5},
])

_m('tiere_pin.json','tiere_haustiere',[
    {"n":"Schottische Hochlandrind Domestikation (Schottland)","lat":57.3,"lng":-4.5},
    {"n":"Lama (Alpaca) Domestikation Puno (Peru)","lat":-15.85,"lng":-70.02},
    {"n":"Trampeltier Domestikation (Zentralasien, Mongolei)","lat":47.0,"lng":105.0},
    {"n":"Jak Domestikation (Tibet/Qinghai, China)","lat":33.0,"lng":92.0},
    {"n":"Hausrind Tauros-Domestikation (Anatolien, Türkei)","lat":38.0,"lng":35.0},
    {"n":"Hausziege Domestikation (Zagros-Gebirge, Iran)","lat":33.5,"lng":47.5},
    {"n":"Hausschaf Domestikation (Mesopotamien, Irak)","lat":33.0,"lng":43.0},
    {"n":"Hausesel Domestikation (Nubien/Ägypten)","lat":23.0,"lng":34.0},
    {"n":"Reindeer Domestikation (Sibirien/Russland)","lat":65.0,"lng":90.0},
    {"n":"Guanaco Wildform Domestikation (Patagonia, Chile/Argentinien)","lat":-45.0,"lng":-70.0},
    {"n":"Bactrian Camel Ursprung (Turkmenistan/Kasachstan)","lat":40.0,"lng":55.0},
    {"n":"Hauskaninchen Domestikation (Südfrankreich/Spanien, Römerzeit)","lat":43.5,"lng":4.5},
    {"n":"Ente (Anas platyrhynchos, Domestikation China)","lat":30.0,"lng":112.0},
    {"n":"Truthahn-Domestikation (Mexiko — Azteken)","lat":19.5,"lng":-99.1},
    {"n":"Graue Gans (Haushaltsgans Domestikation, Ägypten)","lat":27.0,"lng":31.0},
    {"n":"Pfau-Domestikation (Indien — Sri Lanka)","lat":12.0,"lng":79.0},
    {"n":"Regenbogenforelle Domestikation (Nordkalifornien, USA)","lat":38.0,"lng":-122.5},
    {"n":"Wellensittich Domestikation (England — 1840er)","lat":51.5,"lng":-0.1},
    {"n":"Koi-Karpfen Domestikation (Niigata, Japan)","lat":37.5,"lng":138.9},
    {"n":"Seidenspinner Bombyx mori Ursprung (China — 5000 v.Chr.)","lat":32.0,"lng":112.0},
    {"n":"Honigbiene Apis mellifera Haltung (Ägypten — 3000 v.Chr.)","lat":29.0,"lng":30.5},
    {"n":"Ferret Domestikation (Westeuropa — Römerzeit)","lat":43.0,"lng":3.0},
    {"n":"Hausratte (Rattus norvegicus) Labordomestikation (Frankreich)","lat":48.85,"lng":2.35},
    {"n":"Goldhamster Domestikation (Aleppo, Syrien — 1930)","lat":36.2,"lng":37.16},
    {"n":"Farbmaus (Mus musculus, Domestikation Japan)","lat":35.7,"lng":139.7},
    {"n":"Meerschweinchen Domestikation (Andengebiet Peru)","lat":-9.0,"lng":-75.0},
    {"n":"Chinchilla-Farm Domestikation (Chile — 1923)","lat":-33.5,"lng":-70.6},
    {"n":"Hauspferd Domestikation Botai-Kultur (Kasachstan)","lat":52.0,"lng":65.5},
    {"n":"Afrikanische Riesenschnecke — Farm (Kenia)","lat":-1.3,"lng":36.8},
    {"n":"Strauß-Farm Domestikation (Klein Karoo, Südafrika)","lat":-33.5,"lng":21.5},
])

_m('tiere_pin.json','tiere_nationaltier_pin',[
    {"n":"Bengalischer Tiger — Nationales Symbol Indien","lat":22.5,"lng":88.4},
    {"n":"Weißkopfseeadler — National Bird USA (Washington D.C.)","lat":38.9,"lng":-77.0},
    {"n":"Känguru — Nationales Symbol Australien","lat":-25.3,"lng":130.0},
    {"n":"Löwe — Symbol England (Tower of London)","lat":51.51,"lng":-0.08},
    {"n":"Gallischer Hahn — Symbol Frankreich","lat":48.85,"lng":2.35},
    {"n":"Bär — Symbol Deutschland (Berlin)","lat":52.52,"lng":13.4},
    {"n":"Adler — Symbol Mexico (Mexiko-Stadt)","lat":19.43,"lng":-99.13},
    {"n":"Stier — Symbol Spanien (Sevilla — Stierkampf)","lat":37.39,"lng":-6.0},
    {"n":"Kranich — Symbol Japan (Tsurugaoka, Kamakura)","lat":35.33,"lng":139.55},
    {"n":"Roter Drache — Symbol Wales (Cardiff)","lat":51.48,"lng":-3.18},
    {"n":"Einhorn — Symbol Schottland (Edinburgh)","lat":55.95,"lng":-3.19},
    {"n":"Kiwi — Symbol Neuseeland (Wellington)","lat":-41.28,"lng":174.78},
    {"n":"Weißer Storch — Symbol Polen (Warschau)","lat":52.23,"lng":21.01},
    {"n":"Braun-Bär — Symbol Russland (Moskau)","lat":55.75,"lng":37.62},
    {"n":"Kamel — Symbol Kasachstan (Nur-Sultan)","lat":51.18,"lng":71.45},
    {"n":"Sika-Hirsch — Symbol Japan (Nara Deer Park)","lat":34.69,"lng":135.84},
    {"n":"Pandas — Symbol China (Chengdu Panda Base)","lat":30.73,"lng":104.14},
    {"n":"Cóndor Andino — Symbol Peru (Lima)","lat":-12.05,"lng":-77.05},
    {"n":"Llama — Symbol Bolivien (La Paz)","lat":-16.5,"lng":-68.15},
    {"n":"Tapir — Symbol Malaysia (Kuala Lumpur)","lat":3.14,"lng":101.69},
    {"n":"Braunbär — Symbol Finnland (Helsinki)","lat":60.17,"lng":24.94},
    {"n":"Elch — Symbol Norwegen (Oslo)","lat":59.91,"lng":10.75},
    {"n":"Wolf — Symbol Tschechien (Prag)","lat":50.08,"lng":14.42},
    {"n":"Panther — Symbol Belgien (Brüssel)","lat":50.85,"lng":4.35},
    {"n":"Kormoran — Symbol Kiribati (Tarawa)","lat":1.33,"lng":173.0},
    {"n":"Dugong — Symbol Palau (Koror)","lat":7.34,"lng":134.48},
    {"n":"Bandicoot-Ratte — Symbol Papua-Neuguinea (Port Moresby)","lat":-9.44,"lng":147.18},
    {"n":"Gaur — Symbol Myanmar (Naypyidaw)","lat":19.76,"lng":96.08},
    {"n":"Schneeleopard — Symbol Afghanistan (Kabul)","lat":34.53,"lng":69.16},
    {"n":"Schneeleopard — Symbol Kirgisistan (Bischkek)","lat":42.87,"lng":74.59},
])

_m('tiere_pin.json','tiere_primaten',[
    {"n":"Gorilla-Bergforschungsstation Karisoke (Ruanda)","lat":-1.48,"lng":29.52},
    {"n":"Schimpansen-Forschung Gombe (Tansania, Jane Goodall)","lat":-4.67,"lng":29.64},
    {"n":"Bonobo Lokolo Rezervat (DRC)","lat":-0.9,"lng":20.6},
    {"n":"Orang-Utan Rehabilitation Bukit Lawang (Sumatra)","lat":3.55,"lng":98.12},
    {"n":"Orangutan Foundation (Tanjung Puting NP, Borneo)","lat":-2.7,"lng":111.9},
    {"n":"Makaken Affenberg (Affenberg Salem, Deutschland)","lat":47.76,"lng":9.07},
    {"n":"Affenbergkolonie Gibraltar (Rhesus-Makaken)","lat":36.14,"lng":-5.35},
    {"n":"Japanischer Makak (Schneaaffe, Jigokudani, Japan)","lat":36.73,"lng":138.47},
    {"n":"Golden Monkey (Cercopithecus kandti, Volcanoes NP)","lat":-1.47,"lng":29.5},
    {"n":"Howler Monkey Reserve (Belize Community Baboon)","lat":17.5,"lng":-88.5},
    {"n":"Spider Monkey Chiapas (Mexiko — Lacandón-Wald)","lat":16.7,"lng":-91.6},
    {"n":"Mandrill Lékédi Park (Gabun)","lat":-1.5,"lng":12.0},
    {"n":"Colobus-Kolonie Kibale Forest (Uganda)","lat":0.5,"lng":30.4},
    {"n":"Drill Monkey Afi Mountain (Nigeria)","lat":6.4,"lng":9.2},
    {"n":"Proboscis Monkey Kinabatangan River (Sabah, Malaysia)","lat":5.4,"lng":118.4},
    {"n":"Resus-Makak Tempel Swayambhunath (Kathmandu, Nepal)","lat":27.71,"lng":85.29},
    {"n":"Hanuman-Langur Jaipur (Indien — urban)","lat":26.92,"lng":75.83},
    {"n":"Bale Monkey Bale Mountains (Äthiopien)","lat":7.08,"lng":39.9},
    {"n":"Snub-nosed Monkey Qinling Mountains (Shaanxi, China)","lat":33.8,"lng":108.0},
    {"n":"Pygmy Marmoset Yaguas NP (Peru — kleinster Primat)","lat":-2.9,"lng":-72.7},
    {"n":"Sifaka Propithecus diadema (Ranomafana NP, Madagaskar)","lat":-21.26,"lng":47.38},
    {"n":"Indri (größter Lemur) Andasibe Reserve (Madagaskar)","lat":-18.93,"lng":48.41},
    {"n":"Ring-tailed Lemur Berenty Reserve (Madagaskar)","lat":-25.0,"lng":46.3},
    {"n":"Aye-Aye (Daubentonia, nachtaktiv) Mananara (Madagaskar)","lat":-16.17,"lng":49.76},
    {"n":"Tarsier Bohol (Philippinen — kleinstes Primaten-Auge)","lat":9.8,"lng":124.15},
    {"n":"Slow Loris Sumatra (Nycticebus coucang)","lat":0.5,"lng":101.5},
    {"n":"Chimpansee Taï Forest (Elfenbeinküste)","lat":5.75,"lng":-7.15},
    {"n":"Western Lowland Gorilla Lopé NP (Gabun)","lat":-0.18,"lng":11.58},
    {"n":"Celebes Crested Macaque Tangkoko (Sulawesi)","lat":1.57,"lng":125.17},
    {"n":"Hamadryas-Pavian Äthiopische Highlands","lat":11.5,"lng":39.0},
])

_m('tiere_pin.json','tiere_baeren',[
    {"n":"Grizzly Bear Yellowstone (Wyoming, USA)","lat":44.43,"lng":-110.59},
    {"n":"Polar Bear Churchill (Manitoba, Kanada)","lat":58.77,"lng":-94.17},
    {"n":"Polar Bear Svalbard (Norwegen)","lat":77.87,"lng":20.97},
    {"n":"Hokkaido Braunbär Shiretoko NP (Japan)","lat":44.3,"lng":145.1},
    {"n":"Europäischer Braunbär Bayerischer Wald (Deutschland)","lat":48.9,"lng":13.4},
    {"n":"Braunbär Transsylvanien (Rumänien — stärkste Eu-Population)","lat":45.7,"lng":25.3},
    {"n":"Andenbär Spectacled Manu NP (Peru)","lat":-13.0,"lng":-71.5},
    {"n":"Andenbär Cotopaxi NP (Ecuador)","lat":-0.68,"lng":-78.44},
    {"n":"Sun Bear Danum Valley (Sabah, Borneo)","lat":5.0,"lng":117.8},
    {"n":"Sun Bear Sepilok (Malaysia — Rehabilitation)","lat":5.87,"lng":117.93},
    {"n":"Sloth Bear Sri Lanka NP (Yala NP)","lat":6.37,"lng":81.52},
    {"n":"Sloth Bear Kanha Reserve (Indien)","lat":22.3,"lng":80.6},
    {"n":"American Black Bear Olympic NP (Washington, USA)","lat":47.9,"lng":-123.5},
    {"n":"Schwarzbär Great Smoky Mountains (USA)","lat":35.68,"lng":-83.53},
    {"n":"Polar Bear Wrangel Island (Russland — Brutkolonie)","lat":71.0,"lng":-179.5},
    {"n":"Polar Bear Franz Josef Land (Russland)","lat":81.0,"lng":50.0},
    {"n":"Kamtschatka-Braunbär Kronotsky Reserve (Russland)","lat":54.8,"lng":160.6},
    {"n":"Braunbär Asturien (Nordspanien — kantabrische Population)","lat":43.1,"lng":-6.0},
    {"n":"Slowenien Braunbär (Kocevje, zentrale Population)","lat":45.6,"lng":14.9},
    {"n":"Marsikaner Bär (Apennin, Italien — nur ~50 Individuen)","lat":41.9,"lng":13.5},
    {"n":"Himalaya-Schwarzbär (Ursus thibetanus, Nepal)","lat":27.5,"lng":85.0},
    {"n":"Grizzly Kenai Peninsula (Alaska, USA)","lat":60.0,"lng":-150.5},
    {"n":"Kodiak Bär (Kodiak Island, Alaska, USA)","lat":57.5,"lng":-153.5},
    {"n":"Polar Bear Beaufort Sea (Alaska — Eiszug)","lat":71.5,"lng":-156.0},
    {"n":"Ussuri Braunbär Sikhote-Alin Reserve (Russland)","lat":44.7,"lng":135.8},
    {"n":"Polar Bear Baffin Island (Kanada — große Kolonie)","lat":70.0,"lng":-76.0},
    {"n":"Polar Bear Foxe Basin (Kanada)","lat":67.5,"lng":-79.5},
    {"n":"Braunbär Dinaric Alps (Kroatien/Bosnien)","lat":44.5,"lng":16.5},
    {"n":"Andenbär Cofán-Bermejo Reserve (Ecuador)","lat":0.4,"lng":-77.4},
    {"n":"Braunbär Bayerische Alpen — Rückkehr 2019","lat":47.6,"lng":12.8},
])

_m('tiere_pin.json','tiere_endemisch',[
    {"n":"Komodo-Waran (Komodo Island, Indonesien)","lat":-8.57,"lng":119.47},
    {"n":"Lemure (Madagaskar — endemisch 100%)","lat":-18.9,"lng":47.5},
    {"n":"Chamäleon Parsons (Marojejy NP, Madagaskar)","lat":-14.44,"lng":49.47},
    {"n":"Seychellen-Riesenschildkröte (Aldabra-Atoll)","lat":-9.42,"lng":46.35},
    {"n":"Galápagos-Meerechse (Galápagos, Ecuador)","lat":-0.82,"lng":-90.86},
    {"n":"Galápagos-Pinguin (Fernandina, Ecuador)","lat":-0.35,"lng":-91.55},
    {"n":"Kiwi (Neuseeland — alle 5 Arten endemisch)","lat":-41.28,"lng":174.78},
    {"n":"Kakapo (Stewart Island/Rakiura, Neuseeland)","lat":-46.9,"lng":168.1},
    {"n":"Tuatara (Stephens Island, Neuseeland)","lat":-40.67,"lng":174.0},
    {"n":"Bali Starling Leucopsar rothschildi (Bali-Barat NP)","lat":-8.15,"lng":114.6},
    {"n":"Philippine Eagle (Mindanao, Philippinen)","lat":7.0,"lng":126.0},
    {"n":"Borneo Orang-Utan (Danum Valley, Malaysia)","lat":5.0,"lng":117.7},
    {"n":"Sumatra-Nashorn (Gunung Leuser NP, Sumatra)","lat":3.4,"lng":97.5},
    {"n":"Golden Lion Tamarin (Serra dos Órgãos, Brasilien)","lat":-22.4,"lng":-42.9},
    {"n":"Spix-Ara (Caatinga, Brasilien — Wiederansiedlung 2022)","lat":-10.5,"lng":-39.6},
    {"n":"Irawadi-Delfin (Mekong, Kambodscha)","lat":13.55,"lng":105.97},
    {"n":"Vaquita (Porpoise, Golf von Californien, Mexiko)","lat":31.0,"lng":-114.5},
    {"n":"Kakapo Codfish Island (Whenua Hou, Neuseeland)","lat":-46.78,"lng":167.65},
    {"n":"Sri Lanka Leopard Sinharaja (Sri Lanka)","lat":6.4,"lng":80.4},
    {"n":"Bornean Bay Cat (Sundaland, Sarawak, Malaysia)","lat":3.0,"lng":113.5},
    {"n":"Socorro Island Dove (Revillagigedo, Mexiko)","lat":18.79,"lng":-110.96},
    {"n":"New Caledonian Crow (Neukaledonien, Frankreich)","lat":-21.5,"lng":165.5},
    {"n":"Takahe (Fiordland, Neuseeland)","lat":-45.5,"lng":167.7},
    {"n":"Wombat südl. Haarnasenwombat (Epping Forest, Queensland)","lat":-24.2,"lng":141.6},
    {"n":"Quoll ostl. (Tasmanien, Australien)","lat":-42.0,"lng":146.5},
    {"n":"Platypus Murray-Darling (New South Wales, Australien)","lat":-35.0,"lng":147.5},
    {"n":"Numbat (Dryandra Woodland, Westaustralien)","lat":-32.7,"lng":117.0},
    {"n":"Hirscheber Babirusa (Sulawesi Nord, Indonesien)","lat":1.3,"lng":124.8},
    {"n":"Anoa (Bubalus depressicornis, Sulawesi)","lat":-2.0,"lng":121.0},
    {"n":"Tamaraw (Mindoro, Philippinen — kleinstes Rind)","lat":12.9,"lng":121.1},
])

_m('tiere_pin.json','pferde_rassen',[
    {"n":"Arabisches Vollblut (Naher Osten — Wüste Arabiens)","lat":24.0,"lng":45.0},
    {"n":"Englisches Vollblut (Newmarket, England)","lat":52.24,"lng":0.41},
    {"n":"Andalusier / Lusitano (Jerez de la Frontera, Spanien)","lat":36.69,"lng":-6.14},
    {"n":"Lipizzaner (Lipica, Slowenien)","lat":45.52,"lng":13.78},
    {"n":"Freiberger (Avenches, Schweiz)","lat":46.88,"lng":7.06},
    {"n":"Rheinländer Warmblut (Warendorf, NRW)","lat":51.96,"lng":7.99},
    {"n":"Trakehner (Trakehnen, Polen — ehem. Ostpreußen)","lat":54.63,"lng":22.51},
    {"n":"Hannoversches Warmblut (Hannover, Deutschland)","lat":52.37,"lng":9.73},
    {"n":"Oldenburger (Oldenburg, Deutschland)","lat":53.14,"lng":8.21},
    {"n":"Holsteiner (Elmshorn, Schleswig-Holstein)","lat":53.77,"lng":9.65},
    {"n":"Kladruber (Kladruby nad Labem, Tschechien)","lat":50.07,"lng":15.5},
    {"n":"Lippizaner (Piber, Österreich)","lat":47.08,"lng":15.13},
    {"n":"Noriker (Lungau, Salzburg, Österreich)","lat":47.13,"lng":13.72},
    {"n":"Fjordpferd (Sogne, Westnorwegen)","lat":61.22,"lng":6.86},
    {"n":"Islandpferd (Holar, Nordisland)","lat":65.84,"lng":-19.12},
    {"n":"Connemarapony (Connaught, Irland)","lat":53.52,"lng":-9.93},
    {"n":"Welsh Cob (Powys, Wales)","lat":52.53,"lng":-3.43},
    {"n":"Dartmoor Pony (Dartmoor NP, England)","lat":50.57,"lng":-3.92},
    {"n":"New Forest Pony (Hampshire, England)","lat":50.87,"lng":-1.56},
    {"n":"Exmoor Pony (Exmoor NP, Somerset)","lat":51.11,"lng":-3.67},
    {"n":"Shetland-Pony (Shetlandinseln, Schottland)","lat":60.53,"lng":-1.26},
    {"n":"Mustang (Great Basin, Nevada, USA)","lat":39.5,"lng":-116.5},
    {"n":"Appaloosa (Nez-Perce-Reservat, Idaho, USA)","lat":46.5,"lng":-116.3},
    {"n":"Paint Horse (Forth Worth, Texas, USA)","lat":32.76,"lng":-97.33},
    {"n":"Quarter Horse (Abilene, Texas, USA)","lat":32.45,"lng":-99.73},
    {"n":"Tennessee Walking Horse (Shelbyville, Tennessee)","lat":35.49,"lng":-86.46},
    {"n":"Paso Fino (Barranquilla, Kolumbien)","lat":11.01,"lng":-74.82},
    {"n":"Peruanischer Paso (Lima, Peru)","lat":-12.05,"lng":-77.05},
    {"n":"Camargue-Pferd (Saintes-Maries-de-la-Mer, Frankreich)","lat":43.45,"lng":4.43},
    {"n":"Marwari (Jodhpur, Rajasthan, Indien)","lat":26.28,"lng":73.02},
])

# ── tiere_match.json ─────────────────────────────────────────────────────────

_m('tiere_match.json','ernaehrung',[
    {"n":"Gorilla (Westlicher Flachland)","c":"Herbivor / Frungivor"},
    {"n":"Braunbär (Ursus arctos)","c":"Omnivor"},
    {"n":"Wolf (Canis lupus)","c":"Karnivor"},
    {"n":"Gepard (Acinonyx jubatus)","c":"Karnivor"},
    {"n":"Nilpferd (Hippopotamus amphibius)","c":"Herbivor (Gras)"},
    {"n":"Giraffe (Giraffa camelopardalis)","c":"Herbivor (Blätter/Zweige)"},
    {"n":"Koala (Phascolarctos cinereus)","c":"Herbivor (Eukalyptus)"},
    {"n":"Riesenameisenbär (Myrmecophaga tridactyla)","c":"Insektivor (Ameisen/Termiten)"},
    {"n":"Gürteltier (Dasypus novemcinctus)","c":"Omnivor / Insektivor"},
    {"n":"Kolibri (Trochilidae, allgemein)","c":"Nektarivor"},
    {"n":"Geier (Gyps fulvus)","c":"Aasfresser"},
    {"n":"Flamingo (Phoenicopterus roseus)","c":"Filtrierer (Algen/Kleinkrebse)"},
    {"n":"Mantarochen (Mobula birostris)","c":"Filtrierer (Plankton/Krill)"},
    {"n":"Grauwal (Eschrichtius robustus)","c":"Benthos-Filtrierer (Sediment)"},
    {"n":"Storch (Ciconia ciconia)","c":"Karnivor (Frösche/Mäuse/Fische)"},
    {"n":"Seehund (Phoca vitulina)","c":"Karnivor (Fische/Tintenfische)"},
    {"n":"Seeotter (Enhydra lutris)","c":"Karnivor (Meeresfrüchte/Seeigel)"},
    {"n":"Pelikan (Pelecanus onocrotalus)","c":"Karnivor (Fische)"},
    {"n":"Kabeljau (Gadus morhua)","c":"Karnivor (Fische/Krebse)"},
    {"n":"Nilnilbarsch (Lates niloticus)","c":"Karnivor (Apex-Fisch)"},
    {"n":"Tintenfisch (Loligo vulgaris)","c":"Karnivor (Fische/Krebse)"},
    {"n":"Schnecke (Helix pomatia)","c":"Herbivor"},
    {"n":"Koi (Cyprinus rubrofuscus domesticus)","c":"Omnivor"},
    {"n":"Elefant (Asiatisch)","c":"Herbivor (Rinde/Gras/Früchte)"},
    {"n":"Jaguar (Panthera onca)","c":"Karnivor (Apex)"},
    {"n":"Fischotter (Lutra lutra)","c":"Karnivor (Fische)"},
    {"n":"Waschbär (Procyon lotor)","c":"Omnivor"},
    {"n":"Dachs (Meles meles)","c":"Omnivor"},
    {"n":"Flughund (Pteropus vampyrus)","c":"Frungivor"},
    {"n":"Nasenbär (Nasua nasua)","c":"Omnivor"},
])

_m('tiere_match.json','tauchtiefe',[
    {"n":"Bis 2992 Meter — Säugetier-Weltrekord (Tiefsttaucher)","c":"Cuvier-Schnabelwal"},
    {"n":"Bis 2250 Meter — Tintenfischjäger Tiefstsee","c":"Pottwal"},
    {"n":"Bis 1735 Meter — Südpol-Robbe","c":"Südlicher See-Elefant"},
    {"n":"Bis 1280 Meter — Meeresschildkröten-Rekord","c":"Lederschildkröte"},
    {"n":"Bis 700 Meter — Arktis-Raubfischjäger","c":"Weddellrobbe"},
    {"n":"Bis 655 Meter — tiefster tauchender Pinguin","c":"Gentoo-Pinguin"},
    {"n":"Bis 565 Meter — Kaiserpinguin Antarktis","c":"Kaiserpinguin"},
    {"n":"Bis 500 Meter — Hai-Tiefsttaucher","c":"Weißer Hai"},
    {"n":"Bis 200 Meter — arktischer Stoßzahn-Wal","c":"Narwal"},
    {"n":"Bis 150 Meter — Karibik-Riffhai","c":"Schwarzspitzenhai"},
    {"n":"Bis 100 Meter — nordatlantischer Seevogel","c":"Papageientaucher"},
    {"n":"Bis 90 Meter — Pazifik-Meeresotter","c":"Seeotter"},
    {"n":"Bis 80 Meter — tropischer Riffhai","c":"Tigerhai"},
    {"n":"Bis 60 Meter — Tiefseemuschel-Sammler Arktis","c":"Walross"},
    {"n":"Bis 30 Meter — europäischer Küstenfischer","c":"Eisvogel (Alcedo atthis)"},
    {"n":"Bis 25 Meter — Flussdelphin Amazonas","c":"Boto / Amazonas-Delphin"},
    {"n":"Bis 20 Meter — australischer Aal-Fischter","c":"Schnabeltier"},
    {"n":"Bis 15 Meter — tropischer Haifisch-Sprinter","c":"Mako-Hai"},
    {"n":"Bis 10 Meter — Flachküsten-Fischjäger","c":"Kormoran"},
    {"n":"Bis 5 Meter — Süßwasser-Nilpferd","c":"Nilpferd"},
    {"n":"Bis 2 Meter — Bachfischer Mitteleuropa","c":"Wasseramsel (Cinclus cinclus)"},
    {"n":"Bis 1200 Meter — Schwertwal-Tieftauchgang","c":"Orca / Schwertwal"},
    {"n":"Bis 450 Meter — Blauwal-Fressgang","c":"Blauwal"},
    {"n":"Bis 300 Meter — Großer Tümmler Tieftauchgang","c":"Großer Tümmler"},
    {"n":"Bis 250 Meter — australischer Pinguin","c":"Magellan-Pinguin"},
    {"n":"Bis 120 Meter — Mittelmeer-Robbe","c":"Mönchsrobbe"},
    {"n":"Bis 50 Meter — Riffpinguin Galápagos","c":"Galápagos-Pinguin"},
    {"n":"Bis 45 Meter — tropischer Barrakuda","c":"Großer Barrakuda"},
    {"n":"Bis 35 Meter — Nordatlantik-Seelöwe Männchen","c":"Steller-Seelöwe"},
    {"n":"Bis 25 Meter — pazifischer Walroß-Kurzgang","c":"Pazifisches Walross"},
])

_m('tiere_match.json','migranten',[
    {"n":"Zugstrecke Arktis ↔ Antarktis (längste Migration aller Tiere)","c":"Küstenseeschwalbe"},
    {"n":"Zugstrecke Sibirien → Westafrika (Steppe-Wiesenvogel)","c":"Rotkehlpfeifer"},
    {"n":"Zugstrecke Alaska → Neuseeland (Küstenstrandläufer)","c":"Pfuhlschnepfe (Limosa lapponica)"},
    {"n":"Zugstrecke Alaska → Nordostbrasilien (Watvogel)","c":"Golregenpfeifer (Pluvialis dominica)"},
    {"n":"Zugstrecke Grönland → Westafrika (Schneeammer)","c":"Schneeammer (Plectrophenax nivalis)"},
    {"n":"Laichzug von Atlantik → Sargassosee (Aal)","c":"Europäischer Aal"},
    {"n":"Laichzug Pazifik → Flüsse Nordamerika","c":"Pazifischer Lachs (Chinook)"},
    {"n":"Wanderung Sahara → Sahel → Zentralafrika (Nachtvogel)","c":"Gartenrotschwanz (Phoenicurus)"},
    {"n":"Wanderung Skandinavien → Westafrika (Kleinsänger)","c":"Dorngrasmücke (Sylvia communis)"},
    {"n":"Tiefseemigration tägl. 500m auf/ab (Kleinkrebs)","c":"Arktischer Krill"},
    {"n":"Jahresmigration von Serengeti → Masai Mara (Pflanzenfresser)","c":"Weißbartgnu"},
    {"n":"Wanderung Kalahari → Okavango (Savannentier)","c":"Afrikanischer Elefant"},
    {"n":"Zugstrecke Russland → Indien (Großer Weißkopfkranich)","c":"Sibirischer Kranich"},
    {"n":"Wanderung Grönland → Azoren (Bartwal)","c":"Buckelwal"},
    {"n":"Migration Arktis → Karibik (jahreszeitl. Seevogel)","c":"Tordalk (Alca torda)"},
    {"n":"Jährliche Nahrungsmigration Mongolei → Indien","c":"Silbermöwe (überwinternde Population)"},
    {"n":"Wanderung Zentralasien ↔ Indischer Subkontinent (Großtrappe)","c":"Macqueen-Trappe"},
    {"n":"Zugstrecke Sibirien → SE-Asien (Kleinstorchart)","c":"Orientalischer Storch"},
    {"n":"Crabmigration Christmas Island (Australien) — jährl.","c":"Rote Krabbe (Gecarcoidea natalis)"},
    {"n":"Wanderung Serengeti-Ökosystem — Zebra + Gnus zusammen","c":"Steppenzebra"},
    {"n":"Zugstrecke Mongolei → Bangladesch (Wasservogel)","c":"Weißäugige Tauchente"},
    {"n":"Atlantische Überquerung im Herbst (Zugvogel)","c":"Amerikanisches Rotkehlchen"},
    {"n":"Migration NW-Australien → Papua-Neuguinea (Riff-Schildkröte)","c":"Suppenschildkröte"},
    {"n":"Wanderung Tundra → Steppen (Steppenwanderer Mammalier)","c":"Saiga-Antilope"},
    {"n":"Migrations-Rekord Eissturmvogel Nordpazifik ↔ Antarktis","c":"Wanderalbatros"},
    {"n":"Migration Mexiko ↔ Kanada (Schmetterling)","c":"Monarchfalter"},
    {"n":"Migration Nordsee ↔ Karibik (Meeresschildkröte)","c":"Unechte Karettschildkröte"},
    {"n":"Zugstrecke Baikalsee → Indischer Ozean (Wasservogel)","c":"Baikalente"},
])

_m('tiere_match.json','wuesten_spezialisten',[
    {"n":"Kangaroo Rat — kein Trinkwasser nötig (Nordamerika)","c":"Sonora-Wüste"},
    {"n":"Wüstenigel — schläft tagsüber, aktiv nachts","c":"Sahara/Arabische Wüste"},
    {"n":"Namib-Wüstenkäfer — Nebeltrinker (Stipitocapnia)","c":"Namib"},
    {"n":"Arabischer Wolf — minimalster Wasserhaushalt","c":"Arabische Wüste"},
    {"n":"Sandgecko (Stenodactylus) — temperaturregulierende Laufweise","c":"Sahara"},
    {"n":"Wüstenfuchs Fennec — Riesige Ohren zur Kühlung","c":"Sahara"},
    {"n":"Wüstenrennmaus Psammomys — salzige Halophyten","c":"Sahara/Naher Osten"},
    {"n":"Dornenteufel (Thorny Devil) — Wassertransport über Haut","c":"Australische Wüste"},
    {"n":"Rüsselratte (Macroscelides) — hitzeresistent","c":"Namib"},
    {"n":"Jerboa (Springmaus) — lange Hinterbeine für Hitze-Sprint","c":"Gobi/Sahara"},
    {"n":"Wüstenrennmaus (Meriones unguiculatus) — minimaler Harnstoff","c":"Gobi-Wüste"},
])

_m('tiere_match.json','metamorphose',[
    {"n":"Puppe im Kokon aus Seide (wirtschaftlich genutzt)","c":"Seidenspinner (Bombyx mori)"},
    {"n":"Imago entsteht nach Puppenruhe in Blütenform","c":"Orchideenmantis"},
    {"n":"Freischwimmende Miracidium-Larve → Schnecke → Cercariae","c":"Leberegel (Fasciola)"},
    {"n":"Bipinnaria-Larve → Seestern über Metamorphose","c":"Gemeiner Seestern"},
    {"n":"Nauplius → Cypris-Larve → festsitzende Seepocke","c":"Seepocke (Balanus)"},
    {"n":"Trochophora → Veliger → Erwachsene Muschel","c":"Auster (Ostrea edulis)"},
    {"n":"Ammocoete-Larve lebt 7 Jahre im Sediment","c":"Bachneunauge (Lampetra)"},
    {"n":"Leptocephala-Larve im Atlantik → Glasaal → Flussaal","c":"Europäischer Aal"},
    {"n":"Wiggler-Larve im Wasser → Puppe → blutsaugend","c":"Stechmücke (Aedes)"},
    {"n":"Raupe frisst Nesseln → Tagfalter (bunt, Mitteleuropa)","c":"Kleiner Fuchs (Aglais urticae)"},
])

_m('tiere_match.json','forscher_eponyme',[
    {"n":"Zählung von Zugvögeln mittels Lichtfallen (Radarbeo.)","c":"Peter Berthold"},
    {"n":"Taktile Kommunikation bei Honigbienen (Tanzsprache)","c":"Karl von Frisch"},
    {"n":"Prägungsexperiment Graugänse — Nachfolgebewegung","c":"Konrad Lorenz"},
    {"n":"Aggressive Territorien Rotkehlchen (Englands Gartenvogel)","c":"David Lack"},
    {"n":"Agonistisches Verhalten Kampffisch Betta splendens","c":"Niko Tinbergen"},
    {"n":"Kommunikation Schimpansen mit Zeichensprache","c":"Beatrix Gardner"},
    {"n":"Hirnstimualtionsexperiment mit Elektroden Ratten","c":"James Olds / Peter Milner"},
    {"n":"Bienen-Elektrorezeption im Bienenstock","c":"Randolf Menzel"},
    {"n":"Habituation-Lernen Seehasen (Aplysia californica)","c":"Eric Kandel"},
    {"n":"Imprinting auf Enten-Küken (Nachfolge-Lernen)","c":"Eckhard Hess"},
])

print(f'\n✅ patch_278b fertig — {_t} neue Einträge.')
