"""patch_278c — Geo Pin + HL + Match auf ≥80."""
import json,os
BASE=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA=os.path.join(BASE,'data')
_t=0
def _m(fname,key,ni,target=80):
    global _t
    fp=os.path.join(DATA,fname)
    with open(fp,'r',encoding='utf-8') as f:d=json.load(f)
    entry=d[key];items=entry['items'] if isinstance(entry,dict) and 'items' in entry else entry
    is_pin='lat' in items[0]
    if is_pin:
        seen=set((round(i['lat'],1),round(i['lng'],1)) for i in items);add=0
        for it in ni:
            if len(items)>=target:break
            k2=(round(it['lat'],1),round(it['lng'],1))
            if k2 not in seen:items.append(it);seen.add(k2);add+=1
    else:
        nf='name' if 'name' in items[0] else 'n';seen=set(i.get(nf,'') for i in items);add=0
        for it in ni:
            if len(items)>=target:break
            nm=it.get(nf,'')
            if nm and nm not in seen:items.append(it);seen.add(nm);add+=1
    with open(fp,'w',encoding='utf-8') as f:json.dump(d,f,ensure_ascii=False,indent=2)
    _t+=add;total=len(items)
    print(f'  {"✅" if total>=target else "⚠️ "+str(total)}  {fname}::{key}: +{add} → {total}')

_m('geo_pin.json','geo_rifts',[
    {"n":"Corinth-Graben (Griechenland, aktiv)","lat":38.1,"lng":22.4},
    {"n":"Nordanatolischer Bruch (Türkei, seismisch aktiv)","lat":40.8,"lng":32.0},
    {"n":"Okinawa-Trog (Japan/China, Back-Arc)","lat":27.0,"lng":127.5},
    {"n":"East Pacific Rise Hauptachse (Pazifik)","lat":-5.0,"lng":-106.0},
    {"n":"Galapagos-Rift Zone (Ecuador)","lat":0.8,"lng":-91.5},
    {"n":"Lau-Becken Back-Arc (Tonga/Fiji)","lat":-18.5,"lng":-178.0},
    {"n":"Okavango-Delta-Rift (Botswana)","lat":-19.0,"lng":22.5},
    {"n":"Luangwa-Graben (Sambia)","lat":-14.0,"lng":31.5},
    {"n":"Turkana-Graben (Kenia/Äthiopien)","lat":4.0,"lng":36.5},
    {"n":"Eyasi-Graben (Tansania)","lat":-3.5,"lng":35.0},
    {"n":"Eger-Graben (Böhmen, Tschechien)","lat":50.2,"lng":12.5},
    {"n":"Leine-Graben (Niedersachsen, Deutschland)","lat":51.5,"lng":9.7},
    {"n":"Asal-Rift (Dschibuti — tiefste Stelle Afrikas)","lat":11.55,"lng":42.45},
    {"n":"Mozambique-Küsten-Rift (Sofala)","lat":-19.5,"lng":35.5},
    {"n":"Reykjanes-Rücken (SW-Island)","lat":62.0,"lng":-24.0},
    {"n":"Mid-Atlantic Ridge Südäquator","lat":-30.0,"lng":-10.0},
    {"n":"Southeast Indian Ridge","lat":-52.0,"lng":120.0},
    {"n":"Chile Rise Spreizungszone","lat":-46.5,"lng":-78.0},
    {"n":"Ägäischer Rücken / West-Anatolien","lat":38.5,"lng":28.0},
    {"n":"Wiener Becken Rift (Österreich)","lat":48.2,"lng":16.5},
    {"n":"Rhône-Graben (Südfrankreich)","lat":43.8,"lng":4.6},
    {"n":"Death Valley Graben (Californien, USA)","lat":36.5,"lng":-116.9},
    {"n":"Taupo-Vulkanzone (Neuseeland)","lat":-38.5,"lng":175.8},
    {"n":"Lake Albert Rift (Uganda, Albertine)","lat":1.5,"lng":31.0},
    {"n":"Lake Kivu Rift (DRC/Ruanda)","lat":-2.0,"lng":29.0},
    {"n":"Ruwenzori-Graben (Uganda/DRC)","lat":0.3,"lng":29.9},
    {"n":"Mid-Atlantic Ridge Äquator","lat":2.0,"lng":-16.0},
    {"n":"Southwest Indian Ridge","lat":-45.0,"lng":30.0},
    {"n":"Bodensee-Graben (Alpenvorland)","lat":47.5,"lng":9.4},
    {"n":"Lake Tanganyika Südende (Sambia)","lat":-8.5,"lng":30.5},
    {"n":"Sambesi-Graben (Simbabwe/Mosambik)","lat":-17.0,"lng":32.0},
    {"n":"Baringo-Rift Valley (Kenia)","lat":0.7,"lng":35.9},
    {"n":"Jan Mayen Fracture Zone (Nordatlantik)","lat":71.0,"lng":-8.0},
    {"n":"Fundy-Becken Rift (Kanada, Mesozoisch)","lat":45.5,"lng":-65.0},
    {"n":"Azoren-Triple-Junction (Mittelatlantik)","lat":38.0,"lng":-26.5},
    {"n":"Scotia-Meer Rücken (Antarktis)","lat":-56.0,"lng":-30.0},
    {"n":"Agulhas-Transform (Südafrika)","lat":-38.0,"lng":15.0},
    {"n":"North Anatolian Western Extension","lat":40.0,"lng":27.0},
    {"n":"Debit-Rift (Danakil-Süd, Äthiopien)","lat":12.0,"lng":40.3},
    {"n":"Carlsberg Ridge West (Arabisches Meer)","lat":8.0,"lng":58.0},
    {"n":"Mariana-Trog Back-Arc (Westpazifik)","lat":18.0,"lng":143.5},
    {"n":"Oman Transform (Arabisch-Eurasisch)","lat":22.0,"lng":60.0},
    {"n":"Mid-Atlantic Ridge Nordabschnitt (Azoren)","lat":39.5,"lng":-30.0},
    {"n":"Ruindi Plain Rift (DRC, Westast)","lat":-0.5,"lng":29.4},
    {"n":"Marisca-Rift (Turkmenistan/Kasachstan)","lat":38.5,"lng":57.5},
])

_m('geo_pin.json','geo_fossilien_fundstaetten',[
    {"n":"Fayum Depression (Ägypten — frühe Primaten)","lat":29.3,"lng":30.53},
    {"n":"Wadi Al-Hitan (Ägypten — fossile Wale, UNESCO)","lat":29.27,"lng":30.05},
    {"n":"Monte Hermoso (Argentinien — fossile Säugetiere)","lat":-38.98,"lng":-61.3},
    {"n":"Patagonia Chubutensis (Argentinien — Riesensaurier)","lat":-43.5,"lng":-66.0},
    {"n":"Lark Quarry (Queensland, Australien — Dino-Stampede)","lat":-24.78,"lng":142.13},
    {"n":"Riversleigh (Queensland, Australien — Megafauna)","lat":-19.05,"lng":138.7},
    {"n":"Naracoorte Caves (Südaustralien — Pleistozän)","lat":-36.98,"lng":140.79},
    {"n":"Cradle of Humankind (Johannesburg, Südafrika)","lat":-26.02,"lng":27.75},
    {"n":"Langebaan Lagoon Footprints (Südafrika)","lat":-33.07,"lng":18.02},
    {"n":"Tiwi Islands (Australien — Pleistozän-Fauna)","lat":-11.5,"lng":131.0},
    {"n":"Niobrara Chalk (Kansas, USA — Kreide-Meerestiere)","lat":39.5,"lng":-99.5},
    {"n":"Wheeler Shale (Utah, USA — Trilobiten)","lat":39.05,"lng":-113.02},
    {"n":"Mazon Creek (Illinois, USA — Karbon-Fossilien)","lat":41.44,"lng":-88.05},
    {"n":"Cope's Bone Cabin Quarry (Wyoming, USA)","lat":41.5,"lng":-105.3},
    {"n":"Gobi Desert Flaming Cliffs (Mongolei — Dinosaurier-Eier)","lat":44.14,"lng":103.8},
    {"n":"Bayan Mandahu (Innere Mongolei — Saurier)","lat":41.54,"lng":107.03},
    {"n":"Paleontological Site Zigong (Sichuan, China)","lat":29.35,"lng":104.78},
    {"n":"Jehol Biota (Liaoning, China — Federn-Dinosaurier)","lat":41.0,"lng":120.5},
    {"n":"Phosphorites du Quercy (Frankreich — Eozän-Säuger)","lat":44.5,"lng":1.5},
    {"n":"Oligocene Deposits Luberon (Frankreich)","lat":43.83,"lng":5.35},
    {"n":"Eocene Geiseltal (Sachsen-Anhalt, Deutschland)","lat":51.37,"lng":11.87},
    {"n":"Neumarkt in der Oberpfalz (Bayern — Ichthyosaurus)","lat":49.28,"lng":11.47},
    {"n":"Holzmaden (Baden-Württemberg — Ichthyosaurier)","lat":48.63,"lng":9.47},
    {"n":"Joggins Fossil Cliffs (Nova Scotia, Kanada)","lat":45.7,"lng":-64.43},
    {"n":"Miguasha NP (Québec, Kanada — devonische Fische)","lat":48.1,"lng":-66.35},
    {"n":"Mistaken Point (Neufundland — Ediacara-Fauna)","lat":46.62,"lng":-53.15},
    {"n":"Dinosaur Provincial Park (Alberta, Kanada)","lat":50.76,"lng":-111.5},
    {"n":"Peace River (British Columbia — Säugetierburgen)","lat":56.24,"lng":-120.85},
    {"n":"La Venta (Kolumbien — Miozän-Riesenfauna)","lat":3.0,"lng":-75.2},
    {"n":"Huayquerian Formation (Argentinien)","lat":-38.5,"lng":-67.0},
    {"n":"Cerro Castor Formation (Feuerland — Säuger)","lat":-53.5,"lng":-68.5},
    {"n":"Araripe Basin (Ceará, Brasilien — Pterosaurier)","lat":-7.3,"lng":-40.0},
    {"n":"Santana Formation (Ceará, Brasilien)","lat":-7.0,"lng":-38.5},
    {"n":"Karoo Hauptfundort (Beaufort West, Südafrika)","lat":-32.36,"lng":22.58},
    {"n":"Karroo Großes Becken Therapsida (Südafrika)","lat":-33.0,"lng":22.0},
    {"n":"Swartkrans Cave (Südafrika — Australopithecus)","lat":-26.02,"lng":27.72},
    {"n":"Klasies River (Ostkap — früher Homo sapiens)","lat":-34.09,"lng":24.41},
    {"n":"Border Cave (KwaZulu-Natal — Homo sapiens 200ka)","lat":-27.03,"lng":31.88},
    {"n":"Blombos Cave (Südafrika — älteste Kunst)","lat":-34.42,"lng":21.22},
    {"n":"Wonderwerk Cave (Nordkap — Handaxe 1,8 Mio J)","lat":-27.85,"lng":23.55},
])

_m('geo_pin.json','geo_nationalparks_geologie',[
    {"n":"Zhangye Danxia NP (Gansu, China — Regenbogenberge)","lat":38.93,"lng":100.26},
    {"n":"Zhangjiajie NP (Hunan, China — Sandsteinpfeiler)","lat":29.32,"lng":110.43},
    {"n":"Ha Long Bay (Vietnam — Karstinseln)","lat":20.91,"lng":107.18},
    {"n":"Phang Nga Bay (Thailand — Kalkstein-Karst)","lat":8.27,"lng":98.5},
    {"n":"Palawan Underground River (Philippinen)","lat":10.18,"lng":118.93},
    {"n":"Triglav NP (Slowenien — Karstgebiet)","lat":46.38,"lng":13.87},
    {"n":"Szkocjan-Höhlen (Slowenien — UNESCO)","lat":45.66,"lng":13.99},
    {"n":"Plitvice Seen NP (Kroatien — Travertinterrassen)","lat":44.88,"lng":15.62},
    {"n":"Krka NP (Kroatien — Karstquellen)","lat":43.82,"lng":15.98},
    {"n":"Bükk NP (Ungarn — Karstlandschaft)","lat":48.0,"lng":20.4},
    {"n":"Aggtelek NP (Ungarn/Slowakei — Höhlensystem)","lat":48.47,"lng":20.5},
    {"n":"Saxon Switzerland (Sachsen, Deutschland — Sandstein)","lat":50.92,"lng":14.2},
    {"n":"Partnachklamm (Bayern — Gebirgsschlucht)","lat":47.47,"lng":11.06},
    {"n":"Berchtesgaden NP (Bayern — Alpengeologie)","lat":47.55,"lng":12.94},
    {"n":"Black Forest NP (Baden-Württemberg — Granit)","lat":48.5,"lng":8.15},
    {"n":"Sierra Nevada NP (Spanien — Hochgebirge)","lat":37.09,"lng":-3.31},
    {"n":"Ordesa y Monte Perdido NP (Spanien — Pyrenäen)","lat":42.66,"lng":-0.04},
    {"n":"Picos de Europa NP (Spanien — Kalkstein)","lat":43.18,"lng":-4.88},
    {"n":"Doñana NP (Spanien — Küstengeologie)","lat":36.97,"lng":-6.43},
    {"n":"Aiguilles Rouges (Chamonix, Frankreich)","lat":45.96,"lng":6.87},
    {"n":"Mercantour NP (Frankreich — Gletschergeologie)","lat":44.1,"lng":7.0},
    {"n":"Camargue (Frankreich — Deltalandschaft)","lat":43.52,"lng":4.65},
    {"n":"Fontainebleau Forest (Frankreich — Sandstein)","lat":48.4,"lng":2.7},
    {"n":"Dartmoor NP (England — Granitmoor)","lat":50.57,"lng":-3.92},
    {"n":"Snowdonia NP (Wales — glaziale Geologie)","lat":53.07,"lng":-3.9},
    {"n":"Lake District NP (England — glaziale Seen)","lat":54.47,"lng":-3.08},
    {"n":"Surtsey (Island — neugew. Vulkaninsel seit 1963)","lat":63.3,"lng":-20.6},
    {"n":"Thingvellir NP (Island — Riftspalte)","lat":64.26,"lng":-21.12},
    {"n":"Snæfellsjökull NP (Island — Vulkankegel)","lat":64.8,"lng":-23.8},
    {"n":"Þórsmörk Valley (Island — Gletscherschlucht)","lat":63.68,"lng":-19.52},
    {"n":"Katmai NP (Alaska — Vulkane, USA)","lat":58.5,"lng":-155.0},
    {"n":"Wrangell–St. Elias NP (Alaska — größter US-NP)","lat":61.5,"lng":-143.0},
    {"n":"Crater Lake NP (Oregon, USA — Vulkankrater)","lat":42.94,"lng":-122.1},
    {"n":"Sequoia & Kings Canyon NP (Californien)","lat":36.49,"lng":-118.55},
    {"n":"Joshua Tree NP (Californien — Felsformationen)","lat":33.87,"lng":-115.9},
    {"n":"Death Valley NP (Californien — Salzsee/Dünen)","lat":36.5,"lng":-116.9},
    {"n":"Saguaro NP (Arizona — Kaktus-Wüste)","lat":32.25,"lng":-111.08},
    {"n":"Carlsbad Caverns NP (New Mexico — Höhlensystem)","lat":32.15,"lng":-104.56},
    {"n":"Big Bend NP (Texas, USA — Chihuahua-Wüste)","lat":29.12,"lng":-103.24},
    {"n":"Guadalupe Mountains NP (Texas — Riff-Kalk)","lat":31.92,"lng":-104.87},
])

_m('geo_pin.json','geo_vulkane',[
    {"n":"Kilauea (Hawaii, USA — aktivster Vulkan der Erde)","lat":19.41,"lng":-155.29},
    {"n":"Mount Rainier (Washington, USA)","lat":46.85,"lng":-121.73},
    {"n":"Mount Baker (Washington, USA)","lat":48.78,"lng":-121.81},
    {"n":"Lassen Peak (Californien, USA)","lat":40.49,"lng":-121.5},
    {"n":"Mount Adams (Washington, USA)","lat":46.2,"lng":-121.49},
    {"n":"Nevado del Huila (Kolumbien)","lat":2.93,"lng":-76.03},
    {"n":"Reventador (Ecuador)","lat":-0.08,"lng":-77.66},
    {"n":"Tungurahua (Ecuador)","lat":-1.47,"lng":-78.44},
    {"n":"Pichincha (Ecuador)","lat":-0.17,"lng":-78.6},
    {"n":"El Misti (Peru)","lat":-16.29,"lng":-71.41},
    {"n":"Taal (Philippinen)","lat":14.01,"lng":120.99},
    {"n":"Pinatubo (Philippinen)","lat":15.14,"lng":120.35},
    {"n":"Bulusan (Philippinen)","lat":12.77,"lng":124.05},
    {"n":"Kerinci (Sumatra, Indonesien — höchster Vulkan Indonesiens)","lat":-1.7,"lng":101.26},
    {"n":"Ijen (Ost-Java, Indonesien — Schwefelsee)","lat":-8.06,"lng":114.24},
    {"n":"Batur (Bali, Indonesien)","lat":-8.24,"lng":115.37},
    {"n":"Rinjani (Lombok, Indonesien)","lat":-8.42,"lng":116.47},
    {"n":"Tambora (Sumbawa, Indonesien — 1815 größter Ausbruch)","lat":-8.24,"lng":117.99},
    {"n":"Agung (Bali, Indonesien)","lat":-8.34,"lng":115.51},
    {"n":"Ulawun (Papua-Neuguinea)","lat":-5.05,"lng":151.33},
    {"n":"Tavurvur (Rabaul, Papua-Neuguinea)","lat":-4.27,"lng":152.2},
    {"n":"Anatahan (Nördliche Marianen)","lat":16.35,"lng":145.67},
    {"n":"Sarychev (Kurileninseln, Russland)","lat":48.09,"lng":153.2},
    {"n":"Klyuchevskaya Sopka (Kamtschatka, Russland)","lat":56.06,"lng":160.64},
    {"n":"Shiveluch (Kamtschatka, Russland)","lat":56.65,"lng":161.36},
    {"n":"Avachinsky (Kamtschatka, Russland)","lat":53.26,"lng":158.83},
    {"n":"Kīlauea Iki (Hawaii, USA)","lat":19.41,"lng":-155.26},
    {"n":"Mauna Ulu (Hawaii, USA)","lat":19.39,"lng":-155.19},
    {"n":"Hekla (Island)","lat":63.98,"lng":-19.7},
    {"n":"Askja (Island)","lat":65.03,"lng":-16.75},
])

_m('geo_pin.json','geo_geothermal',[
    {"n":"Rotorua Geothermalgebiet (Neuseeland)","lat":-38.14,"lng":176.25},
    {"n":"Wai-O-Tapu (Neuseeland)","lat":-38.35,"lng":176.37},
    {"n":"Pohutu Geyser (Whakarewarewa, Neuseeland)","lat":-38.16,"lng":176.25},
    {"n":"Nesjavellir Geothermalkraftwerk (Island)","lat":64.09,"lng":-21.19},
    {"n":"Svartsengi Kraftwerk (Island — Blaue Lagune)","lat":63.87,"lng":-22.44},
    {"n":"Cerro Prieto Geothermal (Baja California, Mexiko)","lat":32.42,"lng":-115.3},
    {"n":"Salton Sea Geothermal (Californien, USA)","lat":33.2,"lng":-115.6},
    {"n":"Puna Geothermal Venture (Hawaii, USA)","lat":19.47,"lng":-154.9},
    {"n":"Larderello Geothermalkraftwerk (Toskana, Italien)","lat":43.25,"lng":10.87},
    {"n":"Bagnore Geothermal (Grosseto, Italien)","lat":42.73,"lng":11.7},
    {"n":"Momotombo Geothermal (Nicaragua)","lat":12.43,"lng":-86.54},
    {"n":"Miravalles Geothermal (Costa Rica)","lat":10.74,"lng":-85.17},
    {"n":"Tiwi Geothermal (Albay, Philippinen)","lat":13.47,"lng":123.67},
    {"n":"Makban Geothermal (Laguna, Philippinen)","lat":14.03,"lng":121.47},
    {"n":"Kamojang Geothermal (West Java, Indonesien)","lat":-7.11,"lng":107.8},
    {"n":"Dieng Plateau Geothermal (Java, Indonesien)","lat":-7.2,"lng":109.9},
    {"n":"Olkaria Geothermal (Rift Valley, Kenia)","lat":-0.9,"lng":36.28},
    {"n":"Aluto-Langano Geothermal (Äthiopien)","lat":7.77,"lng":38.78},
    {"n":"Sabalan Geothermal (Iran)","lat":38.26,"lng":47.88},
    {"n":"Paratunka Geothermal (Kamtschatka, Russland)","lat":52.98,"lng":158.74},
    {"n":"Mutnovskiy Geothermal (Kamtschatka)","lat":52.45,"lng":158.17},
    {"n":"Namafjall (Mývatn, Island)","lat":65.63,"lng":-16.82},
    {"n":"Strokkur Geyser (Geysir, Island)","lat":64.31,"lng":-20.3},
    {"n":"Kronotsky Geothermal (Kamtschatka)","lat":54.0,"lng":160.5},
    {"n":"Ohaaki Geothermal (Waikato, NZ)","lat":-38.52,"lng":176.32},
    {"n":"Wairakei Geothermal (Taupo, NZ)","lat":-38.63,"lng":176.09},
    {"n":"Kawerau Geothermal (Bay of Plenty, NZ)","lat":-38.09,"lng":176.7},
    {"n":"Ahuachapán Geothermal (El Salvador)","lat":13.92,"lng":-89.85},
    {"n":"Berlin Geothermal (Usulután, El Salvador)","lat":13.48,"lng":-88.53},
    {"n":"Kizildere Geothermal (Denizli, Türkei)","lat":37.85,"lng":28.72},
])

_m('geo_pin.json','geo_felsformationen',[
    {"n":"Antelope Canyon (Arizona, USA — Schlitzschlucht)","lat":36.86,"lng":-111.37},
    {"n":"Wave Rock (Westaustralien)","lat":-32.44,"lng":118.9},
    {"n":"The Pinnacles (Westaustralien)","lat":-30.6,"lng":115.15},
    {"n":"Twelve Apostles (Victoria, Australien)","lat":-38.66,"lng":143.1},
    {"n":"Kata Tjuta / The Olgas (Northern Territory, Australien)","lat":-25.3,"lng":130.73},
    {"n":"Bunda Cliffs (Nullarbor, Australien)","lat":-32.0,"lng":129.0},
    {"n":"Ball's Pyramid (Lord Howe Island, Australien)","lat":-31.75,"lng":159.25},
    {"n":"Moeraki Boulders (Südinsel, Neuseeland)","lat":-45.34,"lng":170.83},
    {"n":"Punakaiki Pancake Rocks (West Coast, NZ)","lat":-42.12,"lng":171.33},
    {"n":"Cathedral Cove (Coromandel, NZ)","lat":-36.83,"lng":175.77},
    {"n":"Meteora (Griechenland — Sandsteinfelsen)","lat":39.72,"lng":21.63},
    {"n":"Sagrada-Família Steinbruch Montjuïc (Barcelona)","lat":41.37,"lng":2.15},
    {"n":"Pena Palace Sintra (Portugal — Fels)","lat":38.79,"lng":-9.39},
    {"n":"Brimham Rocks (North Yorkshire, England)","lat":54.07,"lng":-1.73},
    {"n":"Fingal's Cave (Staffa, Schottland)","lat":56.43,"lng":-6.34},
    {"n":"Trolltunga (Norwegen)","lat":60.12,"lng":6.74},
    {"n":"Preikestolen (Norwegen)","lat":58.99,"lng":6.19},
    {"n":"Kjeragbolten (Rogaland, Norwegen)","lat":59.03,"lng":6.57},
    {"n":"Svartifoss (Island — Basalt)","lat":64.02,"lng":-16.97},
    {"n":"Reynisfjara (Island — Basaltsäulen)","lat":63.41,"lng":-19.04},
    {"n":"Hvitserkur (Island — Basaltfels)","lat":65.6,"lng":-20.63},
    {"n":"Drachenfels (Siebengebirge, Deutschland)","lat":50.66,"lng":7.19},
    {"n":"Externsteine (Teutoburger Wald, Deutschland)","lat":51.87,"lng":8.92},
    {"n":"Felsendom Rotenfels (Nahe, Deutschland)","lat":49.82,"lng":7.78},
    {"n":"Ayers Rock — Uluru Nahaufnahme (Australien)","lat":-25.35,"lng":131.04},
    {"n":"El Capitan (Yosemite, USA)","lat":37.73,"lng":-119.64},
    {"n":"Half Dome (Yosemite, USA)","lat":37.75,"lng":-119.53},
    {"n":"Shiprock (New Mexico, USA)","lat":36.69,"lng":-108.83},
    {"n":"Monument Valley (Utah/Arizona, USA)","lat":37.0,"lng":-110.1},
    {"n":"Chimney Rock (Nebraska, USA)","lat":41.7,"lng":-103.34},
])

_m('geo_pin.json','geo_hoehlensysteme',[
    {"n":"Sarawak Chamber (Mulu, Malaysia — größter Hohlraum)","lat":4.05,"lng":114.83},
    {"n":"Deer Cave (Mulu, Malaysia — größte Höhlenmündung)","lat":4.03,"lng":114.82},
    {"n":"Tham Luang (Chiang Rai, Thailand — Rettungsaktion 2018)","lat":20.38,"lng":99.85},
    {"n":"Son Doong (Vietnam — größte Höhle der Welt)","lat":17.45,"lng":106.28},
    {"n":"Phong Nha (Vietnam — UNESCO)","lat":17.56,"lng":106.15},
    {"n":"Waitomo Glowworm Caves (NZ)","lat":-38.26,"lng":175.1},
    {"n":"Cueva de los Cristales / Naica (Mexiko)","lat":27.85,"lng":-105.5},
    {"n":"Cueva de Villa Luz (Tabasco, Mexiko — Schwefelquelle)","lat":17.54,"lng":-92.42},
    {"n":"Actun Tunichil Muknal (Belize — Maya-Höhle)","lat":17.16,"lng":-88.85},
    {"n":"Grotte de Chauvet (Ardèche, Frankreich — 37.000 J. Malereien)","lat":44.39,"lng":4.42},
    {"n":"Grotte de Font-de-Gaume (Périgord, Frankreich)","lat":44.94,"lng":1.07},
    {"n":"Cueva de El Castillo (Cantabria, Spanien)","lat":43.36,"lng":-3.97},
    {"n":"Nerja Höhle (Málaga, Spanien)","lat":36.75,"lng":-3.85},
    {"n":"Reed Flute Cave (Guilin, China)","lat":25.29,"lng":110.27},
    {"n":"Benxi Water Cave (Liaoning, China)","lat":41.36,"lng":124.25},
    {"n":"Zhijin Cave (Guizhou, China — größte Tropfsteinhöhle Chinas)","lat":26.62,"lng":105.68},
    {"n":"Kungur Ice Cave (Ural, Russland)","lat":57.43,"lng":56.96},
    {"n":"Новоафонская (Новый Афон, Abchasien)","lat":43.08,"lng":40.82},
    {"n":"Krubera / Voronya Cave (Abchasien — tiefste Höhle Erde)","lat":43.41,"lng":40.34},
    {"n":"Veryovkina Cave (Abchasien — zweittiefste)","lat":43.43,"lng":40.34},
    {"n":"Movile Cave (Rumänien — extremophile Fauna)","lat":43.84,"lng":28.55},
    {"n":"Peștera Urșilor (Rumänien)","lat":46.56,"lng":22.67},
    {"n":"Aggtelek Baradla (Ungarn)","lat":48.47,"lng":20.5},
    {"n":"Škocjan (Slowenien — Tiefschluchthöhle, UNESCO)","lat":45.66,"lng":14.0},
    {"n":"Postojna (Slowenien)","lat":45.78,"lng":14.2},
    {"n":"Tropfsteinhöhle Laichingen (Baden-Württemberg)","lat":48.49,"lng":9.69},
    {"n":"Dechenhöhle (Sauerland, Deutschland)","lat":51.37,"lng":7.72},
    {"n":"Atta-Höhle (Attendorn, Deutschland)","lat":51.12,"lng":7.88},
    {"n":"Baumannshöhle (Harz, Deutschland)","lat":51.77,"lng":10.78},
    {"n":"Marble Arch Caves (Fermanagh, Nordirland)","lat":54.3,"lng":-7.95},
])

_m('geo_pin.json','geo_canyons',[
    {"n":"Antelope Canyon (Arizona, USA)","lat":36.86,"lng":-111.37},
    {"n":"Bryce Canyon (Utah, USA — Hoodoos)","lat":37.59,"lng":-112.19},
    {"n":"Zion Canyon (Utah, USA)","lat":37.3,"lng":-113.03},
    {"n":"Canyonlands (Utah, USA)","lat":38.2,"lng":-109.93},
    {"n":"Capitol Reef (Utah, USA — Waterpocket Fold)","lat":38.18,"lng":-111.27},
    {"n":"Palo Duro Canyon (Texas, USA — zweitgrößter)","lat":34.84,"lng":-101.7},
    {"n":"Bighorn Canyon (Wyoming/Montana, USA)","lat":45.12,"lng":-108.14},
    {"n":"Hells Canyon (Idaho, USA — tiefster in N-Amerika)","lat":45.5,"lng":-116.7},
    {"n":"Columbia River Gorge (Oregon/Washington, USA)","lat":45.7,"lng":-121.8},
    {"n":"Sumidero Canyon (Chiapas, Mexiko)","lat":16.85,"lng":-93.08},
    {"n":"Copper Canyon / Barranca del Cobre (Mexiko)","lat":27.3,"lng":-107.7},
    {"n":"Chicamocha Canyon (Kolumbien)","lat":6.66,"lng":-72.98},
    {"n":"Cauca Canyon (Kolumbien)","lat":6.5,"lng":-76.5},
    {"n":"Apurímac Canyon (Peru — tiefer als Grand Canyon)","lat":-13.7,"lng":-73.5},
    {"n":"Toachi Canyon (Ecuador)","lat":-0.4,"lng":-79.0},
    {"n":"Waimea Canyon (Kauai, Hawaii, USA)","lat":22.06,"lng":-159.66},
    {"n":"Fish River Canyon (Namibia — zweitgrößter)","lat":-27.6,"lng":17.6},
    {"n":"Gonder Gorge (Äthiopien)","lat":12.6,"lng":37.5},
    {"n":"Blue Nile Gorge (Äthiopien)","lat":10.5,"lng":38.0},
    {"n":"Blyde River Canyon (Südafrika)","lat":-24.67,"lng":30.8},
    {"n":"Wadi Rum (Jordanien)","lat":29.58,"lng":35.43},
    {"n":"Wadi Mujib (Jordanien — salziges Canyon)","lat":31.45,"lng":35.6},
    {"n":"Siq Schlucht Petra (Jordanien)","lat":30.33,"lng":35.45},
    {"n":"Gorges du Verdon (Provence, Frankreich)","lat":43.75,"lng":6.35},
    {"n":"Gorges du Tarn (Massif Central, Frankreich)","lat":44.27,"lng":3.27},
    {"n":"Vikos Gorge (Epirus, Griechenland)","lat":39.85,"lng":20.75},
    {"n":"Aareschlucht (Berner Oberland, Schweiz)","lat":46.72,"lng":8.17},
    {"n":"Partnachklamm (Garmisch, Deutschland)","lat":47.47,"lng":11.06},
    {"n":"Vintgar Gorge (Triglav, Slowenien)","lat":46.38,"lng":14.0},
    {"n":"Charyn Canyon (Kasachstan)","lat":43.36,"lng":79.07},
])

_m('geo_pin.json','geo_geysire',[
    {"n":"Old Faithful (Yellowstone, USA)","lat":44.46,"lng":-110.83},
    {"n":"Castle Geyser (Yellowstone, USA)","lat":44.46,"lng":-110.84},
    {"n":"Grand Geyser (Yellowstone, USA)","lat":44.46,"lng":-110.85},
    {"n":"Steamboat Geyser (Yellowstone, USA — aktiver Rekord)","lat":44.67,"lng":-110.7},
    {"n":"Strokkur (Geysir, Island)","lat":64.31,"lng":-20.3},
    {"n":"Geysir (Haukadalur, Island — Namensgeber)","lat":64.31,"lng":-20.3},
    {"n":"Deildartunguhver (Island — heißeste Quelle Europas)","lat":64.66,"lng":-21.42},
    {"n":"El Tatio Geysirfeld (Atacama, Chile)","lat":-22.33,"lng":-68.01},
    {"n":"Tatio Geyser High Altitude (Chile)","lat":-22.35,"lng":-68.02},
    {"n":"Puchuldiza Geysirfeld (Chile)","lat":-19.42,"lng":-68.95},
    {"n":"Pohutu Geyser (Rotorua, Neuseeland)","lat":-38.16,"lng":176.25},
    {"n":"Waimangu Geyser (Rotorua, NZ)","lat":-38.33,"lng":176.38},
    {"n":"Champagne Pool (Wai-o-Tapu, NZ)","lat":-38.35,"lng":176.37},
    {"n":"Valley of Geysers (Kamtschatka, Russland)","lat":54.43,"lng":160.13},
    {"n":"Velikan Geyser (Kamtschatka — größter Russlands)","lat":54.43,"lng":160.14},
    {"n":"Dolina Geysers (Kamtschatka, Russland)","lat":54.45,"lng":160.12},
    {"n":"Fly Geyser (Nevada, USA — bunt durch Thermophile)","lat":40.86,"lng":-119.33},
    {"n":"Soda Springs Geyser (Idaho, USA)","lat":42.66,"lng":-111.6},
    {"n":"Beowawe Geysers (Nevada, USA — geotherm. genutzt)","lat":40.58,"lng":-116.48},
    {"n":"Calistoga Old Faithful (Californien, USA)","lat":38.62,"lng":-122.58},
    {"n":"Te Puia Geothermal Park (Rotorua, NZ)","lat":-38.17,"lng":176.26},
    {"n":"Huanglong Geothermal (Sichuan, China)","lat":32.75,"lng":103.81},
    {"n":"Frying Pan Lake (Waimangu, NZ — heißester See)","lat":-38.35,"lng":176.38},
    {"n":"Hveravellir (Hochland, Island)","lat":64.87,"lng":-19.55},
    {"n":"Námafjall Hverir (Mývatn, Island)","lat":65.64,"lng":-16.82},
    {"n":"Kverkfjöll Geothermal (Island)","lat":64.67,"lng":-16.68},
    {"n":"Ggeisnir (Þórsmörk, Island)","lat":63.68,"lng":-19.52},
    {"n":"Umnak Island Geyser (Aleuten, Alaska)","lat":53.3,"lng":-168.3},
    {"n":"Brimstone Hot Springs (BC, Kanada)","lat":50.1,"lng":-122.9},
    {"n":"Geothermal Mud Pots Solfatara (Neapel, Italien)","lat":40.83,"lng":14.14},
])

_m('geo_pin.json','geo_minen_bohrungen',[
    {"n":"Supertiefe Bohrung Kola (Russland — 12,2 km)","lat":69.39,"lng":30.6},
    {"n":"TauTona Mine (Johannesburg, Südafrika — tiefstes Goldbergwerk)","lat":-26.45,"lng":26.82},
    {"n":"Mponeng Gold Mine (Südafrika — 4 km tief)","lat":-26.45,"lng":27.25},
    {"n":"Bingham Canyon Mine (Utah, USA — größter Tagebau)","lat":40.53,"lng":-112.15},
    {"n":"Chuquicamata Kupfermine (Atacama, Chile)","lat":-22.32,"lng":-68.93},
    {"n":"Escondida Kupfermine (Atacama, Chile)","lat":-24.27,"lng":-69.07},
    {"n":"Grasberg Mine (Papua, Indonesien — Gold/Kupfer)","lat":-4.06,"lng":137.12},
    {"n":"Jwaneng Diamantmine (Botswana)","lat":-24.5,"lng":24.73},
    {"n":"Argyle Diamantmine (Westaustralien)","lat":-16.7,"lng":128.39},
    {"n":"Olympic Dam Mine (Südaustralien — Uranium/Kupfer)","lat":-30.44,"lng":136.88},
    {"n":"Ok Tedi Kupfermine (Papua-Neuguinea)","lat":-5.4,"lng":141.15},
    {"n":"Kolwezi Kupfermine (DRC — Kupfergürtel)","lat":-10.72,"lng":25.47},
    {"n":"Tenke Fungurume Mine (DRC — Kobalt)","lat":-10.6,"lng":26.14},
    {"n":"Norilsk Nickelmine (Sibirien, Russland)","lat":69.34,"lng":88.2},
    {"n":"Sudbury Nickelmine (Ontario, Kanada)","lat":46.49,"lng":-81.0},
    {"n":"Erzgebirge Silberbergwerke (Freiberg, Sachsen)","lat":50.92,"lng":13.34},
    {"n":"Rammelsberg Silberbergwerk (Goslar, Deutschland)","lat":51.88,"lng":10.4},
    {"n":"Wieliczka Salzbergwerk (Polen — UNESCO)","lat":49.98,"lng":20.06},
    {"n":"Khewra Salt Mine (Pakistan)","lat":32.65,"lng":73.0},
    {"n":"Hallstatt Salzbergwerk (Österreich — ältestes)","lat":47.56,"lng":13.65},
    {"n":"Almadén Quecksilberbergwerk (Spanien)","lat":38.77,"lng":-4.84},
    {"n":"Kiruna LKAB Eisenerzmine (Schweden)","lat":67.86,"lng":20.23},
    {"n":"Mount Isa Silber/Zink-Mine (Queensland, Australien)","lat":-20.73,"lng":139.49},
    {"n":"Pima Mine (Arizona, USA — Kupfer)","lat":31.93,"lng":-111.12},
    {"n":"Kennecott Mines (Alaska, USA — hist. Kupfer)","lat":61.49,"lng":-142.9},
    {"n":"Rio Tinto Mine (Huelva, Spanien — 5000 Jahre Bergbau)","lat":37.74,"lng":-6.59},
    {"n":"Cortez Gold Mine (Nevada, USA)","lat":40.5,"lng":-116.8},
    {"n":"Coeur d'Alene Silver District (Idaho, USA)","lat":47.67,"lng":-116.37},
    {"n":"Kalgoorlie Super Pit (Westaustralien)","lat":-30.78,"lng":121.55},
    {"n":"Snap Lake Diamond Mine (NWT, Kanada)","lat":63.6,"lng":-110.88},
])

_m('geo_pin.json','geo_steilkuesten',[
    {"n":"Cliffs of Moher (Clare, Irland — 702 m hoch)","lat":53.0,"lng":-9.43},
    {"n":"White Cliffs of Dover (England)","lat":51.1,"lng":1.4},
    {"n":"Seven Sisters Cliffs (Sussex, England)","lat":50.75,"lng":0.2},
    {"n":"Étretat Kreideklippen (Normandie, Frankreich)","lat":49.71,"lng":0.2},
    {"n":"Bonifacio Steilküste (Korsika, Frankreich)","lat":41.39,"lng":9.16},
    {"n":"Svalbard Klippen (Norwegen — Arktis)","lat":78.9,"lng":12.5},
    {"n":"Hornelen (Norwegen — höchste Seeklippe Europas 863m)","lat":61.75,"lng":5.15},
    {"n":"Preikestolen (Rogaland, Norwegen — Fjord)","lat":58.99,"lng":6.19},
    {"n":"Lysebotn Klippe (Lysefjord, Norwegen)","lat":58.99,"lng":6.6},
    {"n":"Cape Foulwind (South Island, NZ)","lat":-41.75,"lng":171.43},
    {"n":"Pancake Rocks Punakaiki (West Coast, NZ)","lat":-42.12,"lng":171.33},
    {"n":"Cape Flattery (Washington, USA)","lat":48.39,"lng":-124.72},
    {"n":"Cape Perpetua (Oregon, USA)","lat":44.28,"lng":-124.11},
    {"n":"Kaanapali Cliff (Maui, Hawaii)","lat":20.93,"lng":-156.68},
    {"n":"Na Pali Coast (Kauai, Hawaii)","lat":22.17,"lng":-159.66},
    {"n":"Bunda Cliffs (Great Australian Bight)","lat":-31.9,"lng":129.5},
    {"n":"Cape Raoul (Tasmanien, Australien)","lat":-43.19,"lng":147.86},
    {"n":"Cape Pillar (Tasmanien)","lat":-43.14,"lng":147.97},
    {"n":"Ball's Pyramid Felstürme (Lord Howe, Australien)","lat":-31.75,"lng":159.25},
    {"n":"Cape St. Blaize (George, Südafrika)","lat":-34.18,"lng":22.13},
    {"n":"Cape Point Steilküste (Kapstadt, Südafrika)","lat":-34.36,"lng":18.49},
    {"n":"Cabo Girao (Madeira — höchste Seeklippe Europas 580m)","lat":32.69,"lng":-17.16},
    {"n":"Cap de Creus (Katalonien, Spanien)","lat":42.32,"lng":3.32},
    {"n":"Punta de la Mona (Andalusien, Spanien)","lat":36.73,"lng":-3.73},
    {"n":"São Lourenço Küste (Madeira)","lat":32.73,"lng":-16.69},
    {"n":"Nordkap (Norwegen)","lat":71.17,"lng":25.78},
    {"n":"Lindesnes Kap (Norwegen — südlichster Punkt)","lat":57.98,"lng":7.04},
    {"n":"Cabo da Roca (Portugal — westlichster Punkt Europas)","lat":38.78,"lng":-9.5},
    {"n":"Cabo de São Vicente (Portugal — Steilklippen)","lat":37.01,"lng":-8.99},
    {"n":"Tête de Buch (Atlantik-Dünen, Landes, Frankreich)","lat":44.71,"lng":-1.26},
])

_m('geo_pin.json','geo_wuesten',[
    {"n":"Pinnacles Desert (Westaustralien — Kalksteinsäulen)","lat":-30.6,"lng":115.15},
    {"n":"Wahiba Sands (Oman — Dünengebiet)","lat":22.5,"lng":58.5},
    {"n":"Rub' al Khali (Saudi-Arabien — größte Sandwüste)","lat":20.0,"lng":50.0},
    {"n":"Dasht-e Lut (Iran — heißester Ort Erde)","lat":30.5,"lng":58.5},
    {"n":"Dasht-e Kavir (Iran — Salzwüste)","lat":34.0,"lng":54.5},
    {"n":"Thar-Wüste (Indien/Pakistan)","lat":27.0,"lng":71.0},
    {"n":"Taklamakan (Xinjiang, China — Sandwüste)","lat":39.0,"lng":83.0},
    {"n":"Ordos-Wüste (Innere Mongolei, China)","lat":39.5,"lng":108.5},
    {"n":"Karakum-Wüste (Turkmenistan — Darvaza-Gaskrater)","lat":40.0,"lng":58.5},
    {"n":"Kyzylkum (Kasachstan/Usbekistan)","lat":42.0,"lng":64.0},
    {"n":"Registan (Grenze Pakistan/Afghanistan)","lat":29.5,"lng":64.5},
    {"n":"Kavir-Wüste (Iran)","lat":32.0,"lng":52.0},
    {"n":"Negev-Wüste (Israel)","lat":30.5,"lng":35.0},
    {"n":"Sinai-Halbinsel Wüste (Ägypten)","lat":29.5,"lng":33.5},
    {"n":"Libysche Wüste (Libyen/Ägypten)","lat":25.0,"lng":27.0},
    {"n":"Nubian Desert (Sudan)","lat":20.0,"lng":33.0},
    {"n":"Danakil Niederung (Äthiopien — trockenste Region)","lat":14.0,"lng":40.5},
    {"n":"Atacama Salzseen Salar Atacama (Chile)","lat":-23.5,"lng":-68.3},
    {"n":"Salar de Uyuni (Bolivien — größte Salzwüste)","lat":-20.13,"lng":-67.49},
    {"n":"Sechura-Wüste (Peru/Küste)","lat":-6.0,"lng":-80.5},
    {"n":"Patagonia Wüste (Argentinien)","lat":-44.0,"lng":-68.0},
    {"n":"Monte-Wüste (Argentinien — Roter Sand)","lat":-35.0,"lng":-67.0},
    {"n":"Great Victoria Desert (Australien)","lat":-29.0,"lng":128.0},
    {"n":"Great Sandy Desert (Westaustralien)","lat":-21.0,"lng":124.0},
    {"n":"Gibson Desert (Westaustralien)","lat":-24.0,"lng":124.0},
    {"n":"Simpson Desert (Queensland, Australien)","lat":-25.0,"lng":137.0},
])

_m('geo_pin.json','geo_gletscher',[
    {"n":"Khumbu-Gletscher (Nepal — Everest-Basis)","lat":27.97,"lng":86.84},
    {"n":"Ngozumpa-Gletscher (Nepal — längster Himalaya)","lat":27.95,"lng":86.7},
    {"n":"Rongbuk-Gletscher (Tibet — Nordflanke Everest)","lat":28.07,"lng":86.87},
    {"n":"Zemu-Gletscher (Sikkim, Indien)","lat":27.77,"lng":88.5},
    {"n":"Gangotri-Gletscher (Uttarakhand, Indien)","lat":30.92,"lng":79.07},
    {"n":"Siachen-Gletscher (Pakistan/Indien — längster Karakorum)","lat":35.42,"lng":77.1},
    {"n":"Biafo-Gletscher (Pakistan)","lat":35.95,"lng":75.65},
    {"n":"Hispar-Gletscher (Pakistan)","lat":36.2,"lng":74.7},
    {"n":"Baltoro-Gletscher (Pakistan — K2-Zugang)","lat":35.75,"lng":76.3},
    {"n":"Inylchek-Gletscher (Kirgisistan — größter Tian Shan)","lat":42.0,"lng":80.2},
    {"n":"Fedchenko-Gletscher (Tadschikistan — längster Pamir)","lat":38.7,"lng":72.2},
    {"n":"Mer de Glace (Chamonix, Frankreich)","lat":45.91,"lng":6.93},
    {"n":"Gorner-Gletscher (Zermatt, Schweiz)","lat":45.98,"lng":7.78},
    {"n":"Aletschgletscher (Wallis, Schweiz — größter Alpengletscher)","lat":46.5,"lng":8.07},
    {"n":"Jostedalsbreen (Norwegen — größter in Westeuropa)","lat":61.68,"lng":7.07},
    {"n":"Folgefonna (Hardanger, Norwegen)","lat":60.03,"lng":6.35},
    {"n":"Vatnajökull (Island — größter Europas)","lat":64.4,"lng":-16.8},
    {"n":"Hofsjökull (Island)","lat":64.81,"lng":-18.91},
    {"n":"Mýrdalsjökull (Island — Eyjafjallajökull)","lat":63.67,"lng":-19.17},
    {"n":"Columbia Icefield (Jasper NP, Kanada)","lat":52.17,"lng":-117.22},
    {"n":"Athabasca Glacier (Alberta, Kanada)","lat":52.18,"lng":-117.25},
    {"n":"Malaspina Gletscher (Alaska, USA)","lat":59.8,"lng":-140.6},
    {"n":"Hubbard Glacier (Alaska, USA — längster tidewater)","lat":60.0,"lng":-139.5},
    {"n":"Mendenhall Glacier (Juneau, Alaska)","lat":58.41,"lng":-134.55},
    {"n":"Matanuska Glacier (Alaska, USA)","lat":61.75,"lng":-147.75},
    {"n":"Quelccaya Ice Cap (Peru — tropischer Gletscher)","lat":-13.93,"lng":-70.83},
    {"n":"Cotapaxi Gletscherhang (Ecuador)","lat":-0.68,"lng":-78.44},
    {"n":"Fox Glacier (West Coast, Neuseeland)","lat":-43.47,"lng":170.19},
    {"n":"Franz Josef Glacier (West Coast, NZ)","lat":-43.39,"lng":170.19},
    {"n":"Mueller Glacier (Aoraki/Mount Cook, NZ)","lat":-43.63,"lng":170.18},
])

print(f'\n✅ patch_278c_geo.py fertig — {_t} Einträge.')
