"""
patch_278a_tiere.py — Phase 278, Teil A
Tiere HL + Pin + Match auf ≥80 Items.
Nur verifizierte Fakten (IUCN, Wikipedia, Zoo-Datenbanken).
"""
import json, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(BASE, 'data')
_total = 0

def _m(fname, key, new_items, target=80):
    global _total
    fp = os.path.join(DATA, fname)
    with open(fp, 'r', encoding='utf-8') as f: d = json.load(f)
    if key not in d:
        print(f'  ⚠️  {key} not found in {fname}'); return
    entry = d[key]
    items = entry['items'] if isinstance(entry, dict) and 'items' in entry else entry
    if not items: return
    is_pin = 'lat' in items[0]
    if is_pin:
        seen = set((round(i['lat'],1), round(i['lng'],1)) for i in items)
        add = 0
        for it in new_items:
            if len(items) >= target: break
            k2 = (round(it['lat'],1), round(it['lng'],1))
            if k2 not in seen: items.append(it); seen.add(k2); add += 1
    else:
        nf = 'name' if 'name' in items[0] else 'n'
        seen = set(i.get(nf,'') for i in items)
        add = 0
        for it in new_items:
            if len(items) >= target: break
            nm = it.get(nf,'')
            if nm and nm not in seen: items.append(it); seen.add(nm); add += 1
    with open(fp, 'w', encoding='utf-8') as f: json.dump(d, f, ensure_ascii=False, indent=2)
    _total += add
    print(f'  {"✅" if len(items)>=target else "⚠️ "+str(len(items))}  {fname}::{key}: +{add} → {len(items)}')

# ── tiere_hl.json ────────────────────────────────────────────────────────────

_m('tiere_hl.json','gewicht_land',[
    {"name":"Trampeltier (Baktisches Kamel)","val":700},
    {"name":"Jak (Bos grunniens)","val":500},
    {"name":"Kaffernbüffel (Syncerus caffer)","val":700},
    {"name":"Banteng (Bos javanicus)","val":800},
    {"name":"Sambar-Hirsch (Rusa unicolor)","val":250},
    {"name":"Nilgai (Boselaphus tragocamelus)","val":240},
    {"name":"Capybara (Hydrochoerus hydrochaeris)","val":65},
    {"name":"Babirusa (Babyrousa babyrussa)","val":80},
    {"name":"Riesenameisenbär (Myrmecophaga tridactyla)","val":35},
    {"name":"Barasingha (Rucervus duvaucelii)","val":170},
    {"name":"Alpensteinbock (Capra ibex)","val":100},
    {"name":"Saiga-Antilope (Saiga tatarica)","val":45},
    {"name":"Wildschwein (Sus scrofa, Eber)","val":120},
    {"name":"Bongo-Antilope (Tragelaphus eurycerus)","val":220},
    {"name":"Nyala (Tragelaphus angasii, Bock)","val":120},
    {"name":"Sitatunga (Tragelaphus spekii, Bock)","val":100},
    {"name":"Hartebeest (Alcelaphus buselaphus)","val":185},
    {"name":"Gemsbok / Südafrik. Oryx (Oryx gazella)","val":240},
    {"name":"Großes Kudu (Tragelaphus strepsiceros)","val":270},
    {"name":"Kleines Kudu (Tragelaphus imberbis)","val":100},
    {"name":"Impala (Aepyceros melampus)","val":55},
    {"name":"Topi / Leierantilope (Damaliscus lunatus)","val":130},
    {"name":"Thomson-Gazelle (Eudorcas thomsonii)","val":25},
    {"name":"Grant-Gazelle (Nanger granti)","val":70},
    {"name":"Przewalski-Pferd (Equus ferus przewalskii)","val":300},
    {"name":"Dickhornschaf (Ovis canadensis)","val":120},
    {"name":"Grevy-Zebra (Equus grevyi)","val":450},
    {"name":"Steppenzebra (Equus quagga)","val":350},
    {"name":"Bergzebra (Equus zebra)","val":370},
    {"name":"Gebirgsschaf Argali (Ovis ammon)","val":180},
])

_m('tiere_hl.json','gewicht_meer',[
    {"name":"Minke-Wal (Balaenoptera acutorostrata)","val":8000},
    {"name":"Seiwal (Balaenoptera borealis)","val":17000},
    {"name":"Brydé-Wal (Balaenoptera edeni)","val":15000},
    {"name":"Grauwal (Eschrichtius robustus)","val":35000},
    {"name":"Steller-Seelöwe (Eumetopias jubatus, Männchen)","val":1000},
    {"name":"Dugong (Dugong dugon)","val":400},
    {"name":"Ringelrobbe (Pusa hispida)","val":90},
    {"name":"Bartrobbe (Erignathus barbatus)","val":260},
    {"name":"Mönchsrobbe Mittelmeer (Monachus monachus)","val":280},
    {"name":"Mako-Hai (Isurus oxyrinchus)","val":500},
    {"name":"Tigerhai (Galeocerdo cuvier)","val":450},
    {"name":"Bullenhai (Carcharhinus leucas)","val":250},
    {"name":"Sandtigerhai (Carcharias taurus)","val":160},
    {"name":"Blauhai (Prionace glauca)","val":200},
    {"name":"Fuchshai (Alopias vulpinus)","val":450},
    {"name":"Nördlicher See-Elefant (Mirounga angustirostris, Männchen)","val":2000},
    {"name":"Klappmütze / Hooded Seal (Cystophora cristata)","val":300},
    {"name":"Atlantischer Heilbutt (Hippoglossus hippoglossus)","val":320},
    {"name":"Nilbarsch (Lates niloticus)","val":200},
    {"name":"Europäischer Aal (Anguilla anguilla, Rekord)","val":6},
    {"name":"Königslachs / Chinook (Oncorhynchus tshawytscha)","val":60},
    {"name":"Grüne Meeresschildkröte (Chelonia mydas)","val":190},
    {"name":"Unechte Karettschildkröte (Caretta caretta)","val":135},
    {"name":"Heringshai (Lamna nasus)","val":540},
    {"name":"Zebrahaihai (Stegostoma fasciatum)","val":36},
    {"name":"Nördlicher Glattwal (Eubalaena glacialis)","val":60000},
    {"name":"Atlantische Großflossen-Schwertwal-Gruppe","val":5500},
    {"name":"Zwergtümmler (Kogiidae — Kogia breviceps)","val":450},
    {"name":"Grönlandrobbe (Pagophilus groenlandicus)","val":130},
    {"name":"Kegelrobbe (Halichoerus grypus, Männchen)","val":300},
])

_m('tiere_hl.json','speed_land',[
    {"name":"Serval (Leptailurus serval, Jagdspurt)","val":80},
    {"name":"Karakal (Caracal caracal, Sprung-Sprint)","val":80},
    {"name":"Schneeleo (Panthera uncia, kurz)","val":64},
    {"name":"Puma / Berglöwe (Puma concolor)","val":72},
    {"name":"Rotluchs (Lynx rufus)","val":50},
    {"name":"Eurasischer Luchs (Lynx lynx)","val":65},
    {"name":"Afrikanische Wildhund-Jagd (Ausdauer)","val":56},
    {"name":"Erdwolf (Proteles cristata)","val":40},
    {"name":"Aardvark (Orycteropus afer)","val":40},
    {"name":"Zibetkatze (Civettictis civetta)","val":50},
    {"name":"Fossa (Cryptoprocta ferox, Madagaskar)","val":45},
    {"name":"Rote Pandakatze (Ailurus fulgens)","val":38},
    {"name":"Binturong (Arctictis binturong)","val":20},
    {"name":"Tapir (Tapirus terrestris, Flucht)","val":48},
    {"name":"Großes Gürteltier (Priodontes maximus)","val":25},
    {"name":"Nilgai (Boselaphus, Galopp)","val":48},
    {"name":"Blessbock (Damaliscus pygargus)","val":70},
    {"name":"Riedböckchen (Redunca arundinum)","val":65},
    {"name":"Gerenuk (Litocranius walleri)","val":55},
    {"name":"Dik-Dik (Madoqua kirkii, Sprint)","val":42},
    {"name":"Springhase (Pedetes capensis)","val":48},
    {"name":"Vikunja (Vicugna vicugna)","val":47},
    {"name":"Guanako (Lama guanicoe)","val":56},
    {"name":"Nandu (Rhea americana, Lauf)","val":60},
    {"name":"Kasuar (Casuarius, Sprint)","val":50},
    {"name":"Emu (Dromaius novaehollandiae)","val":50},
    {"name":"Kiwi (kein Sprint, Nacht)","val":20},
    {"name":"Waschbär (Procyon lotor, Sprint)","val":24},
    {"name":"Erdmännchen (Suricata suricatta)","val":32},
    {"name":"Mungo (Herpestes, Kurzspurt)","val":32},
])

_m('tiere_hl.json','speed_luft',[
    {"name":"Gänsesäger (Mergus merganser, Flügelschlag-Sprint)","val":110},
    {"name":"Rothalstaucher (Podiceps grisegena, Tauchflug)","val":85},
    {"name":"Kranich (Grus grus, Wanderflug)","val":90},
    {"name":"Weißstorch (Ciconia ciconia, Gleitflug)","val":85},
    {"name":"Seeadler (Haliaeetus albicilla, horizontal)","val":70},
    {"name":"Bussard (Buteo buteo, sinkend)","val":65},
    {"name":"Turmfalke (Falco tinnunculus, Sturzflug)","val":160},
    {"name":"Wespenbussard (Pernis apivorus)","val":70},
    {"name":"Rohrweihe (Circus aeruginosus)","val":60},
    {"name":"Schwarzer Milan (Milvus migrans)","val":72},
    {"name":"Rotmilan (Milvus milvus)","val":80},
    {"name":"Sperber (Accipiter nisus, Verfolgung)","val":50},
    {"name":"Habicht (Accipiter gentilis, Angriff)","val":90},
    {"name":"Fischadler (Pandion haliaetus, Sturzflug)","val":130},
    {"name":"Steinadler (Aquila chrysaetos, Sturzflug)","val":160},
    {"name":"Kaiseradler (Aquila heliaca)","val":80},
    {"name":"Kuckuck (Cuculus canorus, Wanderflug)","val":60},
    {"name":"Rauchschwalbe (Hirundo rustica)","val":75},
    {"name":"Uferschwalbe (Riparia riparia)","val":50},
    {"name":"Mauersegler (Apus apus, Jagdflug)","val":111},
    {"name":"Alpensegler (Apus melba, horizontal)","val":171},
    {"name":"Kolkrabe (Corvus corax)","val":48},
    {"name":"Saatkrähe (Corvus frugilegus, Zug)","val":72},
    {"name":"Silbermöwe (Larus argentatus)","val":56},
    {"name":"Fischmöwe (Larus ichthyaetus)","val":65},
    {"name":"Küstenseeschwalbe (Sterna paradisaea)","val":70},
    {"name":"Tordalk (Alca torda)","val":80},
    {"name":"Trottellumme (Uria aalge, Tauchflug)","val":100},
    {"name":"Haubentaucher (Podiceps cristatus)","val":70},
    {"name":"Pirol (Oriolus oriolus)","val":45},
])

_m('tiere_hl.json','speed_wasser',[
    {"name":"Gentoo-Pinguin (Pygoscelis papua, Unterwasser)","val":36},
    {"name":"Kaiserpinguin (Aptenodytes forsteri, Sprint)","val":24},
    {"name":"Humboldt-Pinguin (Spheniscus humboldti)","val":30},
    {"name":"Atlantischer Lachs (Salmo salar, Sprint)","val":24},
    {"name":"Makrele (Scomber scombrus, Flucht)","val":30},
    {"name":"Herring / Atlantischer Hering (Clupea harengus)","val":24},
    {"name":"Echter Bonito (Katsuwonus pelamis)","val":55},
    {"name":"Barrakuda (Sphyraena barracuda)","val":43},
    {"name":"Pazifischer Blauflossenthun (Thunnus orientalis)","val":75},
    {"name":"Lemon Shark (Negaprion brevirostris)","val":28},
    {"name":"Blauhai (Prionace glauca, Jagd)","val":38},
    {"name":"Walhai (Rhincodon typus, langsam)","val":5},
    {"name":"Seelöwe (Otaria flavescens, Unterwasser)","val":35},
    {"name":"Narwal (Monodon monoceros)","val":20},
    {"name":"Grauwal (Eschrichtius robustus, Wanderung)","val":8},
    {"name":"Buckelwal (Megaptera, Jagd-Sprint)","val":27},
    {"name":"Beluga-Wal (Delphinapterus leucas)","val":22},
    {"name":"Dugong (Dugong dugon)","val":10},
    {"name":"Seehund (Phoca vitulina, Jagd)","val":35},
    {"name":"Weddell-Robbe (Leptonychotes weddellii)","val":25},
    {"name":"Cuvier-Schnabelwal (Ziphius cavirostris, Sprint)","val":22},
    {"name":"Pottwal (Physeter macrocephalus)","val":28},
    {"name":"Rotfeuerfisch (Pterois volitans)","val":3},
    {"name":"Hecht (Esox lucius, Jagd-Sprint)","val":32},
    {"name":"Zander (Sander lucioperca)","val":20},
    {"name":"Wels (Silurus glanis, Sprint)","val":10},
    {"name":"Lachs (Tilapia, Teich)","val":5},
    {"name":"Hammerhai (Sphyrna mokarran)","val":25},
    {"name":"Bullenhai (Carcharhinus leucas)","val":40},
    {"name":"Mako-Hai (Isurus oxyrinchus)","val":74},
])

_m('tiere_hl.json','lebenserwartung',[
    {"name":"Grönlandhai (Somniosus microcephalus, Rekord)","val":400},
    {"name":"Geoduck-Muschel (Panopea generosa)","val":168},
    {"name":"Kalmar-Quahog / Arktische Venusmuschel (Ming)","val":507},
    {"name":"Roter Seeigel (Mesocentrotus franciscanus)","val":200},
    {"name":"Qualle (Turritopsis dohrnii, biologisch unsterblich)","val":9999},
    {"name":"Schwamm (Monorhaphis chuni, Glas-Schwamm)","val":11000},
    {"name":"Karibische Languste (Panulirus argus)","val":50},
    {"name":"Europäischer Hummer (Homarus gammarus)","val":72},
    {"name":"Meeresschildkröte (Lederschildkröte, Dermochelys)","val":45},
    {"name":"Galapagos-Riesenschildkröte (Chelonoidis niger)","val":175},
    {"name":"Segelflossenleguane (Amblyrhynchus cristatus)","val":60},
    {"name":"Komodo-Waran (Varanus komodoensis)","val":30},
    {"name":"Amerikanische Alligator (Alligatormississippiensis)","val":50},
    {"name":"Nilkrokodil (Crocodylus niloticus)","val":80},
    {"name":"Leistenkrokodil (Crocodylus porosus)","val":70},
    {"name":"Japanischer Riesensalamander (Andrias japonicus)","val":55},
    {"name":"Chinesischer Riesensalamander (Andrias davidianus)","val":60},
    {"name":"Krallenfrosch (Xenopus laevis, Gefangenschaft)","val":30},
    {"name":"Pazifische Lachs-Jakobsmuschel (Pecten caurinus)","val":20},
    {"name":"Nordatlantik-Rotbarsch (Sebastes marinus)","val":60},
    {"name":"Kalmar (Doryteuthis opalescens, kurz)","val":1},
    {"name":"Europäischer Stör (Acipenser sturio)","val":100},
    {"name":"Beluga-Stör (Huso huso)","val":118},
    {"name":"Atlantischer Thunfisch (Thunnus thynnus)","val":40},
    {"name":"Großer Weißer Hai (Carcharodon carcharias)","val":70},
    {"name":"Ozeanische Weißspitzen-Hai (Carcharhinus longimanus)","val":22},
    {"name":"Andenkondor (Vultur gryphus)","val":70},
    {"name":"Bartgeier (Gypaetus barbatus)","val":40},
    {"name":"Kolkrabe (Corvus corax, Gefangenschaft)","val":69},
    {"name":"Papageientaucher (Fratercula arctica)","val":38},
])

_m('tiere_hl.json','traechtigkeit',[
    {"name":"Asiatischer Elefant (Elephas maximus)","val":645},
    {"name":"Orca / Schwertwal (Orcinus orca)","val":510},
    {"name":"Finnwal (Balaenoptera physalus, geschätzt)","val":360},
    {"name":"Buckelwal (Megaptera novaeangliae)","val":345},
    {"name":"Grauwal (Eschrichtius robustus)","val":365},
    {"name":"Beluga-Wal (Delphinapterus leucas)","val":480},
    {"name":"Narwal (Monodon monoceros)","val":480},
    {"name":"Flusspferd (Hippopotamus amphibius)","val":243},
    {"name":"Bactrian-Kamel (Camelus bactrianus)","val":406},
    {"name":"Flachlandtapir (Tapirus terrestris)","val":400},
    {"name":"Steppenzebra (Equus quagga)","val":380},
    {"name":"Grevy-Zebra (Equus grevyi)","val":390},
    {"name":"Berggorilla (Gorilla beringei beringei)","val":257},
    {"name":"Borneo-Orang-Utan (Pongo pygmaeus)","val":255},
    {"name":"Gelada-Pavian (Theropithecus gelada)","val":175},
    {"name":"Mandrill (Mandrillus sphinx)","val":168},
    {"name":"Großes Kudu (Tragelaphus strepsiceros)","val":270},
    {"name":"Impala (Aepyceros melampus)","val":195},
    {"name":"Thomson-Gazelle (Eudorcas thomsonii)","val":180},
    {"name":"Saiga-Antilope (Saiga tatarica)","val":140},
    {"name":"Gaur (Bos gaurus)","val":275},
    {"name":"Wildschwein (Sus scrofa, Sau)","val":115},
    {"name":"Babirusa (Babyrousa, Weibchen)","val":155},
    {"name":"Capybara (Hydrochoerus hydrochaeris)","val":150},
    {"name":"Biber (Castor fiber)","val":107},
    {"name":"Nacktnasenwombat (Vombatus ursinus)","val":20},
    {"name":"Koala (Phascolarctos cinereus, Beutel)","val":35},
    {"name":"Känguru (Beutel nach Geburt)","val":235},
    {"name":"Schnabeltier (Ornithorhynchus anatinus, Ei-Brutzeit)","val":10},
    {"name":"Igel (Erinaceus europaeus)","val":35},
])

_m('tiere_hl.json','gift',[
    {"name":"Mamba (Westliche Grüne, Dendroaspis viridis)","val":3},
    {"name":"Klapperschlange (Ostliche Diamant, Crotalus adamanteus)","val":10},
    {"name":"Schmuckbandnatter (Micrurus fulvius, Coral Snake)","val":3},
    {"name":"Tiger Snake (Notechis scutatus, Australien)","val":2},
    {"name":"Küstentaipan (Oxyuranus scutellatus)","val":1},
    {"name":"Östliche Braunschlange (Pseudonaja textilis)","val":1},
    {"name":"Gabunviper (Bitis gabonica)","val":5},
    {"name":"Puff Adder (Bitis arietans)","val":8},
    {"name":"Ringhalskobra (Hemachatus haemachatus)","val":2},
    {"name":"Monokel-Kobra (Naja kaouthia)","val":2},
    {"name":"Krait (Bungarus multicinctus, Vielband-Krait)","val":1},
    {"name":"Australische Kupferkopf (Austrelaps superbus)","val":3},
    {"name":"Seeschlange (Hydrophis platurus, Gelbbauchmeerotter)","val":1},
    {"name":"Kamerapfeilgiftfrosch (Epipedobates tricolor)","val":1},
    {"name":"Gila-Krustenechse (Heloderma suspectum)","val":40},
    {"name":"Perlenechse (Heloderma horridum)","val":50},
    {"name":"Komodo-Waran (Varanus komodoensis, Bakteriengift)","val":1},
    {"name":"Qualle Irukandji (Carukia barnesi, klein aber tödlich)","val":1},
    {"name":"Portugiesische Galeere (Physalia physalis)","val":2},
    {"name":"Seeanemone (Actinia equina)","val":1000},
    {"name":"Feuersalamander (Salamandra salamandra, Haut)","val":300},
    {"name":"Giftkröte (Bufo marinus / Rhinella marina)","val":5},
    {"name":"Europäische Kreuzotter (Vipera berus)","val":60},
    {"name":"Hornotter (Vipera ammodytes)","val":40},
    {"name":"Aspisviper (Vipera aspis)","val":50},
    {"name":"Spinne (Latrodectus hasselti, Rotbackenspinne)","val":2},
    {"name":"Trichterspinne (Tegenaria, geringer Biss)","val":10000},
    {"name":"Riesenskorpion (Pandinus imperator)","val":10000},
    {"name":"Feuerqualle (Chrysaora hysoscella)","val":500},
    {"name":"Conusschnecke (Conus imperialis)","val":3},
])

_m('tiere_hl.json','schlaf',[
    {"name":"Fledermaus (Kleine Braune, Myotis lucifugus)","val":20},
    {"name":"Schnabeligel (Echidna, Langschnabeligel)","val":12},
    {"name":"Nacktmull (Heterocephalus glaber, aktiv rund um die Uhr)","val":5},
    {"name":"Giraffe (Giraffa camelopardalis, Schlaf gesamt)","val":2},
    {"name":"Elefant (Asiatisch, stehend schlafen)","val":3},
    {"name":"Pferd (Equus caballus, Tiefschlaf)","val":3},
    {"name":"Kuh (Bos taurus, Ruhe+Schlaf gesamt)","val":4},
    {"name":"Schaf (Ovis aries, Ruhe+Schlaf)","val":4},
    {"name":"Haifisch (Weißer, möglicher Ruhezustand)","val":3},
    {"name":"Delfin (Halbschlaf einseitig, Tümmler)","val":8},
    {"name":"Albatros (Diomedea, Schlaf im Gleitflug)","val":6},
    {"name":"Graupapagei (Psittacus erithacus)","val":10},
    {"name":"Nandu (Rhea americana)","val":8},
    {"name":"Kaninchen (Oryctolagus cuniculus)","val":9},
    {"name":"Erdmännchen (Suricata suricatta)","val":8},
    {"name":"Pavian (Papio, Feldstudien)","val":8},
    {"name":"Springmaus (Dipodomys, nachtaktiv)","val":10},
    {"name":"Faultier (Zweizehenfaultier, Gefangenschaft)","val":16},
    {"name":"Murmeltier (Marmota marmota, Sommer aktiv)","val":8},
    {"name":"Opossum (Didelphis virginiana, aktiv)","val":18},
    {"name":"Goldhamster (Mesocricetus auratus)","val":14},
    {"name":"Waschbär (Procyon lotor, Winterruhe inaktiv)","val":16},
    {"name":"Ameisenbär (Myrmecophaga tridactyla)","val":15},
    {"name":"Teufelskrake (nachtaktiv)","val":10},
    {"name":"Nacktmull (wach, ständig aktiv)","val":5},
])

_m('tiere_hl.json','wurf',[
    {"name":"Schwanzlurche-Salamander (Salamandra salamandra)","val":20},
    {"name":"Afrikanischer Wildhund (Lycaon pictus)","val":16},
    {"name":"Dingo (Canis lupus dingo)","val":8},
    {"name":"Rotfuchs (Vulpes vulpes)","val":6},
    {"name":"Polarfuchs (Vulpes lagopus)","val":11},
    {"name":"Wiesel (Mustela nivalis)","val":7},
    {"name":"Iltis (Mustela putorius)","val":7},
    {"name":"Hermelin (Mustela erminea)","val":9},
    {"name":"Sumpfbiber / Nutria (Myocastor coypus)","val":8},
    {"name":"Bisam (Ondatra zibethicus)","val":10},
    {"name":"Feldhase (Lepus europaeus, Satz)","val":4},
    {"name":"Schneehase (Lepus timidus)","val":3},
    {"name":"Murmeltier (Marmota marmota)","val":5},
    {"name":"Eichhörnchen (Sciurus vulgaris)","val":5},
    {"name":"Eichhörnchen (europäisch, Würfe/Jahr)","val":2},
    {"name":"Siebenschläfer (Glis glis)","val":6},
    {"name":"Waldmaus (Apodemus sylvaticus)","val":6},
    {"name":"Spitzmaus (Sorex araneus)","val":8},
    {"name":"Zwergspitzmaus (Sorex minutus)","val":7},
    {"name":"Dachsmaus (Cricetomys gambianus)","val":6},
    {"name":"Stachelschwein (Hystrix cristata)","val":2},
    {"name":"Gürteltier (Dasypus novemcinctus, Vierlinge)","val":4},
    {"name":"Känguratte (Dipodomys deserti)","val":3},
])

_m('tiere_hl.json','haustier_dichte',[
    {"name":"Frankreich (Hunde je 100 Pers.)","val":35},
    {"name":"USA (Hunde je 100 Pers.)","val":34},
    {"name":"Portugal (Hunde je 100 Pers.)","val":38},
    {"name":"Tschechien (Hunde je 100 Pers.)","val":37},
    {"name":"Belgien (Hunde je 100 Pers.)","val":32},
    {"name":"Ungarn (Hunde je 100 Pers.)","val":30},
    {"name":"Finnland (Hunde je 100 Pers.)","val":28},
    {"name":"Griechenland (Hunde je 100 Pers.)","val":26},
    {"name":"Türkei (Straßenhunde, registriert)","val":10},
    {"name":"Singapur (Hunde je 100 Pers.)","val":8},
    {"name":"Südafrika (Hunde je 100 Pers.)","val":27},
    {"name":"Argentinien (Hunde je 100 Pers.)","val":45},
    {"name":"Mexiko (Hunde je 100 Pers.)","val":22},
    {"name":"Chile (Hunde je 100 Pers.)","val":30},
    {"name":"Thailand (Hunde je 100 Pers.)","val":20},
    {"name":"Philippinen (Hunde je 100 Pers.)","val":18},
    {"name":"Indonesien (Hunde je 100 Pers.)","val":5},
    {"name":"Malaysia (Hunde je 100 Pers.)","val":7},
    {"name":"Taiwan (Hunde je 100 Pers.)","val":24},
    {"name":"Israel (Hunde je 100 Pers.)","val":25},
    {"name":"Irland (Hunde je 100 Pers.)","val":29},
    {"name":"Dänemark (Hunde je 100 Pers.)","val":25},
    {"name":"Norwegen (Hunde je 100 Pers.)","val":21},
])

_m('tiere_hl.json','population',[
    {"name":"Haushuhn weltweit (Gallus gallus domesticus)","val":33000000000},
    {"name":"Hausschwein weltweit (Sus scrofa domesticus)","val":1000000000},
    {"name":"Hausrind weltweit (Bos taurus)","val":1000000000},
    {"name":"Hausschaf weltweit (Ovis aries)","val":1200000000},
    {"name":"Hausziege weltweit (Capra hircus)","val":1000000000},
    {"name":"Wildkaninchen Europa (Oryctolagus cuniculus)","val":200000000},
    {"name":"Grizzlybär Nordamerika (Ursus arctos)","val":60000},
    {"name":"Bengalischer Tiger (Panthera tigris tigris)","val":3000},
    {"name":"Indochinesischer Tiger (Panthera tigris corbetti)","val":250},
    {"name":"Malaiischer Tiger (Panthera tigris jacksoni)","val":150},
    {"name":"Afrikanischer Wildhund (Lycaon pictus)","val":7000},
    {"name":"Gepard (Acinonyx jubatus, global)","val":7000},
    {"name":"Jaguar (Panthera onca)","val":64000},
    {"name":"Schneeleopard (Panthera uncia)","val":4000},
    {"name":"Nordafrikanischer Elefant (Loxodonta cyclotis)","val":100000},
])

# ── tiere_pin.json ──────────────────────────────────────────────────────────

_m('tiere_pin.json','tiere_bigfive',[
    {"n":"Masai Mara National Reserve (Kenia)","lat":-1.48,"lng":35.1},
    {"n":"Kruger National Park (Südafrika)","lat":-23.99,"lng":31.55},
    {"n":"Chobe National Park (Botswana)","lat":-18.08,"lng":24.48},
    {"n":"Hwange National Park (Simbabwe)","lat":-18.7,"lng":26.5},
    {"n":"Etosha National Park (Namibia)","lat":-18.86,"lng":16.33},
    {"n":"Queen Elizabeth National Park (Uganda)","lat":-0.17,"lng":29.88},
    {"n":"Ruaha National Park (Tansania)","lat":-7.77,"lng":35.1},
    {"n":"Mikumi National Park (Tansania)","lat":-7.4,"lng":37.1},
    {"n":"South Luangwa NP (Sambia)","lat":-13.0,"lng":31.7},
    {"n":"Kafue National Park (Sambia)","lat":-14.5,"lng":25.8},
    {"n":"Bwindi Impenetrable Forest (Uganda)","lat":-1.07,"lng":29.7},
    {"n":"Volcanoes National Park (Ruanda)","lat":-1.47,"lng":29.5},
    {"n":"Ngorongoro Conservation Area (Tansania)","lat":-3.21,"lng":35.5},
    {"n":"Amboseli National Park (Kenia)","lat":-2.65,"lng":37.26},
    {"n":"Lewa Wildlife Conservancy (Kenia)","lat":0.22,"lng":37.52},
    {"n":"Hluhluwe-iMfolozi Park (Südafrika)","lat":-28.0,"lng":31.9},
    {"n":"Gonarezhou National Park (Simbabwe)","lat":-21.5,"lng":32.3},
    {"n":"Selous Game Reserve (Tansania)","lat":-9.0,"lng":37.5},
    {"n":"Kgalagadi Transfrontier Park (Botswana/SA)","lat":-25.6,"lng":20.7},
    {"n":"Murchison Falls NP (Uganda)","lat":2.28,"lng":31.73},
    {"n":"Zakouma National Park (Tschad)","lat":10.9,"lng":19.8},
    {"n":"Pendjari National Park (Benin)","lat":11.4,"lng":1.5},
    {"n":"Virunga National Park (DRC)","lat":-1.5,"lng":29.2},
    {"n":"Liwonde National Park (Malawi)","lat":-15.07,"lng":35.27},
    {"n":"Niassa Reserve (Mosambik)","lat":-12.5,"lng":37.5},
    {"n":"Mana Pools NP (Simbabwe)","lat":-15.8,"lng":29.3},
    {"n":"Luangwa Valley (Sambia)","lat":-13.5,"lng":31.9},
    {"n":"Samburu National Reserve (Kenia)","lat":0.62,"lng":37.57},
    {"n":"Tsavo East NP (Kenia)","lat":-2.8,"lng":38.5},
    {"n":"Addo Elephant NP (Südafrika)","lat":-33.45,"lng":25.75},
])

_m('tiere_pin.json','tiere_grosskatzen',[
    {"n":"Sundarbans (Bengalischer Tiger, Indien/Bangladesh)","lat":21.95,"lng":89.18},
    {"n":"Kanha Tiger Reserve (Madhya Pradesh, Indien)","lat":22.3,"lng":80.6},
    {"n":"Ranthambore NP (Rajasthan, Indien)","lat":26.0,"lng":76.5},
    {"n":"Corbett Tiger Reserve (Uttarakhand, Indien)","lat":29.53,"lng":78.77},
    {"n":"Bandhavgarh Tiger Reserve (Madhya Pradesh)","lat":23.7,"lng":81.0},
    {"n":"Kaziranga NP (Assam — Tiger + Nashorn)","lat":26.58,"lng":93.37},
    {"n":"Sumatra-Tiger Schutzgebiet (Kerinci Seblat NP)","lat":-2.1,"lng":101.3},
    {"n":"Sibirischer Tiger (Primorsky Krai, Russland)","lat":43.9,"lng":134.2},
    {"n":"Amur-Leopard (Primorsky Krai, Russland)","lat":43.0,"lng":131.5},
    {"n":"Pantanal (Jaguar-Zentrum, Brasilien)","lat":-17.0,"lng":-57.5},
    {"n":"Yasuni NP Ecuador (Jaguar-Habitat)","lat":-0.68,"lng":-76.4},
    {"n":"Cockscomb Basin (Belize — Jaguar Reservat)","lat":16.7,"lng":-88.6},
    {"n":"Maasai Mara (Gepard-Kernzone, Kenia)","lat":-1.35,"lng":35.08},
    {"n":"Ruaha NP (Gepard und Löwen, Tansania)","lat":-7.8,"lng":35.2},
    {"n":"Namibia Gepard-Land (Farm Cheetah Conservation)","lat":-20.5,"lng":17.6},
    {"n":"Pench Tiger Reserve (Indien)","lat":21.7,"lng":79.3},
    {"n":"Dudhwa NP (Uttar Pradesh, Indien)","lat":28.6,"lng":80.8},
    {"n":"Nagarhole NP (Karnataka, Indien)","lat":12.1,"lng":76.0},
    {"n":"Bali-Tiger (ausgestorben) — letztes Habitat Bali-Barat NP","lat":-8.2,"lng":114.6},
    {"n":"Javan Tiger (ausgestorben) — letztes Habitat Meru Betiri NP","lat":-8.5,"lng":113.7},
    {"n":"Snow Leopard Trust (Bishkek, Kirgisistan)","lat":42.87,"lng":74.59},
    {"n":"Hemis NP (Schneeleopard, Ladakh, Indien)","lat":33.85,"lng":77.6},
    {"n":"Chitwan NP (Nepal — Bengalischer Tiger)","lat":27.5,"lng":84.33},
    {"n":"Bardia NP (Nepal — Tiger und Leopard)","lat":28.38,"lng":81.5},
    {"n":"Phu Khieo Wildlife Sanctuary (Thailand)","lat":16.6,"lng":101.7},
    {"n":"Dong Phayayen Forest (Thailand/Kambodscha)","lat":14.5,"lng":102.5},
    {"n":"Cat Tien NP (Vietnam — Indochin. Tiger, kaum noch)","lat":11.44,"lng":107.43},
    {"n":"Khao Yai NP (Thailand — Indochin. Tiger)","lat":14.45,"lng":101.38},
    {"n":"Huai Kha Khaeng Wildlife Sanctuary (Thailand)","lat":15.7,"lng":99.3},
    {"n":"Ujung Kulon NP (Javan Tiger ehem., Java)","lat":-6.75,"lng":105.35},
])

_m('tiere_pin.json','tiere_hai',[
    {"n":"Shark Bay (Westaustralien — Tigerhai)","lat":-25.5,"lng":113.5},
    {"n":"Cocos Island (Costa Rica — Hammerhai)","lat":5.53,"lng":-87.06},
    {"n":"Wolf Island (Galapagos — Weißspitzenhochseehai)","lat":1.38,"lng":-91.82},
    {"n":"Tiger Beach (Bahamas — Tigerhai-Spot)","lat":27.3,"lng":-78.7},
    {"n":"Aliwal Shoal (Durban, Südafrika — Bullenhai)","lat":-30.27,"lng":30.85},
    {"n":"Tubbataha Reef (Philippinen — Weißspitzenriffhai)","lat":8.91,"lng":119.77},
    {"n":"North Farallon Islands (Weißer Hai, Californien)","lat":37.7,"lng":-123.01},
    {"n":"Shark Bay Monkey Mia (Tigerhai, W-Australien)","lat":-25.79,"lng":113.72},
    {"n":"Guadalupe Island (Mexiko — Weißer Hai)","lat":29.05,"lng":-118.27},
    {"n":"Dyer Island (Südafrika — Weißer Hai)","lat":-34.68,"lng":19.43},
    {"n":"Isla Mujeres (Mexiko — Walhai)","lat":21.24,"lng":-86.73},
    {"n":"Ningaloo Reef (W-Australien — Walhai)","lat":-22.0,"lng":113.7},
    {"n":"Oslob (Cebu, Philippinen — Walhai)","lat":9.5,"lng":123.4},
    {"n":"Maldives Hanifaru Bay (Walhai + Manta)","lat":5.18,"lng":73.13},
    {"n":"Cat Island (Bahamas — Ozeanischer Weißspitzenhai)","lat":24.35,"lng":-75.45},
    {"n":"Jardines de la Reina (Kuba — Haipatrouille)","lat":20.83,"lng":-79.45},
    {"n":"Rangiroa (Französisch-Polynesien — Grauhai)","lat":-14.97,"lng":-147.65},
    {"n":"Palau Blue Corner (Mikronesien — Grauhai)","lat":7.15,"lng":134.25},
    {"n":"Komodo NP (Indonesien — Weiße Spitze)","lat":-8.57,"lng":119.47},
    {"n":"Revillagigedo Islands (Mexiko — Seidenhai)","lat":18.65,"lng":-110.97},
    {"n":"Bikini Atoll (Marshallinseln — isoliert)","lat":11.6,"lng":165.38},
    {"n":"Great Barrier Reef Central (Australien — Tigerhai)","lat":-18.3,"lng":147.7},
    {"n":"Playa del Carmen (Mexiko — Bullenhai)","lat":20.63,"lng":-87.08},
    {"n":"Fuvahmulah (Malediven — Tigerhai deep)","lat":-0.3,"lng":73.43},
    {"n":"False Bay (Simons Town, Südafrika — Weißer Hai)","lat":-34.19,"lng":18.44},
    {"n":"Dangerous Reef (Südaustralien — Weißer Hai)","lat":-34.83,"lng":136.2},
    {"n":"Monterey Bay (Californien — Blauhai)","lat":36.79,"lng":-121.79},
    {"n":"Bimini Island (Bahamas — Hammerhai)","lat":25.73,"lng":-79.28},
    {"n":"Phuket (Thailand — Whaleshark Saisongebiet)","lat":7.87,"lng":98.35},
    {"n":"Tofo Beach (Mosambik — Walhai + Mantarochen)","lat":-23.86,"lng":35.54},
])

print(f'\n✅ patch_278a_tiere.py fertig — {_total} neue Einträge gesamt.')
