# -*- coding: utf-8 -*-
"""
Phase: 291
Scope: Englisch fuer die 5 Rubriken (emob/arch/astro/geo/sport) — Prompts + Einheiten + fixedOpts

Fuellt _CONTENT_I18N.en mit den englischen Entsprechungen der 329 deutschen
Strings, die in Phase 288 bereits auf Polnisch uebersetzt wurden.
Mechanismus unveraendert (_tc); nur Datenergaenzung.
Validierung: jeder dt. Schluessel muss bereits in _CONTENT_I18N.pl existieren.
Dependencies: patch_290_beta_i18n.py
"""
import os, json, re

GEN = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'gen.py')
content = open(GEN, encoding='utf-8').read()

PROMPTS_EN = {
"Auf welchem Kontinent wurde diese Sportart erfunden / ist am populaersten?": "On which continent was this sport invented / is it most popular?",
"Auf welcher Fahrzeugplattform basiert dieses EV-Modell?": "Which vehicle platform is this EV model based on?",
"Auf welcher Technologie basiert dieser Elektromotortyp?": "Which technology is this electric motor type based on?",
"Auf welcher tektonischen Hauptplatte liegt dieser Kontinent / diese Region?": "On which major tectonic plate does this continent / region lie?",
"Auf welcher tektonischen Platte liegt dieses Land hauptsaechlich?": "On which tectonic plate does this country mainly lie?",
"Aus welchem Land kommt diese Sportlegende?": "Which country does this sports legend come from?",
"Aus welchem Land stammt dieses EV-Startup?": "Which country is this EV startup from?",
"Aus welcher Zeit stammt dieses Werkzeug?": "From which era does this tool date?",
"Bei welchem Fahrzeug dauert das Laden von 10% auf 80% kürzer?": "For which vehicle is charging from 10% to 80% faster?",
"Diese Stadt hat eine der höchsten EV-Dichten weltweit — wo liegt sie?": "This city has one of the highest EV densities worldwide — where is it?",
"Durch welchen Prozess entstand dieses Naturwunder hauptsächlich?": "By which process did this natural wonder mainly form?",
"Durch welchen tektonischen Prozess entstand dieses Gebirge?": "By which tectonic process did this mountain range form?",
"Für welche Anwendung ist diese 3D-Methode am besten?": "For which application is this 3D method best suited?",
"Für welche Entdeckung oder welches Gesetz ist dieser Astronom bekannt?": "For which discovery or law is this astronomer known?",
"In welche Kategorie fällt der Anteil erneuerbarer Energien in diesem Land?": "Into which category does this country's share of renewable energy fall?",
"In welchem Erdzeitalter lebte dieses Wesen?": "In which geological era did this creature live?",
"In welchem Grab wurden mehr Beigaben gefunden?": "In which tomb were more grave goods found?",
"In welchem Jahr ereignete sich dieses historische Erdbeben?": "In which year did this historic earthquake occur?",
"In welchem Land fand diese Fussball-WM statt?": "In which country did this football World Cup take place?",
"In welchem Land gilt diese EV-Fördermaßnahme?": "In which country does this EV subsidy apply?",
"In welchem Land gilt dieses EV-Privileg?": "In which country does this EV privilege apply?",
"In welchem Land liegt dieser Vulkan?": "In which country is this volcano?",
"In welchem Land liegt dieses Höhlensystem?": "In which country is this cave system?",
"In welchem Land oder Region wurde diese Sportart entwickelt?": "In which country or region was this sport developed?",
"In welchem modernen Land liegt diese Indus-Tal-Stätte?": "In which modern country is this Indus Valley site?",
"In welcher Stadt fanden diese Olympischen Sommerspiele statt?": "In which city did these Summer Olympics take place?",
"In welcher Stadt findet dieser Formel-E-ePrix statt?": "In which city is this Formula E ePrix held?",
"In welcher Stadt wird diese berühmte Sammlung aufbewahrt?": "In which city is this famous collection kept?",
"Ist diese Sportart bei den Olympischen Spielen vertreten?": "Is this sport represented at the Olympic Games?",
"Mit welchem Partner/Protokoll kann dieses Ladenetzwerk Roaming?": "With which partner/protocol can this charging network roam?",
"Von welchem Hersteller stammt dieses EV-Konzeptfahrzeug?": "Which manufacturer is this EV concept car from?",
"Was bedeutet diese EV-Warnanzeige im Armaturenbrett?": "What does this EV warning indicator on the dashboard mean?",
"Was behauptete diese berühmte Fälschung zu sein?": "What did this famous forgery claim to be?",
"Was erkennt diese archäologische Surveymethode?": "What does this archaeological survey method detect?",
"Was schreibt die AVAS-Vorschrift für dieses Szenario vor?": "What does the AVAS regulation prescribe for this scenario?",
"Was verrät diese Isotopenanalyse?": "What does this isotope analysis reveal?",
"Welche Antriebsart nutzt diese Rakete oder Raumsonde?": "Which type of propulsion does this rocket or space probe use?",
"Welche Bedrohung gefährdet diese UNESCO-Welterbestätte?": "Which threat endangers this UNESCO World Heritage site?",
"Welche Beschreibung passt zu diesem astronomischen Objekt?": "Which description fits this astronomical object?",
"Welche Bohrung / Mine reicht tiefer?": "Which borehole / mine goes deeper?",
"Welche Datierungsmethode ist hier am besten geeignet?": "Which dating method is best suited here?",
"Welche Eigenschaft beschreibt diesen Planeten am besten?": "Which property best describes this planet?",
"Welche Entdeckung ist jünger?": "Which discovery is more recent?",
"Welche Epoche deckt dieses Digitalprojekt ab?": "Which era does this digital project cover?",
"Welche Funktion übernimmt diese TMS-Komponente?": "Which function does this TMS component perform?",
"Welche Information liefert dieser Pflanzenfund in der Archäologie?": "What information does this plant find provide in archaeology?",
"Welche Platte driftet schneller?": "Which plate drifts faster?",
"Welche Rakete transportiert mehr Nutzlast in die Erdumlaufbahn (LEO)?": "Which rocket carries more payload to low Earth orbit (LEO)?",
"Welche Raumsonde / welches Teleskop war länger im Betrieb?": "Which space probe / telescope operated longer?",
"Welche Ruinenanlage ist größer?": "Which ruin complex is larger?",
"Welche Schlucht ist tiefer?": "Which gorge is deeper?",
"Welche V2X-Technologie beschreibt diese Netzinteraktion?": "Which V2X technology describes this grid interaction?",
"Welche Verhaltensregel beschreibt diese Ladesituation?": "Which rule of conduct describes this charging situation?",
"Welche charakteristische Farbe hat dieses Mineral?": "What characteristic colour does this mineral have?",
"Welchem Galaxientyp gehört diese Galaxie an?": "Which galaxy type does this galaxy belong to?",
"Welchem Kristallsystem gehört dieses Mineral an?": "Which crystal system does this mineral belong to?",
"Welchem Ladestandard entspricht dieser Steckertyp?": "Which charging standard does this connector type correspond to?",
"Welchem SAE-Autonomiegrad entspricht diese Funktion?": "Which SAE autonomy level does this function correspond to?",
"Welchem Weltverband gehoert diese Sportart an?": "Which world federation does this sport belong to?",
"Welchen Vorteil bietet dieses EV-spezifische Reifenmerkmal?": "What advantage does this EV-specific tyre feature offer?",
"Welcher Berg ist hoeher?": "Which mountain is higher?",
"Welcher Epoche gehört dieses Artefakt an?": "Which era does this artefact belong to?",
"Welcher Exoplanet ist weiter von der Erde entfernt?": "Which exoplanet is farther from Earth?",
"Welcher Faktor reduziert die EV-Reichweite auf diese Weise?": "Which factor reduces EV range in this way?",
"Welcher Fund liegt tiefer?": "Which find lies deeper?",
"Welcher Himmelskörper hat die stärkere Oberflächengravitation?": "Which celestial body has the stronger surface gravity?",
"Welcher Kultur entstammt diese Schrift?": "Which culture does this script originate from?",
"Welcher Kultur gehört diese astronomische Stätte oder Beobachtung?": "Which culture does this astronomical site or observation belong to?",
"Welcher Kultur gehört dieser Bestattungsritus an?": "Which culture does this burial rite belong to?",
"Welcher Kultur gehört dieser Keramikstil an?": "Which culture does this pottery style belong to?",
"Welcher Ladekorridore / EV-Roadtrip-Route führt durch diesen Ort?": "Which charging corridor / EV road-trip route passes through this place?",
"Welcher Marathon hat eine laengere Geschichte?": "Which marathon has a longer history?",
"Welcher Megalith ist schwerer?": "Which megalith is heavier?",
"Welcher Planet hat den groesseren Durchmesser?": "Which planet has the larger diameter?",
"Welcher Planet hat mehr bekannte Monde?": "Which planet has more known moons?",
"Welcher Planet ist durchschnittlich heißer (Oberflächentemperatur)?": "Which planet is hotter on average (surface temperature)?",
"Welcher Prozess hat diese Landschaftsform erschaffen?": "Which process created this landform?",
"Welcher Transfer war teurer?": "Which transfer was more expensive?",
"Welcher Tsunami war höher?": "Which tsunami was higher?",
"Welcher Vorteil ist typisch für diese Batteriezellchemie?": "Which advantage is typical of this battery cell chemistry?",
"Welcher Vulkan hat den hoeheren Gipfel?": "Which volcano has the higher summit?",
"Welcher Vulkanausbruch war explosiver (VEI)?": "Which volcanic eruption was more explosive (VEI)?",
"Welcher Zivilisation gehört diese Münze?": "Which civilisation does this coin belong to?",
"Welcher Zivilisation gehörte diese Währung?": "Which civilisation did this currency belong to?",
"Welcher antiken Kultur entstammt diese medizinische Praxis?": "Which ancient culture does this medical practice originate from?",
"Welcher griechischen Ordnung gehört dieser Tempel an?": "Which Greek order does this temple belong to?",
"Welches 3D-Scan-Projekt hat mehr Datenmenge?": "Which 3D scan project has more data?",
"Welches Artefakt hat einen höheren Schätzwert?": "Which artefact has a higher estimated value?",
"Welches Artefakt ist älter?": "Which artefact is older?",
"Welches Eisvorkommen hat größeres Volumen?": "Which ice deposit has greater volume?",
"Welches Elektroauto beschleunigt schneller von 0 auf 100 km/h?": "Which electric car accelerates faster from 0 to 100 km/h?",
"Welches Elektroauto hat eine größere Batteriekapazität?": "Which electric car has a larger battery capacity?",
"Welches Elektroauto hat eine größere WLTP-Reichweite?": "Which electric car has a greater WLTP range?",
"Welches Elektroauto hat mehr Systemdrehmoment?": "Which electric car has more system torque?",
"Welches Elektroauto ist schwerer?": "Which electric car is heavier?",
"Welches Elektroauto ist teurer (Basispreis)?": "Which electric car is more expensive (base price)?",
"Welches Elektroauto lädt mit höherer Maximalleistung?": "Which electric car charges at a higher maximum power?",
"Welches Erdbeben hatte die groessere Magnitude?": "Which earthquake had the greater magnitude?",
"Welches Fahrzeug arbeitet mit einer höheren Systemspannung?": "Which vehicle operates at a higher system voltage?",
"Welches Fahrzeug hat einen niedrigeren Luftwiderstandsbeiwert (cw)?": "Which vehicle has a lower drag coefficient (Cd)?",
"Welches Fahrzeug hat mehr Batteriezellen?": "Which vehicle has more battery cells?",
"Welches Fahrzeug hat mehr Ladeanschlüsse (AC + DC kombiniert)?": "Which vehicle has more charging ports (AC + DC combined)?",
"Welches Fahrzeug zeigt dieses typische Ladeverhalten?": "Which vehicle shows this typical charging behaviour?",
"Welches Gestein / welche Gesteinsformation ist älter?": "Which rock / rock formation is older?",
"Welches Höhlensystem ist länger?": "Which cave system is longer?",
"Welches Land fordert dieses Artefakt zurück?": "Which country is demanding this artefact back?",
"Welches Land hat diesen Sport als inoffiziellen Nationalsport?": "Which country has this sport as its unofficial national sport?",
"Welches Material hat einen höheren Schmelzpunkt?": "Which material has a higher melting point?",
"Welches Mineral ist härter (Mohs-Skala)?": "Which mineral is harder (Mohs scale)?",
"Welches Objekt ist laut C14-Datierung älter?": "Which object is older according to C14 dating?",
"Welches Objekt ist weiter von der Sonne entfernt?": "Which object is farther from the Sun?",
"Welches Objekt wurde früher entdeckt?": "Which object was discovered earlier?",
"Welches Protokoll/welcher Standard ermöglicht diese EV-Smart-Home-Funktion?": "Which protocol/standard enables this EV smart-home function?",
"Welches Stadion fasst mehr Zuschauer?": "Which stadium holds more spectators?",
"Welches Stadion wurde frueher erbaut?": "Which stadium was built earlier?",
"Welches Ziel hat diese Raumsonde angesteuert?": "Which target did this space probe head for?",
"Welches antike Bauwerk ist höher?": "Which ancient structure is taller?",
"Welches antike Straßennetz ist länger?": "Which ancient road network is longer?",
"Welches stratigraphische Grundprinzip wird hier beschrieben?": "Which basic stratigraphic principle is described here?",
"Wer entdeckte oder ergrub diese Fundstätte?": "Who discovered or excavated this site?",
"Wer erzielte mehr Tore in einer Saison?": "Who scored more goals in one season?",
"Wer gewann mehr Olympia-Goldmedaillen?": "Who won more Olympic gold medals?",
"Wer haelt diesen Weltrekord?": "Who holds this world record?",
"Wer hat einen hoeheren Marktwert?": "Who has a higher market value?",
"Wer hob mehr? (Reissen + Stossen zusammen)": "Who lifted more? (snatch + clean & jerk combined)",
"Wer sprang hoeher?": "Who jumped higher?",
"Wer verdient mehr pro Jahr?": "Who earns more per year?",
"Wessen Bau hat länger gedauert?": "Whose construction took longer?",
"Wie historisch korrekt ist diese Darstellung?": "How historically accurate is this depiction?",
"Wie viele Spieler umfasst eine Mannschaft bei diesem Feldsport?": "How many players does a team have in this field sport?",
"Wie wurde diese archäologische Entdeckung gemacht?": "How was this archaeological discovery made?",
"Wo befinden sich diese Steilküsten / Klippen?": "Where are these sea cliffs?",
"Wo befinden sich diese prähistorischen Höhlenmalereien?": "Where are these prehistoric cave paintings?",
"Wo befinden sich diese prähistorischen Pfahlbauten?": "Where are these prehistoric pile dwellings?",
"Wo befindet sich diese EV-Batterie-Gigafactory?": "Where is this EV battery gigafactory?",
"Wo befindet sich diese EV-Batterie-Recyclinganlage?": "Where is this EV battery recycling plant?",
"Wo befindet sich dieser bedeutende Ladepark?": "Where is this major charging park?",
"Wo befindet sich dieser bedeutende Solarpark?": "Where is this major solar park?",
"Wo befindet sich dieses Batterie-Forschungsinstitut?": "Where is this battery research institute?",
"Wo befindet sich dieses Teleskop oder Observatorium?": "Where is this telescope or observatory?",
"Wo befindet sich dieses bedeutende Lithiumvorkommen oder -bergwerk?": "Where is this major lithium deposit or mine?",
"Wo fand dieser Meilenstein der frühen Elektromobilität statt?": "Where did this milestone of early electric mobility take place?",
"Wo fand dieser historische Meilenstein der Elektromobilität statt?": "Where did this historic milestone of electric mobility take place?",
"Wo hat diese digitale Archäologie-Institution ihren Sitz?": "Where is this digital archaeology institution based?",
"Wo hat dieses E-Fahrzeug-Startup seinen Hauptsitz?": "Where is this EV startup headquartered?",
"Wo liegt diese Geothermalquelle?": "Where is this geothermal spring?",
"Wo liegt diese Grand-Slam-Tennis-Arena?": "Where is this Grand Slam tennis arena?",
"Wo liegt diese Maya- oder Inka-Ruine?": "Where is this Maya or Inca ruin?",
"Wo liegt diese Megalithanlage?": "Where is this megalithic site?",
"Wo liegt diese Mine oder dieses Bohrprojekt?": "Where is this mine or drilling project?",
"Wo liegt diese Motorsport-Rennstrecke?": "Where is this motorsport racetrack?",
"Wo liegt diese Schlucht / dieser Canyon?": "Where is this gorge / canyon?",
"Wo liegt diese Wikinger-Siedlung heute?": "Where is this Viking settlement today?",
"Wo liegt diese Wüste oder Wüstenlandschaft?": "Where is this desert or desert landscape?",
"Wo liegt diese bedeutende Fossilien-Fundstätte?": "Where is this important fossil site?",
"Wo liegt diese berühmte Felsformation?": "Where is this famous rock formation?",
"Wo liegt diese berühmte Nekropole?": "Where is this famous necropolis?",
"Wo liegt diese verlassene Wüstenstadt?": "Where is this abandoned desert city?",
"Wo liegt diese versunkene Stadt?": "Where is this sunken city?",
"Wo liegt dieser Geysir?": "Where is this geyser?",
"Wo liegt dieser Gletscher?": "Where is this glacier?",
"Wo liegt dieser Marathon-Start/-Ziel?": "Where is this marathon start/finish?",
"Wo liegt dieser Meteoritenkrater?": "Where is this meteorite crater?",
"Wo liegt dieser Nationalpark mit besonderer Geologie?": "Where is this national park with notable geology?",
"Wo liegt dieser Ozeangraben / tiefste Punkt?": "Where is this ocean trench / deepest point?",
"Wo liegt dieser Vulkan?": "Where is this volcano?",
"Wo liegt dieser Wintersport-Ort?": "Where is this winter sports resort?",
"Wo liegt dieser beruehmt Golfplatz?": "Where is this famous golf course?",
"Wo liegt dieser tektonische Graben / diese Spalte?": "Where is this tectonic rift / fissure?",
"Wo liegt dieser weltberuehmt Surfspot?": "Where is this world-famous surf spot?",
"Wo liegt dieses Dark-Sky-Reservat?": "Where is this Dark Sky Reserve?",
"Wo liegt dieses Fussballstadion?": "Where is this football stadium?",
"Wo liegt dieses Höhlensystem?": "Where is this cave system?",
"Wo liegt dieses Observatorium?": "Where is this observatory?",
"Wo liegt dieses Olympiastadion?": "Where is this Olympic stadium?",
"Wo liegt dieses Raumfahrtkontrollzentrum?": "Where is this spaceflight control centre?",
"Wo liegt dieses Raumfahrtzentrum / diese Startrampe?": "Where is this space centre / launch pad?",
"Wo liegt dieses beruehmt Klettergebiet?": "Where is this famous climbing area?",
"Wo liegt dieses beruehmt Skigebiet?": "Where is this famous ski area?",
"Wo liegt dieses berühmte Schiffswrack?": "Where is this famous shipwreck?",
"Wo liegt dieses römische Grenzkastell oder dieser Limesabschnitt?": "Where is this Roman border fort or limes section?",
"Wo sitzt der Ladeanschluss bei diesem Fahrzeug?": "Where is the charging port located on this vehicle?",
"Wo werden autonome Fahrzeuge getestet?": "Where are autonomous vehicles tested?",
"Wo wird dieses Artefakt aufbewahrt?": "Where is this artefact kept?",
"Wo wurde dieser Sensationsfund gemacht?": "Where was this sensational find made?",
"Wofür steht dieses E-Mobilitäts-Akronym?": "What does this e-mobility acronym stand for?",
"Wofür wird dieses Gestein / Mineral hauptsächlich genutzt?": "What is this rock / mineral mainly used for?",
"Wozu wird dieses Mineral oder Gestein hauptsaechlich verwendet?": "What is this mineral or rock mainly used for?",
"Zu welchem Gebirge gehört dieser Berg?": "Which mountain range does this mountain belong to?",
"Zu welchem Sternenhimmel gehört dieses Sternbild hauptsächlich?": "Which sky does this constellation mainly belong to?",
"Zu welchem Typ gehört dieser Himmelskörper?": "Which type does this celestial body belong to?",
"Zu welcher Gesteinsklasse gehoert dieses Gestein?": "Which rock class does this rock belong to?",
"Zu welcher Kultur gehört diese Gottheit?": "Which culture does this deity belong to?",
"Zu welcher Raumfahrtagentur gehoert diese Mission?": "Which space agency does this mission belong to?",
"Zu welcher Sportdisziplin gehoert diese Uebung?": "Which sport discipline does this exercise belong to?",
"Über welche Handelsroute kam dieses Gut?": "Via which trade route did this good arrive?",
}

UNITS_EN = {
"Anschlüsse gesamt": "ports total",
"Anzahl Objekte (ca.)": "number of objects (approx.)",
"Baujahr": "year built",
"GB Scandaten": "GB of scan data",
"Goldmedaillen": "gold medals",
"Gruendungsjahr": "year founded",
"Hektar": "hectares",
"Jahr": "year",
"Jahr der Entdeckung": "year of discovery",
"Jahre BP (vor heute)": "years BP (before present)",
"Jahre Bauzeit (geschätzt)": "years of construction (estimated)",
"Jahre v. Chr.": "years BC",
"Lichtjahre": "light-years",
"Meter Höhe": "metres height",
"Meter Tiefe": "metres depth",
"Millionen Jahre": "million years",
"Minuten (10–80%)": "minutes (10–80%)",
"Mio Euro": "million euros",
"Mio Euro/Jahr": "million euros/year",
"Mio. EUR Schätzwert": "million EUR estimated value",
"Mio. km": "million km",
"Mohs-Härtegrad": "Mohs hardness",
"Monde": "moons",
"Nm": "Nm",
"Richter-Skala": "Richter scale",
"Sekunden (0-100 km/h)": "seconds (0-100 km/h)",
"Tage (Betrieb bis 2026)": "days (operation until 2026)",
"Tonnen": "tonnes",
"Tore": "goals",
"Tsd. EUR": "thousand EUR",
"Tsd. Plaetze": "thousand seats",
"Volt": "volts",
"Vulkanexplosivitätsindex (VEI)": "Volcanic Explosivity Index (VEI)",
"Zellen (gesamt)": "cells (total)",
"cm": "cm",
"cw × 1000": "Cd × 1000",
"kW (DC max.)": "kW (DC max.)",
"kWh (nutzbar)": "kWh (usable)",
"kg": "kg",
"kg (Leergewicht)": "kg (kerb weight)",
"km": "km",
"km (WLTP)": "km (WLTP)",
"km (kartierte Länge)": "km (mapped length)",
"km Gesamtlänge": "km total length",
"km³ (Eisvolumen)": "km³ (ice volume)",
"m": "m",
"m (Tiefe unter Erdoberfläche)": "m (depth below surface)",
"m (Tiefe)": "m (depth)",
"m (maximale Wellenhöhe)": "m (maximum wave height)",
"m/s²": "m/s²",
"mm/Jahr (Driftgeschwindigkeit)": "mm/year (drift speed)",
"t (Nutzlast LEO)": "t (payload LEO)",
"°C (Durchschnitt)": "°C (average)",
"°C (Schmelzpunkt)": "°C (melting point)",
}

FIXEDOPTS_EN = {
"Alter": "Age",
"Antike": "Antiquity",
"Atlantikhandel": "Atlantic trade",
"Autobahn": "Motorway",
"Bauarbeiten": "Construction work",
"Bernsteinstraße": "Amber Road",
"Bodenradar": "Ground-penetrating radar",
"Bronzezeit": "Bronze Age",
"Cross-Cutting": "Cross-cutting relationships",
"Dendrochronologie": "Dendrochronology",
"Dorisch": "Doric",
"Eisenzeit": "Iron Age",
"Ernährung": "Diet",
"Geräusch": "Noise",
"Gewicht": "Weight",
"Gleichstrom": "Direct current",
"Griechenland": "Greece",
"Grip": "Grip",
"Handel": "Trade",
"Heizen": "Heating",
"Herkunft": "Origin",
"Historisch falsch": "Historically incorrect",
"Horizontalität": "Original horizontality",
"Indien": "India",
"Induktion": "Induction",
"Ionisch": "Ionic",
"Isolieren": "Insulating",
"Kabel wegräumen": "Stow the cable",
"Klima": "Climate",
"Klimawandel": "Climate change",
"Komplett erfunden": "Completely fabricated",
"Korinthisch": "Corinthian",
"Krieg": "War",
"Kälte": "Cold",
"Kühlen": "Cooling",
"Laden abbrechen": "Abort charging",
"Landwirt": "Farmer",
"Landwirtschaft": "Agriculture",
"Laserscanning": "Laser scanning",
"Level 1": "Level 1",
"Level 2": "Level 2",
"Level 3": "Level 3",
"Level 4/5": "Level 4/5",
"Magnetometrie": "Magnetometry",
"Mesopotamien": "Mesopotamia",
"Metalldetektoren": "Metal detectors",
"Mittelalter": "Middle Ages",
"Neolithikum": "Neolithic",
"Neuzeit": "Modern era",
"Nicht blockieren": "Do not block",
"Original Continuity": "Original continuity",
"Paläolithikum": "Palaeolithic",
"Permanentmagnet": "Permanent magnet",
"Photogrammetrie": "Photogrammetry",
"Priorität": "Priority",
"Regeln": "Rules",
"Reichweite": "Range",
"Religion": "Religion",
"Reluktanz": "Reluctance",
"Seidenstraße": "Silk Road",
"Stark vereinfacht": "Heavily simplified",
"Steinzeit": "Stone Age",
"Stonehenge-Kultur": "Stonehenge culture",
"Stratigraphie": "Stratigraphy",
"Superposition": "Superposition",
"Taucher": "Diver",
"Thermolumineszenz": "Thermoluminescence",
"Toskanisch": "Tuscan",
"Tourismus": "Tourism",
"Urbanisierung": "Urbanisation",
"Urgeschichte": "Prehistory",
"Wanderer": "Hiker",
"Weihrauchstraße": "Incense Route",
"Weitgehend korrekt": "Largely correct",
"Ägypten": "Egypt",
"Afghanistan": "Afghanistan",
"China": "China",
"Iran": "Iran",
"Pakistan": "Pakistan",
}

EN = {}
EN.update(PROMPTS_EN); EN.update(UNITS_EN); EN.update(FIXEDOPTS_EN)

# --- merge into _CONTENT_I18N.en, validate keys exist in .pl ---
def block(src, name):
    a = src.index(name + '=') + len(name + '=')
    d = 0; k = a; ins = None; esc = False
    while k < len(src):
        c = src[k]
        if ins:
            if esc: esc = False
            elif c == '\\': esc = True
            elif c == ins: ins = None
        else:
            if c in '"\'`': ins = c
            elif c == '{': d += 1
            elif c == '}':
                d -= 1
                if d == 0: k += 1; break
        k += 1
    return a, k, src[a:k]

s_idx, e_idx, obj = block(content, 'const _CONTENT_I18N')
data = json.loads(obj)
missing = [de for de in EN if de not in data.get('pl', {})]
assert not missing, ('Schluessel nicht in pl gefunden: ' + repr(missing[:5]) + f' ({len(missing)} total)')
data.setdefault('en', {}).update(EN)
content = content[:s_idx] + json.dumps(data, ensure_ascii=False) + content[e_idx:]
print(f'[OK]   _CONTENT_I18N.en += {len(EN)} (Prompts {len(PROMPTS_EN)}, Einheiten {len(UNITS_EN)}, fixedOpts {len(FIXEDOPTS_EN)})')

_tmp = GEN + '.tmp'
open(_tmp, 'w', encoding='utf-8').write(content)
os.replace(_tmp, GEN)
print('\nPatch complete.')
